### ISSUE TITLE
Fragment 里Recycylerview 里点击播放第二个视频报错

### ISSUE THREAD

**Issue by huminted** [lipangit/JieCaoVideoPlayer#1008]
Process: com.iwakeup.kaixue, PID: 23173
                                                                    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.iwakeup.kaixue/com.iwakeup.kaixue.Control.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.support.v7.app.ActionBar android.support.v7.app.AppCompatActivity.getSupportActionBar()' on a null object reference
                                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2414)
                                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2477)
                                                                        at android.app.ActivityThread.access$800(ActivityThread.java:160)
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1368)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                        at android.os.Looper.loop(Looper.java:135)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5372)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at java.lang.reflect.Method.invoke(Method.java:372)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1117)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:810)

**Comment by lipangit** [comment]
继承AppCompactactivity了吗

**Comment by huminted** [comment]
麻烦了开发者了，继承AppCompactactivity后已经解决了。
