### ISSUE TITLE
你好  播放一次 关掉  再播放  报异常   是在Activity 中的

### ISSUE THREAD

**Issue by 18667366881** [lipangit/JieCaoVideoPlayer#1021]
java.lang.NullPointerException: Attempt to invoke virtual method fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.hideSupportActionBar(JCVideoPlayer.java:864)
                                                                 at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.startWindowFullscreen(JCVideoPlayer.java:638)
                                                                 at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.onClick(JCVideoPlayer.java:190)
                                                                 at fm.jiecao.jcvideoplayer_lib.JCVideoPlayerStandard.onClick(JCVideoPlayerStandard.java:176)
                                                                 at android.view.View.performClick(View.java:5207)
                                                                 at android.view.View$PerformClick.run(View.java:21177)
                                                                 at android.os.Handler.handleCallback(Handler.java:739)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                 at android.os.Looper.loop(Looper.java:148)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:5458)
                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)

**Comment by lipangit** [comment]
包含jcvd的activity要继承Appcompactactivity
