### ISSUE TITLE
oppo r9splus 全屏，打横，直接退出列表界面

### ISSUE THREAD

**Issue by madreain** [lipangit/JieCaoVideoPlayer#1037]
queueIdle exception
                                                            java.lang.IllegalStateException: Activity has been destroyed
                                                                at android.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1449)
                                                                at android.app.BackStackRecord.commitInternal(BackStackRecord.java:687)
                                                                at android.app.BackStackRecord.commitAllowingStateLoss(BackStackRecord.java:667)
                                                                at com.android.contacts.activities.OppoContactsTabActivity.showContactsFragmentInternal(OppoContactsTabActivity.java:229)
                                                                at com.android.contacts.activities.OppoContactsTabActivity$2.queueIdle(OppoContactsTabActivity.java:557)
                                                                at android.os.MessageQueue.next(MessageQueue.java:392)
                                                                at android.os.Looper.loop(Looper.java:163)
                                                                at android.app.ActivityThread.main(ActivityThread.java:5739)
                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:676)

**Comment by lipangit** [comment]
Activity has been destroyed 不知道这个log是怎么引起的

demo在r9上有问题吗

**Comment by madreain** [comment]
问题已经找到，谢谢哈，上级的activity需要也支持横竖屏切换，要不然就容易出错，因为里面不仅使用了你们的视频播放控件，还有其他的特殊效果

**Comment by lipangit** [comment]
好
