### ISSUE TITLE
AppTheme.NoActionBar 使用情况下会报null

### ISSUE THREAD

**Issue by zhouguanglian** [lipangit/JieCaoVideoPlayer#1068]
java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.Window android.app.Activity.getWindow()' on a null object reference
                                                                at fm.jiecao.jcvideoplayer_lib.g.b(JCVideoPlayer.java:863)
                                                                at fm.jiecao.jcvideoplayer_lib.g.s(JCVideoPlayer.java:578)
                                                                at fm.jiecao.jcvideoplayer_lib.g.m(JCVideoPlayer.java:514)
                                                                at fm.jiecao.jcvideoplayer_lib.j.m(JCVideoPlayerStandard.java:838)
                                                                at fm.jiecao.jcvideoplayer_lib.h.d(JCVideoPlayerManager.java:42)
                                                                at fm.jiecao.jcvideoplayer_lib.g.a(JCVideoPlayer.java:323)
                                                                at com.tn.omg.jiecaovideoplayer.MyJCVideoPlayerStandard.a(MyJCVideoPlayerStandard.java:56)

**Comment by zhouguanglian** [comment]
JCVideoPlayer.TOOL_BAR_EXIST = false;
JCVideoPlayer.ACTION_BAR_EXIST = false;
通过这个已解决

**Comment by lipangit** [comment]
好
