### ISSUE TITLE
void android.app.Activity.setRequestedOrientation(int)' on a null object reference

### ISSUE THREAD

**Issue by zhouguanglian** [lipangit/JieCaoVideoPlayer#1069]
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Activity.setRequestedOrientation(int)' on a null object reference
                                                                at fm.jiecao.jcvideoplayer_lib.g.m(JCVideoPlayer.java:515)
                                                                at fm.jiecao.jcvideoplayer_lib.j.m(JCVideoPlayerStandard.java:838)
                                                                at fm.jiecao.jcvideoplayer_lib.h.d(JCVideoPlayerManager.java:42)
                                                                at fm.jiecao.jcvideoplayer_lib.g.a(JCVideoPlayer.java:323)
                                                                at com.tn.omg.jiecaovideoplayer.MyJCVideoPlayerStandard.a(MyJCVideoPlayerStandard.java:56)
                                                                at fm.jiecao.jcvideoplayer_lib.g.onClick(JCVideoPlayer.java:171)
                                                                at fm.jiecao.jcvideoplayer_lib.j.onClick(JCVideoPlayerStandard.java:208)
                                                                at com.tn.omg.jiecaovideoplayer.MyJCVideoPlayerStandard.onClick(MyJCVideoPlayerStandard.java:38)

**Comment by zhouguanglian** [comment]
JCUtils.getAppCompActivity(getContext()) 问题出在这里 
getContext()：获得的类  android.view.ContextThemeWrapper@5278e3a
getContext() instanceof ContextThemeWrapper：返回 false 
                   最后导致JCUtils.getAppCompActivity(getContext())返回null 
 JCUtils.getAppCompActivity(getContext()).setRequestedOrientation(NORMAL_ORIENTATION);就空指针异常了

**Comment by lipangit** [comment]
包含视频的activity必须继承APPCompactactivity

**Comment by lipangit** [comment]
正在考虑用反射去做，不依赖Appcompactactivity

**Comment by zhouguanglian** [comment]
用的Fragment，那就坐等解除这个依赖，不然用不了。

**Comment by lipangit** [comment]
activity继承APPCompactactivity就不应该有这问题。

**Comment by zhouguanglian** [comment]
JCUtils里面的getAppCompActivity 多加了一个判断
if (context instanceof AppCompatActivity) {
            return (AppCompatActivity) context;
        } else if (context instanceof ContextThemeWrapper) {
            return getAppCompActivity(((ContextThemeWrapper) context).getBaseContext());
        }else if (context instanceof android.view.ContextThemeWrapper){
            return getAppCompActivity(((android.view.ContextThemeWrapper) context).getBaseContext());
        }
加上这一句 就可以了，我是用activity里 包含的Fragment

**Comment by zhouguanglian** [comment]
onStatePause 这个方法不是暂停吗？
我调用之后，点击视频，又重头开始播放了。

**Comment by lipangit** [comment]
这个函数不能调，只能复写，如果想暂停就startButton.performClick()

**Comment by zhouguanglian** [comment]
了解了，完美解决。
感激付出^_^

**Comment by lipangit** [comment]
好

**Comment by HaoPz** [comment]
加上这个句话，没有效果呀。修改extends 是没有问题的。
else if (context instanceof android.view.ContextThemeWrapper){
return getAppCompActivity(((android.view.ContextThemeWrapper) context).getBaseContext());
}
请问您是怎么判断的？

**Comment by lipangit** [comment]
@HaoPz 什么需求
