### ISSUE TITLE
存在内存泄漏

### ISSUE THREAD

**Issue by xiongke15117937934** [lipangit/JieCaoVideoPlayer#1142]
存在内存泄漏？

**Comment by xiongke15117937934** [comment]
每次都会泄漏？

**Comment by xiongke15117937934** [comment]
调用这个
```
@Override
    protected void onDestroy() {
        JCVideoPlayerManager.completeAll();
        super.onDestroy();
    }
```
避免内存泄漏导致
` ```
  Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.support.v7.app.ActionBar android.support.v7.app.AppCompatActivity.getSupportActionBar()' on a null object reference
                                                                      at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.showSupportActionBar(JCVideoPlayer.java:909)
                                                                      at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.clearFullscreenLayout(JCVideoPlayer.java:623)
                                                                      at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.onCompletion(JCVideoPlayer.java:558)
                                                                      at fm.jiecao.jcvideoplayer_lib.JCVideoPlayerStandard.onCompletion(JCVideoPlayerStandard.java:909)
                                                                      at fm.jiecao.jcvideoplayer_lib.JCVideoPlayerManager.completeAll(JCVideoPlayerManager.java:42)
                                                                      at com.xk.gvido.app.ui.activity.VideoDetailActivity.onDestroy(VideoDetailActivity.java:99)
                                                                      at android.app.Activity.performDestroy(Activity.java:6422)
                                                                      at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1142)
                                                                      at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3818)
                                                                      at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3849) 
                                                                      at android.app.ActivityThread.-wrap5(ActivityThread.java) 
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1398) 
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                      at android.os.Looper.loop(Looper.java:148) 
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                      at java.lang.reflect.Method.invoke(Native Method) 
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) `
```
就一定要设置actionbar吗？

**Comment by xiongke15117937934** [comment]
点击 全屏也报错，但是清单中设置了 样式。

**Comment by lipangit** [comment]
android.support.v7.app.AppCompatActivity.getSupportActionBar()' on a null object reference 

这不是内存泄漏，包含jcvd的activity要继承Appcompactactivity

**Comment by xiongke15117937934** [comment]
找到原因了 我的AppBarLayout样式继承了actionbar的 但是actvity没有用actionbar的.
