### ISSUE TITLE
不继承AppCompatActivity各种报错

### ISSUE THREAD

**Issue by SnowJun** [lipangit/JieCaoVideoPlayer#1163]
未继承AppCompatActivity  点击重新播放就崩溃
   java.lang.NullPointerException
                                                                                   at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.onCompletion(JCVideoPlayer.java:559)
                                                                                   at fm.jiecao.jcvideoplayer_lib.JCVideoPlayerStandard.onCompletion(JCVideoPlayerStandard.java:909)
                                                                                   at fm.jiecao.jcvideoplayer_lib.JCVideoPlayerManager.completeAll(JCVideoPlayerManager.java:42)
                                                                                   at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.startVideo(JCVideoPlayer.java:348)
                                                                                   at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.onClick(JCVideoPlayer.java:196)
                                                                                   at fm.jiecao.jcvideoplayer_lib.JCVideoPlayerStandard.onClick(JCVideoPlayerStandard.java:230)

**Comment by lipangit** [comment]
点击全屏按钮报错吗，log里的nullpointe是哪个变量为空导致的

**Comment by SnowJun** [comment]
不是全屏按钮   是加载失败  感叹号出来的时候点感叹号，是actionbar空了

**Comment by SnowJun** [comment]
![image](https://user-images.githubusercontent.com/13073084/29492817-cdc4054e-85ba-11e7-9ef9-cda07c383c6a.png)
这块直接空了

**Comment by lipangit** [comment]
对，不继承Appcompactactivity就会这样，如果没有复杂的style的话可以直接替换成Appcompactactivity

**Comment by lipangit** [comment]
测试一下，其他地方没问题就好

**Comment by SnowJun** [comment]
目前还没有发现问题，不会出现崩溃了，谢谢。

**Comment by lipangit** [comment]
好
