### ISSUE TITLE
.NoSuchFieldError: No static field bottom_seek_progress of type I in class Lfm/jiecao/jcvideoplayer_lib/R$id; or its superclasses (declaration of 'fm.jiecao.jcvideoplayer_lib.R$id' appears in /data/app/com.example.admin.myapplication-2/base.apk)

### ISSUE THREAD

**Issue by androiddream** [lipangit/JieCaoVideoPlayer#1186]
.NoSuchFieldError: No static field bottom_seek_progress of type I in class Lfm/jiecao/jcvideoplayer_lib/R$id; or its superclasses (declaration of 'fm.jiecao.jcvideoplayer_lib.R$id' appears in /data/app/com.example.admin.myapplication-2/base.apk)

**Comment by androiddream** [comment]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.admin.myapplication/com.example.admin.myapplication.util.VideoEditActivity}: android.view.InflateException: Binary XML file line #17: Error inflating class fm.jiecao.jcvideoplayer_lib.JCVideoPlayerStandard
                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2339)
                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2413)
                                                                                   at android.app.ActivityThread.access$800(ActivityThread.java:155)
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1317)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                   at android.os.Looper.loop(Looper.java:135)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5343)
                                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                                   at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
                                                                                Caused by: android.view.InflateException: Binary XML file line #17: Error inflating class fm.jiecao.jcvideoplayer_lib.JCVideoPlayerStandard
                                                                                   at android.view.LayoutInflater.createView(LayoutInflater.java:633)
                                                                                   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
                                                                                   at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
                                                                                   at android.view.LayoutInflater.parseInclude(LayoutInflater.java:916)
                                                                                   at android.view.LayoutInflater.rInflate(LayoutInflater.java:802)
                                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
                                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
                                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
                                                                                   at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:292)
                                                                                   at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
                                                                                   at com.example.admin.myapplication.util.VideoEditActivity.onCreate(VideoEditActivity.java:20)
                                                                                   at android.app.Activity.performCreate(Activity.java:6010)
                                                                                   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1129)
                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2292)
                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2413) 
                                                                                   at android.app.ActivityThread.access$800(ActivityThread.java:155) 
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1317) 
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                   at android.os.Looper.loop(Looper.java:135) 
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5343) 
                                                                                   at java.lang.reflect.Method.invoke(Native Method) 
                                                                                   at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905) 
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700) 
                                                                                Caused by: java.lang.reflect.InvocationTargetException
                                                                                   at java.lang.reflect.Constructor.newInstance(Native Method)
                                                                                   at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
                                                                                   at android.view.LayoutInflater.createView(LayoutInflater.java:607)
                                                                                   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743) 
                                                                                   at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
                                                                                   at android.view.LayoutInflater.parseInclude(LayoutInflater.java:916) 
                                                                                   at android.view.LayoutInflater.rInflate(LayoutInflater.java:802) 
                                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
                                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
                                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
                                                                                   at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:292) 
                                                                                   at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                                                   at com.example.admin.myapplication.util.VideoEditActivity.onCreate(VideoEditActivity.java:20) 
                                                                                   at android.app.Activity.performCreate(Activity.java:6010) 
                                                                                   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1129) 
                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2292) 
                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2413) 
                                                                                   at android.app.ActivityThread.access$800(ActivityThread.java:155) 
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1317) 
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                   at android.os.Looper.loop(Looper.java:135) 
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5343) 
                                                                                   at java.lang.reflect.Method.invoke(Native Method) 
                                                                                   at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905) 
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)

**Comment by lipangit** [comment]
原因是代码里的id和xml的id对不上，挨个检查控件吧，xml里是不是缺了一些控件，代码里找不到他们

**Comment by androiddream** [comment]
谢谢，可能是multidex的锅
