### ISSUE TITLE
列表播放中点击全屏，直接闪退

### ISSUE THREAD

**Issue by axeon** [lipangit/JieCaoVideoPlayer#125]
列表播放中点击全屏，直接闪退

java.lang.IllegalStateException
    at android.media.MediaPlayer.getCurrentPosition(Native Method)
    at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.getCurrentPositionWhenPlaying(JCVideoPlayer.java:673)
    at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.setTextAndProgress(JCVideoPlayer.java:694)
    at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer$4$1.run(JCVideoPlayer.java:653)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5456)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:735)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:625)
java.lang.IllegalStateException
    at android.media.MediaPlayer.getDuration(Native Method)
    at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.getDuration(JCVideoPlayer.java:685)
    at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.setTextAndProgress(JCVideoPlayer.java:695)
    at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer$4$1.run(JCVideoPlayer.java:653)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5456)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:735)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:625)
rStandardEx: 播放。。。。
java.lang.IllegalStateException
    at android.media.MediaPlayer.getCurrentPosition(Native Method)
    at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.getCurrentPositionWhenPlaying(JCVideoPlayer.java:673)
    at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.setTextAndProgress(JCVideoPlayer.java:694)
    at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer$4$1.run(JCVideoPlayer.java:653)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5456)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:735)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:625)
java.lang.IllegalStateException
    at android.media.MediaPlayer.getDuration(Native Method)
    at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.getDuration(JCVideoPlayer.java:685)
    at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.setTextAndProgress(JCVideoPlayer.java:695)
    at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer$4$1.run(JCVideoPlayer.java:653)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5456)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:735)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:625)
 setScreenOnWhilePlaying(true) is ineffective for Surface

**Comment by axeon** [comment]
发现这个问题是100%概率的。。。

**Comment by lipangit** [comment]
按照demo 继承JCVideoPlayerStandard来做，不要修改库。

**Comment by wudifamo** [comment]
原因是你的activity被销毁了,
            android:configChanges="orientation|keyboardHidden|screenSize"
            android:screenOrientation="portrait"
加上

**Comment by lipangit** [comment]
@axeon 怎么样了

@wudifamo 你是说竖屏的activity销毁了？

**Comment by lipangit** [comment]
@axeon 怎么样了

@wudifamo 你是说竖屏的activity销毁了？

**Comment by wudifamo** [comment]
是的,我也遇到过这个问题,竖屏的activity被销毁,导致MediaPlayer被release了,所以getCurrentPosition异常了,我是这么理解的

**Comment by UC10D** [comment]
我在fullScreen 中加了  
    @Override
    public void onConfigurationChanged(Configuration newConfig) {
        super.onConfigurationChanged(newConfig);
    }

**Comment by jesse920524** [comment]
@wudifamo 先感谢你的建议,再问下,是给持有Jcvplayer控件的Activity设置configChange么?
我照做了,依然不好用.
测试机型Nexus5, Android版本6.0.1
但是两台4.4.2和4.2.2的机型完全没有问题.
可以告诉我你的测试机型吗?

**Comment by wudifamo** [comment]
我是HTC X9u  Android6.0
在竖屏的activity对应的manifest加
            android:configChanges="orientation|keyboardHidden|screenSize"
            android:screenOrientation="portrait"
在activity中加
@Override
public void onConfigurationChanged(Configuration newConfig) {
super.onConfigurationChanged(newConfig);
}
 fullscreen库文件不要动.
可以参照这个http://blog.sina.com.cn/s/blog_783ede0301014og5.html

**Comment by jesse920524** [comment]
@wudifamo 
追问以下,是给持有JCVideoPlayerStandard控件的Activity设置android:configChanges="orientation|keyboardHidden|screenSize"
android:screenOrientation="portrait"
并为其@Override onConfigurationChanged方法吗?

**Comment by wudifamo** [comment]
是

**Comment by wcbcslg** [comment]
添加了，还是崩溃

**Comment by wcbcslg** [comment]
java.lang.NullPointerException
	at android.view.SurfaceView.updateWindow(SurfaceView.java:603)
	at android.view.SurfaceView.access$000(SurfaceView.java:86)
	at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:175)
	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:847)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1928)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1057)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5666)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
	at android.view.Choreographer.doCallbacks(Choreographer.java:574)
	at android.view.Choreographer.doFrame(Choreographer.java:544)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5072)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by wcbcslg** [comment]
@lipangit @wudifamo @axeon @jesse920524 你们有遇到过吗，我的listview列表在fragment里面，我点击全屏时必蹦

**Comment by lipangit** [comment]
我之前遇到的是在一个Textureview正常运行的时候，去remove它，会报这个错误

**Comment by wcbcslg** [comment]
请问怎么解决的当时 @lipangit

**Comment by lipangit** [comment]
你看log的顺序就知道remove的时机对不对了，这个问题我当时也调了很久

**Comment by wcbcslg** [comment]
还是没解决，能否说下你当时的具体解决方法 @lipangit

**Comment by wudifamo** [comment]
这个和第一次的原因不一样了啊

**Comment by lipangit** [comment]
应该是做SurfaceView动态添加的时候，总有这个错误
切换全屏的时候回删除旧的SurfaceView，这么做不行，只能保留原来SurfaceView，退出全屏继续播放要复用这个SurfaceView

**Comment by lipangit** [comment]
你能遇到这个问题肯定是大改这个库，坑会比较多

**Comment by UC10D** [comment]
代码全部更新一次。QAQ

**Comment by UC10D** [comment]
代码逻辑看一遍。哈哈哈哈，让你乱改

**Comment by wcbcslg** [comment]
@lipangit 真没大改库呀

**Comment by lipangit** [comment]
基本就是改个控件背景，改个控件位置，可以在布局文件修改，或者继承JCVideoPlayerStandard，在setUp中代码修改，不涉及逻辑的
