### ISSUE TITLE
Unable to start MainActivity

### ISSUE THREAD

**Issue by hram** [lipangit/JieCaoVideoPlayer#132]
FATAL EXCEPTION: main
   Process: fm.jiecao.jiecaovideoplayer, PID: 4115
   java.lang.RuntimeException: Unable to start activity ComponentInfo{fm.jiecao.jiecaovideoplayer/fm.jiecao.jiecaovideoplayer.MainActivity}: android.view.InflateException: Binary XML file line #36: Error inflating class android.support.v7.widget.Toolbar
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2462)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2524)
       at android.app.ActivityThread.access$800(ActivityThread.java:167)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1419)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5546)
       at java.lang.reflect.Method.invoke(Native Method)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)
    Caused by: android.view.InflateException: Binary XML file line #36: Error inflating class android.support.v7.widget.Toolbar
       at android.view.LayoutInflater.createView(LayoutInflater.java:637)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:747)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:810)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:813)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:508)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:418)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
       at android.support.v7.app.AppCompatDelegateImplV7.createSubDecor(AppCompatDelegateImplV7.java:388)
       at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java:309)
       at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:273)
       at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:136)
       at fm.jiecao.jiecaovideoplayer.MainActivity.onCreate(MainActivity.java:39)
       at android.app.Activity.performCreate(Activity.java:5977)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1111)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2415)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2524) 
       at android.app.ActivityThread.access$800(ActivityThread.java:167) 
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1419) 
       at android.os.Handler.dispatchMessage(Handler.java:111) 
       at android.os.Looper.loop(Looper.java:194) 
       at android.app.ActivityThread.main(ActivityThread.java:5546) 
       at java.lang.reflect.Method.invoke(Native Method) 
       at java.lang.reflect.Method.invoke(Method.java:372) 
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964) 
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759) 
    Caused by: java.lang.reflect.InvocationTargetException
       at java.lang.reflect.Constructor.newInstance(Native Method)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
       at android.view.LayoutInflater.createView(LayoutInflater.java:611)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:747) 
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:810) 
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:813) 
       at android.view.LayoutInflater.inflate(LayoutInflater.java:508) 
       at android.view.LayoutInflater.inflate(LayoutInflater.java:418) 
       at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
       at android.support.v7.app.AppCompatDelegateImplV7.createSubDecor(AppCompatDelegateImplV7.java:388) 
       at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java:309) 
       at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:273) 
       at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:136) 
       at fm.jiecao.jiecaovideoplayer.MainActivity.onCreate(MainActivity.java:39) 
       at android.app.Activity.performCreate(Activity.java:5977) 
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1111) 
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2415) 
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2524) 
       at android.app.ActivityThread.access$800(ActivityThread.java:167) 
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1419) 
       at android.os.Handler.dispatchMessage(Handler.java:111) 
       at android.os.Looper.loop(Looper.java:194) 
       at android.app.ActivityThread.main(ActivityThread.java:5546) 
       at java.lang.reflect.Method.invoke(Native Method) 
       at java.lang.reflect.Method.invoke(Method.java:372) 
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964) 
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759) 
    Caused by: java.lang.NoSuchFieldError: No static field abc_textfield_activated_mtrl_alpha of type I in class Landroid/support/v7/appcompat/R$drawable; or its superclasses (declaration of 'android.support.v7.appcompat.R$drawable' appears in /data/data/fm.jiecao.jiecaovideoplayer/files/instant-run/dex/slice-slice_2-classes.dex)
       at android.support.v7.widget.AppCompatDrawableManager.<clinit>(AppCompatDrawableManager.java:134)
       at android.support.v7.widget.TintTypedArray.getDrawable(TintTypedArray.java:60)
       at android.support.v7.widget.Toolbar.<init>(Toolbar.java:254)
       at android.support.v7.widget.Toolbar.<init>(Toolbar.java:196)
       at java.lang.reflect.Constructor.newInstance(Native Method) 
       at java.lang.reflect.Constructor.newInstance(Constructor.java:288) 
       at android.view.LayoutInflater.createView(LayoutInflater.java:611) 
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:747) 
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:810) 
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:813) 
       at android.view.LayoutInflater.inflate(LayoutInflater.java:508) 
       at android.view.LayoutInflater.inflate(LayoutInflater.java:418) 
       at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
       at android.support.v7.app.AppCompatDelegateImplV7.createSubDecor(AppCompatDelegateImplV7.java:388) 
       at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java:309) 
       at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:273) 
       at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:136) 
       at fm.jiecao.jiecaovideoplayer.MainActivity.onCreate(MainActivity.java:39) 
       at android.app.Activity.performCreate(Activity.java:5977) 
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1111) 
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2415) 
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2524) 
       at android.app.ActivityThread.access$800(ActivityThread.java:167) 
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1419) 
       at android.os.Handler.dispatchMessage(Handler.java:111) 
       at android.os.Looper.loop(Looper.java:194) 
       at android.app.ActivityThread.main(ActivityThread.java:5546) 
       at java.lang.reflect.Method.invoke(Native Method) 
       at java.lang.reflect.Method.invoke(Method.java:372) 
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964) 
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)

**Comment by hram** [comment]
fixed after change to com.android.support:appcompat-v7:23.4.0

**Comment by lipangit** [comment]
Good luck
