### ISSUE TITLE
报错java.lang.IllegalStateException,偶发性.

### ISSUE THREAD

**Issue by zhew117** [lipangit/JieCaoVideoPlayer#162]
java.lang.IllegalStateException
                                                                    at android.media.MediaPlayer._setVideoSurface(Native Method)
                                                                    at android.media.MediaPlayer.setSurface(MediaPlayer.java:813)
                                                                    at fm.jiecao.jcvideoplayer_lib.JCMediaManager$MediaHandler.handleMessage(JCMediaManager.java:104)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                    at android.os.Looper.loop(Looper.java:145)
                                                                    at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by zhew117** [comment]
RecyclerView当中使用了

CVideoPlayerStandard jcVideoPlayerStandard = holder.getView(R.id.custom_videoplayer_standard);

            jcVideoPlayerStandard.setUp(item.getShortVideo().getVideoUrlWithToken(),"1");
            ImageLoaderUtil.displayImage(URLs.makeNormalRemoteImageUrl(
                    item.getShortVideo().getVideoPic(), thumbImageSize),jcVideoPlayerStandard.thumbImageView);

**Comment by lipangit** [comment]
在setSurface之前已经判断了isValid了，不知道为什么还能设置失败，这个好像和RecyclerView关系不大，你在调试中有啥想法吗

**Comment by zhew117** [comment]
甩锅给三星~~~

**Comment by FYSong** [comment]
跟是否三星无关，应该是mediaPlayer release了
