### ISSUE TITLE
JCVideoPlayerStandardFresco没有更新，出现inflate错误

### ISSUE THREAD

**Issue by MycroftWong** [lipangit/JieCaoVideoPlayer#177]
```
 Caused by: java.lang.ClassNotFoundException: Didn't find class "fm.jiecao.jcvideoplayer_lib.JCResizeSurfaceView" on path: DexPathList[[zip file "/data/app/com.mycroft.jcplayertest-1/base.apk"],nativeLibraryDirectories=[/data/app/com.mycroft.jcplayertest-1/lib/arm64, /vendor/lib64, /system/lib64]]
      at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
      at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
      at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
      at android.view.LayoutInflater.createView(LayoutInflater.java:575)
      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:747)
      at android.view.LayoutInflater.rInflate(LayoutInflater.java:810) 
      at android.view.LayoutInflater.rInflate(LayoutInflater.java:813) 
      at android.view.LayoutInflater.inflate(LayoutInflater.java:508) 
      at android.view.LayoutInflater.inflate(LayoutInflater.java:418) 
      at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
      at android.view.View.inflate(View.java:18802) 
      at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.init(JCVideoPlayer.java:104) 
      at com.mycroft.jcplayertest.JCVideoPlayerStandardFresco.init(JCVideoPlayerStandardFresco.java:48) 
      at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.<init>(JCVideoPlayer.java:100) 
      at com.mycroft.jcplayertest.JCVideoPlayerStandardFresco.<init>(JCVideoPlayerStandardFresco.java:0) 
      at java.lang.reflect.Constructor.newInstance(Native Method) 
      at java.lang.reflect.Constructor.newInstance(Constructor.java:288) 
      at android.view.LayoutInflater.createView(LayoutInflater.java:611) 
      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:747) 
      at android.view.LayoutInflater.rInflate(LayoutInflater.java:810) 
      at android.view.LayoutInflater.inflate(LayoutInflater.java:508) 
      at android.view.LayoutInflater.inflate(LayoutInflater.java:418) 
      at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
      at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:280) 
      at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
      at com.mycroft.jcplayertest.MainActivity.onCreate(MainActivity.java:16) 
      at android.app.Activity.performCreate(Activity.java:5975) 
      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1111) 
      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2417) 
      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2526) 
      at android.app.ActivityThread.access$800(ActivityThread.java:169) 
      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1421) 
      at android.os.Handler.dispatchMessage(Handler.java:111) 
      at android.os.Looper.loop(Looper.java:194) 
      at android.app.ActivityThread.main(ActivityThread.java:5549) 
      at java.lang.reflect.Method.invoke(Native Method) 
      at java.lang.reflect.Method.invoke(Method.java:372) 
      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964) 
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759) 
      	Suppressed: java.lang.ClassNotFoundException: Didn't find class "fm.jiecao.jcvideoplayer_lib.JCResizeSurfaceView"
```

**Comment by lipangit** [comment]
好
