### ISSUE TITLE
全屏播放时当视屏无法播放时，点击退出键报错

### ISSUE THREAD

**Issue by jas0nchen** [lipangit/JieCaoVideoPlayer#190]
java.lang.IllegalStateException
                                                                     at android.media.MediaPlayer._stop(Native Method)
                                                                     at android.media.MediaPlayer.stop(MediaPlayer.java:1077)
                                                                     at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.backFullscreen(JCVideoPlayer.java:721)
                                                                     at fm.jiecao.jcvideoplayer_lib.JCFullScreenActivity.onBackPressed(JCFullScreenActivity.java:99)
                                                                     at android.app.Activity.onKeyUp(Activity.java:2210)
                                                                     at android.view.KeyEvent.dispatch(KeyEvent.java:2664)
                                                                     at android.app.Activity.dispatchKeyEvent(Activity.java:2440)
                                                                     at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:2018)
                                                                     at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:3848)
                                                                     at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3822)
                                                                     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3395)
                                                                     at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3445)
                                                                     at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3414)
                                                                     at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3521)
                                                                     at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3422)
                                                                     at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3578)
                                                                     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3395)
                                                                     at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3445)
                                                                     at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3414)
                                                                     at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3422)
                                                                     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3395)
                                                                     at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3445)
                                                                     at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3414)
                                                                     at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3554)
                                                                     at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:3714)
                                                                     at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2010)
                                                                     at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1704)
                                                                     at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1695)
                                                                     at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:1987)
                                                                     at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
                                                                     at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                     at android.os.MessageQueue.next(MessageQueue.java:138)
                                                                     at android.os.Looper.loop(Looper.java:123)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5146)
                                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                                     at java.lang.reflect.Method.invoke(Method.java:515)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612)
                                                                     at dalvik.system.NativeStart.main(Native Method)

**Comment by wudifamo** [comment]
我刚也遇到了这个问题,操作是直接用全屏打开地址错误的视频连接
解决办法是在JCVideoPlayer的 backFullscreen中添加
```
public void backFullscreen() {
		Log.d(TAG, "quitFullscreen [" + this.hashCode() + "] ");
		IF_FULLSCREEN_FROM_NORMAL = false;
		if (mIfFullscreenIsDirectly) {
			**if (mCurrentState != CURRENT_STATE_ERROR) {**
				JCMediaManager.instance().mediaPlayer.stop();
			**}**
			finishFullscreenActivity();
		} else {
			CLICK_QUIT_FULLSCREEN_TIME = System.currentTimeMillis();
			IF_RELEASE_WHEN_ON_PAUSE = false;
			quitFullScreenGoToNormal();
		}
	}
```

**Comment by jas0nchen** [comment]
嗯，谢谢，你可以PR一下

**Comment by lipangit** [comment]
@jas0nchen  有道理
