### ISSUE TITLE
 java.lang.ClassCastException: android.view.ContextThemeWrapper cannot be cast to android.app.Activity

### ISSUE THREAD

**Issue by keepfit** [lipangit/JieCaoVideoPlayer#191]
集成中遇到这个问题，求解：

FATAL EXCEPTION: main
                                                                     Process: com.inoknok.unichat, PID: 32669
                                                                     java.lang.ClassCastException: android.view.ContextThemeWrapper cannot be cast to android.app.Activity
                                                                         at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.prepareVideo(JCVideoPlayer.java:291)
                                                                         at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.startButtonLogic(JCVideoPlayer.java:278)
                                                                         at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.onClick(JCVideoPlayer.java:219)
                                                                         at fm.jiecao.jcvideoplayer_lib.JCVideoPlayerStandard.onClick(JCVideoPlayerStandard.java:153)
                                                                         at android.view.View.performClick(View.java:4760)
                                                                         at android.view.View$PerformClick.run(View.java:19762)
                                                                         at android.os.Handler.handleCallback(Handler.java:739)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                         at android.os.Looper.loop(Looper.java:135)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5336)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at java.lang.reflect.Method.invoke(Method.java:372)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)

**Comment by jas0nchen** [comment]
我也遇到了，你是不是把view放在了CoordinatorLayout或者之类的里面？不要放在这里面就好了

**Comment by UC10D** [comment]
CoordinatorLayout  的子view好像有限，之前做别的试了下就改了，没时间研究。理论上groupview 应该是都可以添加子view的。看这个log，好像是 转换出问题。

**Comment by keepfit** [comment]
试了试确实可以了，谢谢！

**Comment by lipangit** [comment]
加油 ^o^

**Comment by e16din** [comment]
I have the same issue in 3.6.3 version:

java.lang.ClassCastException: android.view.ContextThemeWrapper cannot be cast to android.app.Activity
                                                                  at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.prepareVideo(JCVideoPlayer.java:294)
                                                                  at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.startButtonLogic(JCVideoPlayer.java:281)
                                                                  at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.access$000(JCVideoPlayer.java:38)
                                                                  at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer$1.onClick(JCVideoPlayer.java:209)
                                                                  at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:164)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                  at android.os.Looper.loop(Looper.java:135)
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5289)
                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                  at java.lang.reflect.Method.invoke(Method.java:372)
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)

**Comment by prashanthd** [comment]
I got same issue while trying to load video in dialog fragment. is there any solution?

**Comment by lipangit** [comment]
@prashanthd use 4.+， because 4.+will not start new activity.

Few days later will release 4.+ stable version.
