### ISSUE TITLE
视频播放的状态是error（没联网或服务器问题）的时候，走onPause方法或滑动listview都会崩掉

### ISSUE THREAD

**Issue by MyMoonCat** [lipangit/JieCaoVideoPlayer#203]
视频播放的状态是error（没联网或服务器问题）的时候，走onPause方法或滑动listview都会崩掉 
java.lang.IllegalStateException
      at android.media.MediaPlayer._stop(Native Method)
      at android.media.MediaPlayer.stop(MediaPlayer.java:1087)
      at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.releaseAllVideos(JCVideoPlayer.java:702)
      at com.example.ly.videoplayerdemo.MainActivity$2.onClick(MainActivity.java:53)
      at android.view.View.performClick(View.java:4463)

问题代码 JCMediaManager.intance().mediaPlayer.stop();

**Comment by MyMoonCat** [comment]
看了一下，大神后续是准备基于ijkplayer了啊，到时候也可以支持本地播放了

**Comment by lipangit** [comment]
恩，这是个问题，我研究一下

**Comment by anjiao** [comment]
你好 在listview 中 你怎么判断往上滚动  然后不可见的时候 停掉了播放 这个逻辑是哪里 我好想没看懂

**Comment by lipangit** [comment]
保证列表的item是复用的，setUp的时候

**Comment by lipangit** [comment]
@MyMoonCat 现在也支持本地播放

**Comment by lipangit** [comment]
@MyMoonCat 你需要更新库了，现在releaseAllVideos里不调用stop方法，刚才试了一下，error状态走onPause方法或滑动listview不会崩溃，没发现什么问题
