### ISSUE TITLE
当应用此Lib在RecyclerView中，当我在滚出屏幕的时候会报错

### ISSUE THREAD

**Issue by wmhqnyh** [lipangit/JieCaoVideoPlayer#208]
当应用此Lib在RecyclerView中，当我在滚出屏幕的时候会报错
 java.lang.IllegalStateException
                                                                                           at android.media.MediaPlayer._setVideoSurface(Native Method)
                                                                                           at android.media.MediaPlayer.setSurface(MediaPlayer.java:742)
                                                                                           at fm.jiecao.jcvideoplayer_lib.JCMediaManager$MediaHandler.handleMessage(JCMediaManager.java:104)
                                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                           at android.os.Looper.loop(Looper.java:135)
                                                                                           at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by lipangit** [comment]
应该在demo里加个RecyclerView的例子，你能帮忙抽象一个包含RecyclerView的activity吗，然后我调试一下

**Comment by lipangit** [comment]
用新版，demo中有此功能
