### ISSUE TITLE
IllegalStateException

### ISSUE THREAD

**Issue by Maragues** [lipangit/JieCaoVideoPlayer#212]
I wasn't even looking at the screen, but this happened

```
java.lang.IllegalStateException
                                                                    
at android.media.MediaPlayer._setVideoSurface(Native Method)                                                                    
at android.media.MediaPlayer.setSurface(MediaPlayer.java:753)                                                                    
at fm.jiecao.jcvideoplayer_lib.JCMediaManager$MediaHandler.handleMessage(JCMediaManager.java:104)                                                                    
at android.os.Handler.dispatchMessage(Handler.java:102)                                                                    
at android.os.Looper.loop(Looper.java:148)                                                                    
at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by lipangit** [comment]
You maybe modify library, you should not modify library , import build.gradle only

**Comment by ivanviragine** [comment]
This is happening to me also. When scrolling up on a recyclerview with both photos and videos! I'll dig deeper...

**Comment by lipangit** [comment]
@ivanviragine @Maragues you can push a pull-request on demo , RecyclerviewActivity to show how to use in recycleView, I can check the bug more easily .

**Comment by lipangit** [comment]
update to latest stable version, some new feature.
