### ISSUE TITLE
 IjkMediaPlayer errors on version 4

### ISSUE THREAD

**Issue by ivanviragine** [lipangit/JieCaoVideoPlayer#224]
Hi,

I'm having a lot of errors running version 4 beta on Genymotion and Android Studio's emulators.

Here's a stack on Android Studio's emulator:

07-20 16:36:24.899 26206-26214/[PACKAGE] E/art: No implementation found for void tv.danmaku.ijk.media.player.IjkMediaPlayer.native_finalize() (tried Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1finalize and Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1finalize__)
07-20 16:36:24.899 26206-26214/[PACKAGE] E/System: Uncaught exception thrown by finalizer
07-20 16:36:24.899 26206-26214/[PACKAGE] E/System: java.lang.UnsatisfiedLinkError: No implementation found for void tv.danmaku.ijk.media.player.IjkMediaPlayer.native_finalize() (tried Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1finalize and Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1finalize__)
                                                                        at tv.danmaku.ijk.media.player.IjkMediaPlayer.native_finalize(Native Method)
                                                                        at tv.danmaku.ijk.media.player.IjkMediaPlayer.finalize(IjkMediaPlayer.java:862)
                                                                        at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:202)
                                                                        at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:185)
                                                                        at java.lang.Thread.run(Thread.java:818)

Here's a stack on Genymotion:

java.lang.UnsatisfiedLinkError: Couldn't load ijkffmpeg: findLibrary returned null
                                                                                at java.lang.Runtime.loadLibrary(Runtime.java:365)
                                                                                at java.lang.System.loadLibrary(System.java:535)
                                                                                at tv.danmaku.ijk.media.player.IjkMediaPlayer$1.loadLibrary(IjkMediaPlayer.java:157)
                                                                                at tv.danmaku.ijk.media.player.IjkMediaPlayer.loadLibrariesOnce(IjkMediaPlayer.java:168)
                                                                                at tv.danmaku.ijk.media.player.IjkMediaPlayer.initPlayer(IjkMediaPlayer.java:209)
                                                                                at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(IjkMediaPlayer.java:205)
                                                                                at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(IjkMediaPlayer.java:196)
                                                                                at fm.jiecao.jcvideoplayer_lib.JCMediaManager.<init>(JCMediaManager.java:82)
                                                                                at fm.jiecao.jcvideoplayer_lib.JCMediaManager.instance(JCMediaManager.java:76)
                                                                                at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.isCurrentMediaListener(JCVideoPlayer.java:752)
                                                                                at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.release(JCVideoPlayer.java:744)

**Comment by lipangit** [comment]
Real phone please, emulators not support

**Comment by ivanviragine** [comment]
@lipangit that's a very discouraging requirement, since in Android world you HAVE TO test on every possible device, and many of these tests are made on emulators. Another problem is that how can we be sure that this will not happen on real devices?

**Comment by lipangit** [comment]
That model of virtual phone can not play the video , but I think the same model real phone can play the video , so don't worry.
