### ISSUE TITLE
异常情况会导致崩溃问题

### ISSUE THREAD

**Issue by somatezyc** [lipangit/JieCaoVideoPlayer#233]
接入3.6.3版本,仅使用全屏播放功能;当播放地址非法(有前缀空格)或者无网络情况会导致crash:

E/AndroidRuntime: FATAL EXCEPTION: JieCaoVideoPlayer
                                                  Process: com.guangquaner, PID: 32198
                                                  java.lang.IllegalStateException
                                                      at android.media.MediaPlayer._setVideoSurface(Native Method)
                                                      at android.media.MediaPlayer.setSurface(MediaPlayer.java:756)
                                                      at fm.jiecao.jcvideoplayer_lib.JCMediaManager$MediaHandler.handleMessage(JCMediaManager.java:104)
                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                      at android.os.Looper.loop(Looper.java:148)
                                                      at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by lipangit** [comment]
有人反应过这个问题，正在做全新的版本，逻辑改变很大，顶(jiang)住(jiu)兄(yi)弟(xia)

**Comment by lipangit** [comment]
4.*的应该不出这个问题
