### ISSUE TITLE
Activity should not be killed

### ISSUE THREAD

**Issue by prashanthd** [lipangit/JieCaoVideoPlayer#235]
Hi,

I want use your library. The problem is when we open full screen of video it is opening new activity because of that android os may kill previous activity so I will lose data(timers,handlers) in previous activity. **Is it possible to open full screen in dialog or dialog fragment?**

**Comment by prashanthd** [comment]
Getting below exception when tried.

java.lang.ClassCastException: android.view.ContextThemeWrapper cannot be cast to android.app.Activity
                                                                at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.prepareVideo(JCVideoPlayer.java:281)
                                                                at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.startButtonLogic(JCVideoPlayer.java:268)
                                                                at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.onClick(JCVideoPlayer.java:205)
                                                                at fm.jiecao.jcvideoplayer_lib.JCVideoPlayerStandard.onClick(JCVideoPlayerStandard.java:154)

**Comment by lipangit** [comment]
Fullscreen is not activity anymore
