### ISSUE TITLE
4.5版本 ActionBar怎么隐藏

### ISSUE THREAD

**Issue by wfc505059241** [lipangit/JieCaoVideoPlayer#257]
默认是显示ActionBar       然后给activity设置了Theme.AppCompat.Light.NoActionBar 全屏就会报错
 java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.app.ActionBar.setShowHideAnimationEnabled(boolean)' on a null object reference
                                                                   at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.toWindowFullscreen(JCVideoPlayer.java:556)
                                                                   at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.onClick(JCVideoPlayer.java:186)
                                                                   at fm.jiecao.jcvideoplayer_lib.JCVideoPlayerStandard.onClick(JCVideoPlayerStandard.java:165)
                                                                   at android.view.View.performClick(View.java:4790)
                                                                   at android.view.View$PerformClick.run(View.java:19933)
                                                                   at android.os.Handler.handleCallback(Handler.java:739)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                   at android.os.Looper.loop(Looper.java:135)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:5569)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at java.lang.reflect.Method.invoke(Method.java:372)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:931)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:726)

我觉得应该在556这里加上判空

**Comment by lipangit** [comment]
判空是一种，如果actionbar是一直隐藏在全屏结束之后也不能show，这部分帮我想想怎么做好，还是抛给用户自己处理

**Comment by lipangit** [comment]
现在用两个变量手动控制了
