### ISSUE TITLE
视频播放地址无效的问题

### ISSUE THREAD

**Issue by jisuz** [lipangit/JieCaoVideoPlayer#262]
机型是：华为荣耀6
在获取到服务端数据的时候，如果视频播放地址无效有时候会抛出异常，我采用全局的异常捕获，捕获结果如下：
java.lang.IllegalStateException
	at android.media.MediaPlayer._setVideoSurface(Native Method)
	at android.media.MediaPlayer.setSurface(MediaPlayer.java:717)
	at fm.jiecao.jcvideoplayer_lib.JCMediaManager$MediaHandler.handleMessage(JCMediaManager.java:105)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.os.HandlerThread.run(HandlerThread.java:61)

想问一下群主，可不可以加一下对url的播放地址是否有效的判断哈？

**Comment by lipangit** [comment]
试试4.+，可能回避这个问题了，如果url格式有问题你可以在setUp之前自己判断一下

**Comment by jisuz** [comment]
好的
