### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by liuy9** [lipangit/JieCaoVideoPlayer#264]
java.lang.NullPointerException
                                                                                 at android.view.GLES20RenderLayer.start(GLES20RenderLayer.java:112)
                                                                                 at android.view.GLES20RenderLayer.start(GLES20RenderLayer.java:103)
                                                                                 at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1751)
                                                                                 at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1232)
                                                                                 at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6269)
                                                                                 at android.view.Choreographer$CallbackRecord.run(Choreographer.java:788)
                                                                                 at android.view.Choreographer.doCallbacks(Choreographer.java:591)
                                                                                 at android.view.Choreographer.doFrame(Choreographer.java:560)
                                                                                 at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:774)
                                                                                 at android.os.Handler.handleCallback(Handler.java:808)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:103)
                                                                                 at android.os.Looper.loop(Looper.java:193)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5310)
                                                                                 at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                 at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:832)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:648)
                                                                                 at dalvik.system.NativeStart.main(Native Method)

**Comment by lipangit** [comment]
需要更多细节，看不出来哪个变量是null

**Comment by liuy9** [comment]
只有这些log

**Comment by gaaraWB** [comment]
我也遇到这个问题，这个问题什么原因那？

**Comment by lipangit** [comment]
这个最近还有吗

**Comment by ifarhanp** [comment]
有人有任何线索吗？为什么会这样呢？

**Comment by aneeshATgithub** [comment]
Hello, please give any fix on this issue,

This crash occurs when I once logout from google login from may app and do login second time.
First time, there is no crashes. and second time , while google login app crashes and getting the following log from Android Monitor in Android Studio


FATAL EXCEPTION: main
                                                                         Process: com.brainpodium.zonmart, PID: 16935
                                                                         java.lang.NullPointerException
                                                                             at android.view.GLES20RenderLayer.start(GLES20RenderLayer.java:112)
                                                                             at android.view.GLES20RenderLayer.start(GLES20RenderLayer.java:103)
                                                                             at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1460)
                                                                             at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:996)
                                                                             at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5600)
                                                                             at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
                                                                             at android.view.Choreographer.doCallbacks(Choreographer.java:574)
                                                                             at android.view.Choreographer.doFrame(Choreographer.java:544)
                                                                             at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
                                                                             at android.os.Handler.handleCallback(Handler.java:733)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                             at android.os.Looper.loop(Looper.java:136)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                                             at java.lang.reflect.Method.invokeNative(Native Method)
                                                                             at java.lang.reflect.Method.invoke(Method.java:515)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                                             at dalvik.system.NativeStart.main(Native Method)
