### ISSUE TITLE
播放中异常退出

### ISSUE THREAD

**Issue by liuy9** [lipangit/JieCaoVideoPlayer#265]
addInArray been called, this = android.widget.RelativeLayout{4276a2c8 V.E...C. ......ID 0,0-720,400 #7f0b0076 app:id/surface_container}call stack =
                                                                        java.lang.Throwable: addInArray
                                                                            at android.view.ViewGroup.addInArray(ViewGroup.java:3786)
                                                                            at android.view.ViewGroup.addViewInner(ViewGroup.java:3740)
                                                                            at android.view.ViewGroup.addView(ViewGroup.java:3564)
                                                                            at android.view.ViewGroup.addView(ViewGroup.java:3540)
                                                                            at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.addTextureView(JCVideoPlayer.java:310)
                                                                            at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.goBackThisListener(JCVideoPlayer.java:509)
                                                                            at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.goToOtherListener(JCVideoPlayer.java:449)
                                                                            at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.backPress(JCVideoPlayer.java:572)
                                                                            at fm.jiecao.jiecaovideoplayer.ActiivtyMain.onBackPressed(ActiivtyMain.java:138)
                                                                            at android.app.Activity.onKeyUp(Activity.java:2234)
                                                                            at android.view.KeyEvent.dispatch(KeyEvent.java:2703)
                                                                            at android.app.Activity.dispatchKeyEvent(Activity.java:2471)
                                                                            at android.support.v7.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:533)
                                                                            at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:53)
                                                                            at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.dispatchKeyEvent(AppCompatDelegateImplBase.java:254)
                                                                            at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:2039)
                                                                            at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4325)
                                                                            at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4293)
                                                                            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3842)
                                                                            at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3892)
                                                                            at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3861)
                                                                            at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3968)
                                                                            at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3869)
                                                                            at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4025)
                                                                            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3842)
                                                                            at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3892)
                                                                            at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3861)
                                                                            at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3869)
                                                                            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3842)
                                                                            at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3892)
                                                                            at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3861)
                                                                            at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4001)
                                                                            at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4175)
                                                                            at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2074)
                                                                            at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1751)
                                                                            at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1742)
                                                                            at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2051)
                                                                            at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
                                                                            at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                            at android.os.MessageQueue.next(MessageQueue.java:138)
                                                                            at android.os.Looper.loop(Looper.java:150)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5310)
                                                                            at java.lang.reflect.Method.invokeNative(Native Method)
                                                                            at java.lang.reflect.Method.invoke(Method.java:515)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:832)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:648)
                                                                            at dalvik.system.NativeStart.main(Native Method)

**Comment by lipangit** [comment]
是不是退出全屏的时候布局容器有问题

**Comment by liuy9** [comment]
运行demo，直接播放，没有全屏

**Comment by lipangit** [comment]
0_0 demo！

**Comment by lipangit** [comment]
请用新版本
