### ISSUE TITLE
全屏的时候  第一个参数只能传AppCompatActivity类型吗？ 

### ISSUE THREAD

**Issue by KKJJ** [lipangit/JieCaoVideoPlayer#295]
你好，两个问题
1. 全屏的时候  第一个参数只能传AppCompatActivity类型吗？  我传的是FragmentActivity 报转换异常
2. RevycleView里边使用，直接报空指针，为什么？

**Comment by lipangit** [comment]
1.AppCompatActivity 继承 FragmentActivity，就是说你的activity总要继承一个activity那么就继承AppCompatActivity

2.Recycleview肯定是支持的，有朋友已经实现了，demo中之后会添加recycleview的例子

**Comment by KKJJ** [comment]
## 1 . 我的MainActivity集成FragmentActivity，可以播放  但是到结束或者点全屏 就报
FATAL EXCEPTION: main
                                                                       Process: yaofang.cn.thevipclub, PID: 30454
                                                                       java.lang.ClassCastException: com.theclub.MainActivity cannot be cast to android.support.v7.app.AppCompatActivity
                                                                           at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.hideSupportActionBar(JCVideoPlayer.java:805)
                                                                           at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.startWindowFullscreen(JCVideoPlayer.java:575)
                                                                           at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.onClick(JCVideoPlayer.java:197)
                                                                           at fm.jiecao.jcvideoplayer_lib.JCVideoPlayerStandard.onClick(JCVideoPlayerStandard.java:171)
                                                                           at android.view.View.performClick(View.java:4476)
                                                                           at android.view.View$PerformClick.run(View.java:18822)
                                                                           at android.os.Handler.handleCallback(Handler.java:808)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:103)
                                                                           at android.os.Looper.loop(Looper.java:193)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5551)
                                                                           at java.lang.reflect.Method.invokeNative(Native Method)
                                                                           at java.lang.reflect.Method.invoke(Method.java:515)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:914)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:730)
                                                                           at dalvik.system.NativeStart.main(Native Method)


## 2. 在RecycleView里面使用的，点击播放 就直接报空，是有什么要初始化么
FATAL EXCEPTION: main
                                                                     Process: com.theclub, PID: 1615
                                                                     java.lang.NullPointerException
                                                                         at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.prepareVideo(JCVideoPlayer.java:215)
                                                                         at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.onClick(JCVideoPlayer.java:173)
                                                                         at fm.jiecao.jcvideoplayer_lib.JCVideoPlayerStandard.onClick(JCVideoPlayerStandard.java:171)
                                                                         at android.view.View.performClick(View.java:4476)
                                                                         at android.view.View$PerformClick.run(View.java:18822)
                                                                         at android.os.Handler.handleCallback(Handler.java:808)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:103)
                                                                         at android.os.Looper.loop(Looper.java:193)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5551)
                                                                         at java.lang.reflect.Method.invokeNative(Native Method)
                                                                         at java.lang.reflect.Method.invoke(Method.java:515)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:914)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:730)
                                                                         at dalvik.system.NativeStart.main(Native Method)

**Comment by lipangit** [comment]
1. MainActivity 继承 AppCompatActivity ，引入 compile 'com.android.support:appcompat-v7:24.1.1'

2.哪个控件或变量是空？findviewbyid之后只需要setUp点击之后就能播放

**Comment by KKJJ** [comment]
1.  嗯，所以这就是我的第一个问题：全屏那里只能用AppCompatActivity
 2. 改成listView就没问题  RecycleView就报空，这个我再找找看把  不行 就用listView了  
感谢解答，辛苦辛苦
