### ISSUE TITLE
My app keeps crashing

### ISSUE THREAD

**Issue by RobbieArmz** [lipangit/JieCaoVideoPlayer#310]
After I added the library to my project my app doesn't even run. But when I remove it, it start just fine.

```
08-23 03:30:09.548 5945-5945/com.wezzlecorp.wezzle E/VdcInflateDelegate: Exception while inflating <vector>
                                                                         org.xmlpull.v1.XmlPullParserException: Binary XML file line #17<vector> tag requires viewportWidth > 0
                                                                             at android.support.graphics.drawable.VectorDrawableCompat.updateStateFromTypedArray(VectorDrawableCompat.java:535)
                                                                             at android.support.graphics.drawable.VectorDrawableCompat.inflate(VectorDrawableCompat.java:472)
                                                                             at android.support.graphics.drawable.VectorDrawableCompat.createFromXmlInner(VectorDrawableCompat.java:436)
                                                                             at android.support.v7.widget.AppCompatDrawableManager$VdcInflateDelegate.createFromXmlInner(AppCompatDrawableManager.java:708)
                                                                             at android.support.v7.widget.AppCompatDrawableManager.loadDrawableFromDelegates(AppCompatDrawableManager.java:348)
                                                                             at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:188)
                                                                             at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:181)
                                                                             at android.support.v7.widget.AppCompatDrawableManager.checkVectorDrawableSetup(AppCompatDrawableManager.java:689)
                                                                             at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:186)
                                                                             at android.support.v7.widget.TintTypedArray.getDrawableIfKnown(TintTypedArray.java:77)
                                                                             at android.support.v7.app.AppCompatDelegateImplBase.<init>(AppCompatDelegateImplBase.java:83)
                                                                             at android.support.v7.app.AppCompatDelegateImplV7.<init>(AppCompatDelegateImplV7.java:146)
                                                                             at android.support.v7.app.AppCompatDelegateImplV11.<init>(AppCompatDelegateImplV11.java:28)
                                                                             at android.support.v7.app.AppCompatDelegateImplV14.<init>(AppCompatDelegateImplV14.java:41)
                                                                             at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:193)
                                                                             at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:173)
                                                                             at android.support.v7.app.AppCompatActivity.getDelegate(AppCompatActivity.java:511)
                                                                             at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:71)
                                                                             at com.wezzlecorp.wezzle.MainActivity.onCreate(MainActivity.java:13)
                                                                             at android.app.Activity.performCreate(Activity.java:5117)
                                                                             at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080)
                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2144)
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230)
                                                                             at android.app.ActivityThread.access$600(ActivityThread.java:141)
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                             at android.os.Looper.loop(Looper.java:137)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5041)
                                                                             at java.lang.reflect.Method.invokeNative(Native Method)
                                                                             at java.lang.reflect.Method.invoke(Method.java:511)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:561)
                                                                             at dalvik.system.NativeStart.main(Native Method)
08-23 03:30:09.548 5945-5945/com.wezzlecorp.wezzle D/AndroidRuntime: Shutting down VM
08-23 03:30:09.548 5945-5945/com.wezzlecorp.wezzle W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x41fa6930)
08-23 03:30:09.558 5945-5945/com.wezzlecorp.wezzle E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     java.lang.RuntimeException: Unable to start activity ComponentInfo{com.wezzlecorp.wezzle/com.wezzlecorp.wezzle.MainActivity}: android.content.res.Resources$NotFoundException: File res/drawable/abc_ic_ab_back_material.xml from drawable resource ID #0x7f020013
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2180)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230)
                                                                         at android.app.ActivityThread.access$600(ActivityThread.java:141)
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                         at android.os.Looper.loop(Looper.java:137)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5041)
                                                                         at java.lang.reflect.Method.invokeNative(Native Method)
                                                                         at java.lang.reflect.Method.invoke(Method.java:511)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:561)
                                                                         at dalvik.system.NativeStart.main(Native Method)
                                                                      Caused by: android.content.res.Resources$NotFoundException: File res/drawable/abc_ic_ab_back_material.xml from drawable resource ID #0x7f020013
                                                                         at android.content.res.Resources.loadDrawable(Resources.java:1953)
                                                                         at android.content.res.Resources.getDrawable(Resources.java:660)
                                                                         at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:354)
                                                                         at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:193)
                                                                         at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:181)
                                                                         at android.support.v7.widget.AppCompatDrawableManager.checkVectorDrawableSetup(AppCompatDrawableManager.java:689)
                                                                         at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:186)
                                                                         at android.support.v7.widget.TintTypedArray.getDrawableIfKnown(TintTypedArray.java:77)
                                                                         at android.support.v7.app.AppCompatDelegateImplBase.<init>(AppCompatDelegateImplBase.java:83)
                                                                         at android.support.v7.app.AppCompatDelegateImplV7.<init>(AppCompatDelegateImplV7.java:146)
                                                                         at android.support.v7.app.AppCompatDelegateImplV11.<init>(AppCompatDelegateImplV11.java:28)
                                                                         at android.support.v7.app.AppCompatDelegateImplV14.<init>(AppCompatDelegateImplV14.java:41)
                                                                         at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:193)
                                                                         at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:173)
                                                                         at android.support.v7.app.AppCompatActivity.getDelegate(AppCompatActivity.java:511)
                                                                         at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:71)
                                                                         at com.wezzlecorp.wezzle.MainActivity.onCreate(MainActivity.java:13)
                                                                         at android.app.Activity.performCreate(Activity.java:5117)
                                                                         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080)
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2144)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230) 
                                                                         at android.app.ActivityThread.access$600(ActivityThread.java:141) 
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234) 
                                                                         at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                         at android.os.Looper.loop(Looper.java:137) 
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5041) 
                                                                         at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                         at java.lang.reflect.Method.invoke(Method.java:511) 
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794) 
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:561) 
                                                                         at dalvik.system.NativeStart.main(Native Method) 
                                                                      Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #17: invalid drawable tag vector
                                                                         at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:881)
                                                                         at android.graphics.drawable.Drawable.createFromXml(Drawable.java:822)
                                                                         at android.content.res.Resources.loadDrawable(Resources.java:1950)
                                                                         at android.content.res.Resources.getDrawable(Resources.java:660) 
                                                                         at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:354) 
                                                                         at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:193) 
                                                                         at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:181) 
                                                                         at android.support.v7.widget.AppCompatDrawableManager.checkVectorDrawableSetup(AppCompatDrawableManager.java:689) 
                                                                         at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:186) 
                                                                         at android.support.v7.widget.TintTypedArray.getDrawableIfKnown(TintTypedArray.java:77) 
                                                                         at android.support.v7.app.AppCompatDelegateImplBase.<init>(AppCompatDelegateImplBase.java:83) 
                                                                         at android.support.v7.app.AppCompatDelegateImplV7.<init>(AppCompatDelegateImplV7.java:146) 
                                                                         at android.support.v7.app.AppCompatDelegateImplV11.<init>(AppCompatDelegateImplV11.java:28) 
                                                                         at android.support.v7.app.AppCompatDelegateImplV14.<init>(AppCompatDelegateImplV14.java:41) 
                                                                         at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:193) 
                                                                         at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:173) 
                                                                         at android.support.v7.app.AppCompatActivity.getDelegate(AppCompatActivity.java:511) 
                                                                         at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:71) 
                                                                         at com.wezzlecorp.wezzle.MainActivity.onCreate(MainActivity.java:13) 
                                                                         at android.app.Activity.performCreate(Activity.java:5117) 
                                                                         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080) 
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2144) 
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230) 
                                                                         at android.app.ActivityThread.access$600(ActivityThread.java:141) 
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234) 
                                                                         at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                         at android.os.Looper.loop(Looper.java:137) 
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5041) 
                                                                         at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                         at java.lang.reflect.Method.invoke(Method.java:511) 
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794) 
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:561) 
                                                                         at dalvik.system.NativeStart.main(Native Method)
```

**Comment by lipangit** [comment]
It possible caused by  support-v7, check build.gradle config
