### ISSUE TITLE
测试简单版本与so包冲突

### ISSUE THREAD

**Issue by NicolasKun** [lipangit/JieCaoVideoPlayer#319]
~ 新建demo没有别的东西
~ comlipe引入jiecaovideoplayer
~ 添加高德3D地图so包armeabi系列正常播放
~ 添加arm64-v8a系列爆出以下错误(含有libgdinamapv4sdk752.so&libgdinamapv4sdk752ex.so)
AndroidRuntime: FATAL EXCEPTION: main
                                                                        Process: me.nicolas.jcvideodemo, PID: 18730
                                                                        java.lang.UnsatisfiedLinkError: com.android.tools.fd.runtime.IncrementalClassLoader$DelegateClassLoader[DexPathList[[dex file "/data/data/me.nicolas.jcvideodemo/files/instant-run/dex/slice-tv.danmaku.ijk.media-ijkplayer-java-0.6.0_e0e725c706085f75edf4d9d3dd70807ad98b82a9-classes.dex", dex file "/data/data/me.nicolas.jcvideodemo/files/instant-run/dex/slice-tv.danmaku.ijk.media-ijkplayer-armv7a-0.6.0_67c5afb8d63fe53c28bda5cecdd12dfbfb731926-classes.dex", dex file "/data/data/me.nicolas.jcvideodemo/files/instant-run/dex/slice-support-annotations-24.1.1_a6c1007fb3ab2e479ba14f110e995a9d41487d53-classes.dex", dex file "/data/data/me.nicolas.jcvideodemo/files/instant-run/dex/slice-slice_9-classes.dex", dex file "/data/data/me.nicolas.jcvideodemo/files/instant-run/dex/slice-slice_8-classes.dex", dex file "/data/data/me.nicolas.jcvideodemo/files/instant-run/dex/slice-slice_7-classes.dex", dex file "/data/data/me.nicolas.jcvideodemo/files/instant-run/dex/slice-slice_6-classes.dex", dex file "/data/data/me.nicolas.jcvideodemo/files/instant-run/dex/slice-slice_5-classes.dex", dex file "/data/data/me.nicolas.jcvideodemo/files/instant-run/dex/slice-slice_4-classes.dex", dex file "/data/data/me.nicolas.jcvideodemo/files/instant-run/dex/slice-slice_3-classes.dex", dex file "/data/data/me.nicolas.jcvideodemo/files/instant-run/dex/slice-slice_2-classes.dex", dex file "/data/data/me.nicolas.jcvideodemo/files/instant-run/dex/slice-slice_1-classes.dex", dex file "/data/data/me.nicolas.jcvideodemo/files/instant-run/dex/slice-slice_0-classes.dex", dex file "/data/data/me.nicolas.jcvideodemo/files/instant-run/dex/slice-internal_impl-24.1.1_902d727d4e05054ff6600d35fb6729410f898efc-classes.dex", dex file "/data/data/me.nicolas.jcvideodemo/files/instant-run/dex/slice-fm.jiecao-jiecaovideoplayer-4.6.2_8144b73355bf85e19e39ff849d971851f0954ec8-classes.dex", dex file "/data/data/me.nicolas.jcvideodemo/files/instant-run/dex/slice-com.android.support-support-vector-drawable-24.1.1_9ba2272a902189113b2f340c68da0c27d3f240be-classes.dex", dex file "/data/data/me.nicolas.jcvideodemo/files/instant-run/dex/slice-com.android.support-support-v4-24.1.1_8383c233ae130406c6617687b3a2fa864a9838a2-classes.dex", dex file "/data/data/me.nicolas.jcvideodemo/files/instant-run/dex/slice-com.android.support-appcompat-v7-24.1.1_81852a6cb26b66b329c5c5affbae872243b66b92-classes.dex", dex file "/data/data/me.nicolas.jcvideodemo/files/instant-run/dex/slice-com.android.support-animated-vector-drawable-24.1.1_a8ff47145af44a3d50800151ab93ac42d681854c-classes.dex"],nativeLibraryDirectories=[/data/app/me.nicolas.jcvideodemo-1/lib/arm64, /vendor/lib64, /system/lib64, /vendor/lib64, /system/lib64]]] couldn't find "libijkffmpeg.so"
                                                                            at java.lang.Runtime.loadLibrary(Runtime.java:366)
                                                                            at java.lang.System.loadLibrary(System.java:988)
                                                                            at tv.danmaku.ijk.media.player.IjkMediaPlayer$1.loadLibrary(IjkMediaPlayer.java:157)
                                                                            at tv.danmaku.ijk.media.player.IjkMediaPlayer.loadLibrariesOnce(IjkMediaPlayer.java:168)
                                                                            at tv.danmaku.ijk.media.player.IjkMediaPlayer.initPlayer(IjkMediaPlayer.java:209)
                                                                            at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(IjkMediaPlayer.java:205)
                                                                            at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(IjkMediaPlayer.java:196)
                                                                            at fm.jiecao.jcvideoplayer_lib.JCMediaManager.<init>(JCMediaManager.java:55)
                                                                            at fm.jiecao.jcvideoplayer_lib.JCMediaManager.instance(JCMediaManager.java:49)
                                                                            at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.prepareVideo(JCVideoPlayer.java:212)
                                                                            at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.onClick(JCVideoPlayer.java:169)
                                                                            at fm.jiecao.jcvideoplayer_lib.JCVideoPlayerStandard.onClick(JCVideoPlayerStandard.java:171)
                                                                            at android.view.View.performClick(View.java:4908)
                                                                            at android.view.View$PerformClick.run(View.java:20382)
                                                                            at android.os.Handler.handleCallback(Handler.java:815)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                            at android.os.Looper.loop(Looper.java:194)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5692)
                                                                        	at java.lang.reflec

**Comment by MycroftWong** [comment]
一样，遇到这个问题
```
couldn't find "libijkffmpeg.so"
```

**Comment by lipangit** [comment]
http://blog.csdn.net/sinat_31598337/article/details/51418608

试一下他的建议

**Comment by NicolasKun** [comment]
多谢
