### ISSUE TITLE
主界面的的设置全屏按钮点击出现bug

### ISSUE THREAD

**Issue by Dreamer206602** [lipangit/jiecaovideoplayer#33]
03-18 16:27:32.388 13621-13621/fm.jiecao.jiecaovideoplayer D/AndroidRuntime: Shutting down VM
03-18 16:27:32.388 13621-13621/fm.jiecao.jiecaovideoplayer W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x41673ba8)
03-18 16:27:32.393 13621-13621/fm.jiecao.jiecaovideoplayer E/AndroidRuntime: FATAL EXCEPTION: main
                                                                             Process: fm.jiecao.jiecaovideoplayer, PID: 13621
                                                                             java.lang.RuntimeException: Unable to start activity ComponentInfo{fm.jiecao.jiecaovideoplayer/fm.jiecao.jcvideoplayer_lib.JCFullScreenActivity}: java.lang.NullPointerException
                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2215)
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2264)
                                                                                 at android.app.ActivityThread.access$800(ActivityThread.java:136)
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1219)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                 at android.os.Looper.loop(Looper.java:136)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5032)
                                                                                 at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                 at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                                                 at dalvik.system.NativeStart.main(Native Method)
                                                                              Caused by: java.lang.NullPointerException
                                                                                 at fm.jiecao.jcvideoplayer_lib.JCMediaManager.prepareToPlay(JCMediaManager.java:43)
                                                                                 at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.onClick(JCVideoPlayer.java:362)
                                                                                 at android.view.View.performClick(View.java:4439)
                                                                                 at fm.jiecao.jcvideoplayer_lib.JCFullScreenActivity.onCreate(JCFullScreenActivity.java:83)
                                                                                 at android.app.Activity.performCreate(Activity.java:5310)
                                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094)
                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2179)
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2264) 
                                                                                 at android.app.ActivityThread.access$800(ActivityThread.java:136) 
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1219) 
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                 at android.os.Looper.loop(Looper.java:136) 
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5032) 
                                                                                 at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                 at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785) 
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601) 
                                                                                 at dalvik.system.NativeStart.main(Native Method)

**Comment by lipangit** [comment]
fixed
