### ISSUE TITLE
点击换皮肤的按钮跳转到详情界面，点击播放出现bug

### ISSUE THREAD

**Issue by Dreamer206602** [lipangit/jiecaovideoplayer#34]
03-18 16:30:24.803 16380-16380/fm.jiecao.jiecaovideoplayer E/AndroidRuntime: FATAL EXCEPTION: main
                                                                             Process: fm.jiecao.jiecaovideoplayer, PID: 16380
                                                                             java.lang.NullPointerException
                                                                                 at fm.jiecao.jcvideoplayer_lib.JCMediaManager.prepareToPlay(JCMediaManager.java:43)
                                                                                 at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.onClick(JCVideoPlayer.java:362)
                                                                                 at android.view.View.performClick(View.java:4439)
                                                                                 at android.view.View$PerformClick.run(View.java:18623)
                                                                                 at android.os.Handler.handleCallback(Handler.java:733)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                 at android.os.Looper.loop(Looper.java:136)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5032)
                                                                                 at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                 at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                                                 at dalvik.system.NativeStart.main(Native Method)

**Comment by lipangit** [comment]
same as #33 fixed
