### ISSUE TITLE
 java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getVisibility()' on a null object reference

### ISSUE THREAD

**Issue by lipangit** [lipangit/JieCaoVideoPlayer#387]
09-17 20:39:25.584 20389-20389/fm.jiecao.jiecaovideoplayer E/AndroidRuntime: FATAL EXCEPTION: main
                                                                             Process: fm.jiecao.jiecaovideoplayer, PID: 20389
                                                                             java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getVisibility()' on a null object reference
                                                                                 at android.widget.FrameLayout.layoutChildren(FrameLayout.java:531)
                                                                                 at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                                                 at android.view.View.layout(View.java:15691)
                                                                                 at android.view.ViewGroup.layout(ViewGroup.java:5039)
                                                                                 at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2116)
                                                                                 at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1873)
                                                                                 at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1091)
                                                                                 at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5926)
                                                                                 at android.view.Choreographer$CallbackRecord.run(Choreographer.java:775)
                                                                                 at android.view.Choreographer.doCallbacks(Choreographer.java:588)
                                                                                 at android.view.Choreographer.doFrame(Choreographer.java:558)
                                                                                 at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:761)
                                                                                 at android.os.Handler.handleCallback(Handler.java:739)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                 at android.os.Looper.loop(Looper.java:135)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5276)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)

**Comment by shixiangyu** [comment]
碰到过，切屏的时候触发了JCVideoPlayer.releaseAllVideos();

**Comment by shixiangyu** [comment]
这个问题还和TOOL_BAR_EXIST有关，设置成false也不会触发这个问题，但不是好的解决办法，不知道为什么会和TOOL_BAR_EXIST有关系

**Comment by flztsj** [comment]
我这边在 About Ui > ImageLoader > 最后一个视频 点击全屏按钮的时候会Crash，报的就是这个错误。

**Comment by flztsj** [comment]
原因是layout的过程中导致onscroll被调用，导致player的backpress函数被调用，导致一开始的getChildCount＝4，在layout的过程中变成3，然后在for循环中i＝＝3的过程时，拿到的是null。

![jiechao_studio_debug](https://cloud.githubusercontent.com/assets/5946178/18617188/733eb82e-7dfc-11e6-80b0-bbccaadb01b5.jpg)

![jiechao_studio_debug1](https://cloud.githubusercontent.com/assets/5946178/18617191/8d637032-7dfc-11e6-9bd4-8af9416d6590.jpg)

**Comment by yayaxiong** [comment]
我也出现了这个问题，目前已经解决了，记录下，或许以后有人遇到和我一样，需求是这样的：
    要做和 QQ空间 、微博视频列表 一样的 自动播放，播放完了就放下一个 ，这里我采取了网上第三方包，
对列表（RecycleView） 进行滑动监听，滑动到某一个条件会触发我的自定义方法 method1 (表示播放下一个新视频 )  和 method2 (表示停止旧的视频 )，这里是先执行   method2，然后 method1 。当 RecycleView在顶部的时候，点击全屏旋转方向，不会出现这个问题，滑动到第二个自动播放，全屏，当是竖屏的时候正常播放，当我旋转为横屏的时候出现这个问题，后面的都一样。

  分析：有可能是某个View  出现了问题，导致上诉问题，也认真看了源码，没有发现哪里有问题。 RecycleView滑动监听也没有问题，只要不是全屏旋转到横屏都没事，切换到横屏就出问题，经过一段时间验证得出问题原因，问题就是出现在我的滑动监听以及会触发的 method1  和  method2  上面，全屏竖屏的时候， RecycleView  也是竖屏，这个时候没有问题；当旋转到横屏，RecycleView 同样会旋转为横屏，这个时候会触发RecycleView的滑动监听（宽高不一致），也就会触发 method2 和 method1；在  method2  中结束播放就会触发  MediaPlayer 的结束 ，会执行（textureViewContainer.removeView(JCMediaManager.textureView);），而MediaPlayer 是全局唯一性的，全屏中的  MediaPlayer  也会停止，横屏的时候也就出现这个问题了

  解决方法：滑动监听中加判断，判断是竖屏才触发我的  method1  和 method2，现在就不出现这个问题了

**Comment by lipangit** [comment]
@yayaxiong 对总之出现getVisibilty的问题就断点releaseVideo，看哪里不应该release视频却release了，感谢你的反馈
