### ISSUE TITLE
Mediaplayer在Preparing状态时，执行stop()，ANR了

### ISSUE THREAD

**Issue by wl0073921** [lipangit/JieCaoVideoPlayer#391]
Mediaplayer在Preparing状态时，执行stop()，ANR了。

在Android4.4.4中偶现这个问题：
  at android.media.MediaPlayer._stop(Native Method)
  at android.media.MediaPlayer.stop(MediaPlayer.java:1086)

请教一下，有解没？

**Comment by lipangit** [comment]
用最新版本，这些已经放到线程中了
