### ISSUE TITLE
java.lang.IllegalStateException: mpjni: pause: null mp

### ISSUE THREAD

**Issue by wman0211** [lipangit/JieCaoVideoPlayer#434]
Android: 5.1.1
Manufacturer: HUAWEI
Model: KIW-AL10
CrashReporter Key: 79A4DC6F-0C5F-A3BD-5F06-FB35FB7C8B0A8AD5ADAD
Date: Fri Oct 14 22:39:03 GMT+08:00 2016
java.lang.IllegalStateException: mpjni: pause: null mp
at tv.danmaku.ijk.media.player.IjkMediaPlayer._pause(Native Method)
at tv.danmaku.ijk.media.player.IjkMediaPlayer.pause(IjkMediaPlayer.java:505)
at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.onClick(JCVideoPlayer.java:223)
at fm.jiecao.jcvideoplayer_lib.JCVideoPlayerStandard.onClick(JCVideoPlayerStandard.java:156)
at android.view.View.performClick(View.java:4837)
at android.view.View$PerformClick.run(View.java:20020)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5669)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
at ### com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

是用户使用出现的错误, 不能重现操作步骤,
只在 KIW-AL10 机型上出现 Crash了一百多次
请看看原因 谢谢

**Comment by lipangit** [comment]
看样子像用户点击了暂停，崩溃了，但是这时候视频肯定是在播放的，MediaPlayer怎么会是null

**Comment by scar1et** [comment]
@lipangit 我遇到过这种情况，是视频在一开始loading的时候，你暂停或者全屏都会有很大几率崩溃，我现在是判断在loading的时候不让用户进行这样的操作

**Comment by jimmeyshi** [comment]
这个是暂停视频后，去播放手机音乐，然后切换回来继续播放，就报这个错了

**Comment by lipangit** [comment]
试试新版
