### ISSUE TITLE
编译通过，在运行时报错java.lang.NoClassDefFoundError: fm.jiecao.jcvideoplayer_lib.JCMediaManager

### ISSUE THREAD

**Issue by hc05161** [lipangit/JieCaoVideoPlayer#447]
java.lang.NoClassDefFoundError: fm.jiecao.jcvideoplayer_lib.JCMediaManager
     at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.setUp(JCVideoPlayer.java:157)
     at fm.jiecao.jcvideoplayer_lib.JCVideoPlayerStandard.setUp(JCVideoPlayerStandard.java:82)
     at com.example.hc.mytest.MainActivity.onCreate(MainActivity.java:51)
     at android.app.Activity.performCreate(Activity.java:5245)
     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2153)
     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2238)
     at android.app.ActivityThread.access$800(ActivityThread.java:138)
     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1201)
     at android.os.Handler.dispatchMessage(Handler.java:102)
     at android.os.Looper.loop(Looper.java:136)
     at android.app.ActivityThread.main(ActivityThread.java:5016)
     at java.lang.reflect.Method.invokeNative(Native Method)
     at java.lang.reflect.Method.invoke(Method.java:515)
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:611)
     at dalvik.system.NativeStart.main(Native Method)

**Comment by lipangit** [comment]
JCMediaManager这个类找不见应该是引入类库有问题

**Comment by hc05161** [comment]
我是直接下载的jar包和aar包引入的，两个包里的都有相同的JCMediaManager，是否是引用重了。

**Comment by hc05161** [comment]
java.lang.ClassNotFoundException: Didn't find class "fm.jiecao.jcvideoplayer_lib.JCMediaManager" on path: DexPathList[[zip file "/data/app/com.example1.hc.myapplication-1/base.apk"],nativeLibraryDirectories=[/data/app/com.example1.hc.myapplication-1/lib/arm64, /vendor/lib64, /system/lib64]]

**Comment by lipangit** [comment]
引入aar就不用jar了，aar包含代码和资源文件

**Comment by hc05161** [comment]
aar包我是这样引入的：
 compile(name: 'jiecaovideoplayer-4.8.1', ext: 'aar')
然后加上这句话：
repositories {flatDir {dirs 'libs'}}
但还是找不到JCMediaManager类，是怎么回事？

**Comment by lipangit** [comment]
@hc05161 这是用的gradle吧，为什么不 compile 'fm.jiecao:jiecaovideoplayer:4.8.1'

**Comment by hc05161** [comment]
@lipangit 恩，是用的gradle，但是直接compile 'fm.jiecao:jiecaovideoplayer:4.8.1'构建不起，所以才下载的aar包

![falskdjflaskjdf](https://cloud.githubusercontent.com/assets/8087385/19718891/027e661e-9b9a-11e6-986e-f3b9892d1105.png)

**Comment by lipangit** [comment]
compile 'fm.jiecao:jiecaovideoplayer:4.8.1' 再试试，新建个项目试试

**Comment by hc05161** [comment]
这个跟网络环境有关系，可能是我这个网不好，导致compile 'fm.jiecao:jiecaovideoplayer:4.8.1'构建不起，换了一个网络就可以，我这里的网络就不可以，谢谢@lipangit 的认真解答
