### ISSUE TITLE
A bug in list

### ISSUE THREAD

**Issue by lipangit** [lipangit/jiecaovideoplayer#45]
java.lang.IllegalArgumentException: The surface has been released
                                                                     at android.media.MediaPlayer._setVideoSurface(Native Method)
                                                                     at android.media.MediaPlayer.setDisplay(MediaPlayer.java:715)
                                                                     at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.onEventMainThread(JCVideoPlayer.java:298)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at java.lang.reflect.Method.invoke(Method.java:372)
                                                                     at de.greenrobot.event.EventBus.invokeSubscriber(EventBus.java:498)
                                                                     at de.greenrobot.event.EventBus.postToSubscription(EventBus.java:433)
                                                                     at de.greenrobot.event.EventBus.postSingleEventForEventType(EventBus.java:410)
                                                                     at de.greenrobot.event.EventBus.postSingleEvent(EventBus.java:383)
                                                                     at de.greenrobot.event.EventBus.post(EventBus.java:263)
                                                                     at fm.jiecao.jcvideoplayer_lib.JCMediaManager.onPrepared(JCMediaManager.java:61)
                                                                     at android.media.MediaPlayer$EventHandler.handleMessage(MediaPlayer.java:2539)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                     at android.os.Looper.loop(Looper.java:135)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5273)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at java.lang.reflect.Method.invoke(Method.java:372)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)

**Comment by lipangit** [comment]
Create surfaceview should after click start,Not add view

**Comment by lipangit** [comment]
done
