### ISSUE TITLE
全屏会空指针

### ISSUE THREAD

**Issue by sooglejay** [lipangit/JieCaoVideoPlayer#458]
E/AndroidRuntime: FATAL EXCEPTION: main
                                                               Process: com.qq.wx.img, PID: 32472
                                                               java.lang.NullPointerException
                                                                   at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.hideSupportActionBar(JCVideoPlayer.java:917)
                                                                   at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.startWindowFullscreen(JCVideoPlayer.java:648)
                                                                   at fm.jiecao.jcvideoplayer_lib.JCVideoPlayerStandard.startWindowFullscreen(JCVideoPlayerStandard.java:326)
                                                                   at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.onClick(JCVideoPlayer.java:225)
                                                                   at fm.jiecao.jcvideoplayer_lib.JCVideoPlayerStandard.onClick(JCVideoPlayerStandard.java:186)
                                                                   at android.view.View.performClick(View.java:4444)
                                                                   at android.view.View$PerformClick.run(View.java:18457)
                                                                   at android.os.Handler.handleCallback(Handler.java:733)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                   at android.os.Looper.loop(Looper.java:136)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:5113)
                                                                   at java.lang.reflect.Method.invokeNative(Native Method)
                                                                   at java.lang.reflect.Method.invoke(Method.java:515)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612)
                                                                   at dalvik.system.NativeStart.main(Native Method)

**Comment by lipangit** [comment]
这是哪个版本，917行代码是什么，你断点一下看看是activity是null还是actionbar是null

**Comment by ttdevs** [comment]
`public static AppCompatActivity getAppCompActivity(Context context) {
        if (context == null) return null;
        if (context instanceof AppCompatActivity) {
            return (AppCompatActivity) context;
        } else if (context instanceof ContextThemeWrapper) {
            return getAppCompActivity(((ContextThemeWrapper) context).getBaseContext());
        }
        return null;
    }
`
这个方法返回值可能为null， 所以执行：
`ActionBar ab = JCUtils.getAppCompActivity(context).getSupportActionBar();`
就会报空指针。

**Comment by lipangit** [comment]
activity 继承 AppcompatActivity

**Comment by ttdevs** [comment]
@lipangit 想做成一个没有actionbar的界面，不能继承AppcompatActivity

**Comment by lipangit** [comment]
可以把actionbar隐藏

**Comment by qq972600081** [comment]
对，我也遇到这个问题了，而且我做的是sdk，不能要求用户一定得用AppCompatActivity，这个问题能不能解决一下？

**Comment by qq972600081** [comment]
急……直接就闪退了，可是这个不是做了判断吗？多加一个兼容吧，不然只好换框架了，可惜了啊
而且这个问题肯定很容易碰到，建议为了做一个优秀的框架，最好能够考虑兼容到方方面面的情况呢！
最后，谢谢无私奉献的开源精神！框架很棒，请加上兼容！

**Comment by lipangit** [comment]
好的，已经加到工作计划，但还没有具体的时间表
