### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lfm/jiecao/jcvideoplayer_lib/JCMediaManager;

### ISSUE THREAD

**Issue by 471448446** [lipangit/JieCaoVideoPlayer#465]
如果直接使用aar会报错：
 java.lang.NoClassDefFoundError: Failed resolution of: Lfm/jiecao/jcvideoplayer_lib/JCMediaManager;
                                                                  at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.setUp(JCVideoPlayer.java:157)
                                                                  at fm.jiecao.jcvideoplayer_lib.JCVideoPlayerStandard.setUp(JCVideoPlayerStandard.java:82)
                                                                  at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.startFullscreen(JCVideoPlayer.java:902)

但是用maven库导入的方式就不会。维护者看看问题呢？

**Comment by lipangit** [comment]
你的项目是gradle创建的吗，这个就很方便，我已经2年多没用过eclipse开发了，这个应该就是常规的aar引入，然后再引入ijkplayer，你再上网上查查吧，引入成功后开发要是有什么问题再来找我
