### ISSUE TITLE
Errors in judgment and callback

### ISSUE THREAD

**Issue by lipangit** [lipangit/JieCaoVideoPlayer#48]

**Comment by lipangit** [comment]
04-01 10:22:16.584 12686-13113/com.jiecao.news.jiecaonews W/MediaPlayer: info/warning (3, 0)
04-01 10:22:18.904 12686-12686/com.jiecao.news.jiecaonews D/MediaPlayer: Couldn't open file on client side, trying server side
04-01 10:22:18.904 12686-12686/com.jiecao.news.jiecaonews W/System.err: java.io.IOException: setDataSource failed.
04-01 10:22:18.904 12686-12686/com.jiecao.news.jiecaonews W/System.err:     at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1086)
04-01 10:22:18.904 12686-12686/com.jiecao.news.jiecaonews W/System.err:     at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1060)
04-01 10:22:18.904 12686-12686/com.jiecao.news.jiecaonews W/System.err:     at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1014)
04-01 10:22:18.904 12686-12686/com.jiecao.news.jiecaonews W/System.err:     at android.media.MediaPlayer.setDataSource(MediaPlayer.java:957)
04-01 10:22:18.904 12686-12686/com.jiecao.news.jiecaonews W/System.err:     at fm.jiecao.jcvideoplayer_lib.JCMediaManager.prepareToPlay(JCMediaManager.java:46)
04-01 10:22:18.904 12686-12686/com.jiecao.news.jiecaonews W/System.err:     at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.onClick(JCVideoPlayer.java:364)
04-01 10:22:18.904 12686-12686/com.jiecao.news.jiecaonews W/System.err:     at android.view.View.performClick(View.java:4785)
04-01 10:22:18.904 12686-12686/com.jiecao.news.jiecaonews W/System.err:     at android.view.View$PerformClick.run(View.java:19888)
04-01 10:22:18.904 12686-12686/com.jiecao.news.jiecaonews W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
04-01 10:22:18.904 12686-12686/com.jiecao.news.jiecaonews W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
04-01 10:22:18.904 12686-12686/com.jiecao.news.jiecaonews W/System.err:     at android.os.Looper.loop(Looper.java:135)
04-01 10:22:18.904 12686-12686/com.jiecao.news.jiecaonews W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5273)
04-01 10:22:18.904 12686-12686/com.jiecao.news.jiecaonews W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
04-01 10:22:18.904 12686-12686/com.jiecao.news.jiecaonews W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
04-01 10:22:18.904 12686-12686/com.jiecao.news.jiecaonews W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
04-01 10:22:18.904 12686-12686/com.jiecao.news.jiecaonews W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
04-01 10:22:18.904 12686-12686/com.jiecao.news.jiecaonews I/JCVideoPlayer: play video
04-01 10:22:18.914 12686-13042/com.jiecao.news.jiecaonews D/MobclickAgent: Report policy : d
