### ISSUE TITLE
暂停视频，切换手机音乐播放，再切换回APP继续播放视频，闪退

### ISSUE THREAD

**Issue by jimmeyshi** [lipangit/JieCaoVideoPlayer#484]
APP先播放视频，然后暂停视频，切换到手机音乐播放音乐，然后再切换回APP继续播放视频，就会出现此闪退问题

onResume 调用方法
if(视频之前已经初始化成功){
     JCMediaManager.instance().mediaPlayer.start();
     JCMediaManager.instance().mediaPlayer.seekTo((int) basicTime + (int)addTime);
}

11-14 10:11:10.797 27034-27034/com.klgz.app.haoyigong E/AndroidRuntime: FATAL EXCEPTION: main
                                                                        Process: com.klgz.app.haoyigong, PID: 27034
                                                                        java.lang.RuntimeException: Unable to resume activity {com.klgz.app.haoyigong/com.klgz.app.classroomlib.ui.activity.LiveClassRoomActivity}: java.lang.IllegalStateException: mpjni: start: null mp
                                                                            at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2954)
                                                                            at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2985)
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1327)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                            at android.os.Looper.loop(Looper.java:135)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5235)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at java.lang.reflect.Method.invoke(Method.java:372)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:906)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:701)
                                                                         Caused by: java.lang.IllegalStateException: mpjni: start: null mp
                                                                            at tv.danmaku.ijk.media.player.IjkMediaPlayer._start(Native Method)
                                                                            at tv.danmaku.ijk.media.player.IjkMediaPlayer.start(IjkMediaPlayer.java:489)
                                                                            at com.klgz.app.classroomlib.ui.activity.LiveClassRoomActivity.startPlayAfter(LiveClassRoomActivity.java:314)
                                                                            at com.klgz.app.classroomlib.ui.activity.LiveClassRoomActivity.startPlay(LiveClassRoomActivity.java:303)
                                                                            at com.klgz.app.classroomlib.ui.activity.LiveClassRoomActivity.onResume(LiveClassRoomActivity.java:492)
                                                                            at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1241)
                                                                            at android.app.Activity.performResume(Activity.java:6027)
                                                                            at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2943)
                                                                            at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2985)?
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1327)?
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102)?
                                                                            at android.os.Looper.loop(Looper.java:135)?
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5235)?
                                                                            at java.lang.reflect.Method.invoke(Native Method)?
                                                                            at java.lang.reflect.Method.invoke(Method.java:372)?
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:906)?
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:701)?

**Comment by lipangit** [comment]
在activity的onPause中调用releaseAllVideos()函数了吗
再切回界面继续播放的时候会重新初始化播放器，重新播放
