### ISSUE TITLE
播放器嵌套在NestedScrollView中，然后使用小窗口功能出现崩溃

### ISSUE THREAD

**Issue by scar1et** [lipangit/JieCaoVideoPlayer#490]
**逻辑**：
当ScrollVIew滑到看不到播放器的时候，显示小窗口，滑回来的时候隐藏小窗口

**BUG**：
经过几次上述操作，应用崩溃

**日志**：
E/Surface: dequeueBuffer failed (No such device)
E/IJKMEDIA: SDL_Android_NativeWindow_display_l: ANativeWindow_lock: failed -19
E/AndroidRuntime: FATAL EXCEPTION: main
                                                                       Process: com.meetstudio.yinyueba, PID: 7598
                                                                       java.lang.NullPointerException
                                                                           at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3134)
                                                                           at android.view.View.draw(View.java:15307)
                                                                           at android.widget.FrameLayout.draw(FrameLayout.java:472)
                                                                           at android.view.View.getDisplayList(View.java:14198)
                                                                           at android.view.View.getDisplayList(View.java:14240)
                                                                           at android.view.View.draw(View.java:15018)
                                                                           at android.view.ViewGroup.drawChild(ViewGroup.java:3298)
                                                                           at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3135)
                                                                           at android.view.View.getDisplayList(View.java:14193)
                                                                           at android.view.View.getDisplayList(View.java:14240)
                                                                           at android.view.View.draw(View.java:15018)
                                                                           at android.view.ViewGroup.drawChild(ViewGroup.java:3298)
                                                                           at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3135)
                                                                           at android.view.View.getDisplayList(View.java:14193)
                                                                           at android.view.View.getDisplayList(View.java:14240)
                                                                           at android.view.View.draw(View.java:15018)
                                                                           at android.view.ViewGroup.drawChild(ViewGroup.java:3298)
                                                                           at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3135)
                                                                           at android.view.View.getDisplayList(View.java:14193)
                                                                           at android.view.View.getDisplayList(View.java:14240)
                                                                           at android.view.View.draw(View.java:15018)
                                                                           at android.view.ViewGroup.drawChild(ViewGroup.java:3298)
                                                                           at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3135)
                                                                           at android.view.View.draw(View.java:15307)
                                                                           at android.widget.FrameLayout.draw(FrameLayout.java:472)
                                                                           at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2568)
                                                                           at android.view.View.getDisplayList(View.java:14198)
                                                                           at android.view.View.getDisplayList(View.java:14240)
                                                                           at android.view.HardwareRenderer$GlRenderer.buildDisplayList(HardwareRenderer.java:1570)
                                                                           at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1449)
                                                                           at android.view.ViewRootImpl.draw(ViewRootImpl.java:2709)
                                                                           at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2575)
                                                                           at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2147)
                                                                           at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1238)
                                                                           at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6473)
                                                                           at android.view.Choreographer$CallbackRecord.run(Choreographer.java:803)
                                                                           at android.view.Choreographer.doCallbacks(Choreographer.java:603)
                                                                           at android.view.Choreographer.doFrame(Choreographer.java:573)
                                                                           at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:789)
                                                                           at android.os.Handler.handleCallback(Handler.java:733)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                           at android.os.Looper.loop(Looper.java:157)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5387)
                                                                           at java.lang.reflect.Method.invokeNative(Native Method)
                                                                           at java.lang.reflect.Method.invoke(Method.java:515)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
                                                                           at dalvik.system.NativeStart.main(Native Method)

**附TinyWindow使用代码，其余配置都是您Demo上的基本配置**：
                if (scrollY > mpContentHeight && mpContent.currentState == JCVideoPlayer.CURRENT_STATE_PLAYING) {
                    if (!isTinyNow) {
                        isTinyNow = true;
                        mpContent.startWindowTiny();
                    }
                } else {
                    if (isTinyNow) {
                        svContent.stopNestedScroll();
                        isTinyNow = false;
                        JCVideoPlayer.backPress();
                    }
                }

**Comment by lipangit** [comment]
isTinyNow 这个变量是后加的吧，库里有currentWindow变量，表示了当前窗口是列表、全屏、小窗或者普通。

log里没看到JCvideoPlayer的包名，你断点调试一下在进入小窗之前确保没有release视频，我以前遇到过类似问题，如果视频release了在新生成的surface之后会闪退
