### ISSUE TITLE
遇到了个crash问题，我是在recycleview中使用

### ISSUE THREAD

**Issue by CentMeng** [lipangit/jiecaovideoplayer#54]
Caused by: java.lang.IllegalArgumentException: The surface has been released 在JCVideoPlayer 775

**Comment by lipangit** [comment]
请问是最新版本2.0吗，在2.0中点击开始按钮之后才会通过addview的方式添加surfaceview，避免了列表滑动时surfaceview destroy的问题

**Comment by CentMeng** [comment]
是2.0而且使用的引用library 的lib

**Comment by CentMeng** [comment]
Process: com.luoteng.folk, PID: 31243
                                                                  java.lang.IllegalArgumentException: The surface has been released
                                                                      at android.media.MediaPlayer._setVideoSurface(Native Method)
                                                                      at android.media.MediaPlayer.setDisplay(MediaPlayer.java:782)
                                                                      at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.onPrepared(JCVideoPlayer.java:780)
                                                                      at fm.jiecao.jcvideoplayer_lib.JCMediaManager.onPrepared(JCMediaManager.java:61)
                                                                      at android.media.MediaPlayer$EventHandler.handleMessage(MediaPlayer.java:3380)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                      at android.os.Looper.loop(Looper.java:145)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5942)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at java.lang.reflect.Method.invoke(Method.java:372)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)


使用你刚fixbug的

**Comment by lipangit** [comment]
好吧回去调试一下，如果你能给我个现成的demo就更好了

**Comment by CentMeng** [comment]
Sorry,我是在项目中整的，拷贝出来比较麻烦，就是recycleview中使用

**Comment by lipangit** [comment]
行我回去试试，来波star吧同学^_^

**Comment by CentMeng** [comment]
我回去也看看，麻烦大神有思路了修改后通知我一下，谢谢

**Comment by lipangit** [comment]
@CentMeng  https://github.com/wangjiegulu/RecyclerViewSample 刚才在这个项目的基础上LINEARLAYOUT的例子中添加JCVideoPlayer，列表啥问题没有，不知道你遇到的问题是怎么来的。上拉下拉，进入全屏和退出全屏，都没有问题

**Comment by CentMeng** [comment]
需要多试几次，是在recycleview吗？就是还没播放直接滑动下方点下一个，来回快速切换

发自我的 iPhone

**Comment by lipangit** [comment]
照你这么做是会崩溃，我研究一下

**Comment by CentMeng** [comment]
hello，problem has fixed?

**Comment by lipangit** [comment]
在develop分支上解决了
