### ISSUE TITLE
华为手机android 5.1版本，运行demo崩溃

### ISSUE THREAD

**Issue by rwz657026189** [lipangit/JieCaoVideoPlayer#542]
在ListView界面多次切换视频播放后，会在某个视频播放时crash，退出了列表页，但没有退出程序。不是一定发生，但概率挺大，基本切换到7,8个视频时都出发生了。
`610-610/fm.jiecao.jiecaovideoplayer E/art: ClassLinker::FindClass not found:Landroid/view/SearchEvent;
12-04 20:25:34.342 610-610/fm.jiecao.jiecaovideoplayer W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
12-04 20:25:34.363 610-610/fm.jiecao.jiecaovideoplayer D/AccessibilityManager: setStateLocked: wasEnabled = false, mIsEnabled = false, wasTouchExplorationEnabled = false, mIsTouchExplorationEnabled = false, wasHighTextContrastEnabled = false, mIsHighTextContrastEnabled = false
                                                                               java.lang.Throwable: setStateLocked
                                                                                   at android.view.accessibility.AccessibilityManager.setStateLocked(AccessibilityManager.java:553)
                                                                                   at android.view.accessibility.AccessibilityManager.tryConnectToServiceLocked(AccessibilityManager.java:636)
                                                                                   at android.view.accessibility.AccessibilityManager.<init>(AccessibilityManager.java:226)
                                                                                   at android.view.accessibility.AccessibilityManager.getInstance(AccessibilityManager.java:206)
                                                                                   at android.view.View.setFlags(View.java:9851)
                                                                                   at android.view.ViewGroup.initViewGroup(ViewGroup.java:536)
                                                                                   at android.view.ViewGroup.<init>(ViewGroup.java:525)
                                                                                   at android.view.ViewGroup.<init>(ViewGroup.java:520)
                                                                                   at android.view.ViewGroup.<init>(ViewGroup.java:516)
                                                                                   at android.view.ViewGroup.<init>(ViewGroup.java:512)
                                                                                   at android.widget.FrameLayout.<init>(FrameLayout.java:119)
                                                                                   at com.android.internal.policy.impl.PhoneWindow$DecorView.<init>(PhoneWindow.java:2337)
                                                                                   at com.android.internal.policy.impl.PhoneWindow.generateDecor(PhoneWindow.java:3518)
                                                                                   at com.android.internal.policy.impl.PhoneWindow.installDecor(PhoneWindow.java:3907)
                                                                                   at com.android.internal.policy.impl.PhoneWindow.getDecorView(PhoneWindow.java:2050)
                                                                                   at android.support.v7.app.AppCompatDelegateImplV7.createSubDecor(AppCompatDelegateImplV7.java:363)
                                                                                   at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java:312)
                                                                                   at android.support.v7.app.AppCompatDelegateImplV7.initWindowDecorActionBar(AppCompatDelegateImplV7.java:172)
                                                                                   at android.support.v7.app.AppCompatDelegateImplBase.getSupportActionBar(AppCompatDelegateImplBase.java:100)
                                                                                   at android.support.v7.app.AppCompatActivity.getSupportActionBar(AppCompatActivity.java:110)
                                                                                   at fm.jiecao.jiecaovideoplayer.ListViewActivity.onCreate(ListViewActivity.java:20)
                                                                                   at android.app.Activity.performCreate(Activity.java:6161)
                                                                                   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1112)`

**Comment by lipangit** [comment]
刚release的5.0_preview吗

**Comment by rwz657026189** [comment]
不是的，是4.8.3。现在的5.0_preview测试过了，切换了三四十次都没有崩溃了。

**Comment by rwz657026189** [comment]
现在最低支持16，应该是用来google的exoplayer缘故吧，对我现在的项目有点高，之前的版本，不再维护了吗？

**Comment by lipangit** [comment]
对不再维护，提升最低支持的安卓版本没有想象中可怕

**Comment by lipangit** [comment]
@rwz657026189 你对测试有研究吗，是随机测试还是能指定操作流程，能帮忙测试一下release的版本吗

**Comment by rwz657026189** [comment]
没研究过哦，都是手动测试。
