### ISSUE TITLE
Crash. Uncaught exception thrown by finalizer

### ISSUE THREAD

**Issue by shahbaz2417** [lipangit/JieCaoVideoPlayer#550]
No implementation found for void tv.danmaku.ijk.media.player.IjkMediaPlayer.native_finalize() (tried Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1finalize and Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1finalize__)

---------------------------------------

java.lang.UnsatisfiedLinkError: No implementation found for void tv.danmaku.ijk.media.player.IjkMediaPlayer.native_finalize() (tried Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1finalize and Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1finalize__)
                                                                   at tv.danmaku.ijk.media.player.IjkMediaPlayer.native_finalize(Native Method)
                                                                   at tv.danmaku.ijk.media.player.IjkMediaPlayer.finalize(IjkMediaPlayer.java:893)
                                                                   at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:202)
                                                                   at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:185)
                                                                   at java.lang.Thread.run(Thread.java:818)

**Comment by lipangit** [comment]
Use exoplayer in future,I will not research ijkplayer.

**Comment by shahbaz2417** [comment]
That means  you guys are not giving support for earlier implementation. 
Is that new exolplayer implementation is reliable?

**Comment by lipangit** [comment]
Yes, old version will be abandoned.
It is reliable, I will test carefully

**Comment by shahbaz2417** [comment]
Thanks @lipangit
