### ISSUE TITLE
how to play programatically ?

### ISSUE THREAD

**Issue by Hitexroid** [lipangit/JieCaoVideoPlayer#551]
In new version , this code `JCMediaManager.instance().mediaPlayer.start();` not work !

**Comment by lipangit** [comment]
Did you prepare before start?

**Comment by lipangit** [comment]
jcVideoPlayer.startButton.performClick()  auto play video

**Comment by Hitexroid** [comment]
Thank you `performClick()` workd .

**Comment by dinhtrungvn92** [comment]
@lipangit I used jzVideoPlayerStandard.startButton.performClick() when focus to center video of recycleview and it worked, but when view full screen and rotating to lanscape, force close some time occurred. if without auto play, nothing FC. Did you see it yet?

**Comment by dinhtrungvn92** [comment]
Logcat : 
FATAL EXCEPTION: main
                                                                  Process: vn.sfive.browser, PID: 12161
                                                                  java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getVisibility()' on a null object reference
                                                                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:275)
                                                                      at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                      at android.view.View.layout(View.java:18804)
                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5951)
                                                                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                      at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                      at android.view.View.layout(View.java:18804)
                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5951)
                                                                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                      at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                      at android.view.View.layout(View.java:18804)
                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5951)
                                                                      at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                                                      at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                      at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                      at android.view.View.layout(View.java:18804)
                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5951)
                                                                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                      at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                      at com.android.internal.policy.DecorView.onLayout(DecorView.java:887)
                                                                      at android.view.View.layout(View.java:18804)
                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5951)
                                                                      at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2659)
                                                                      at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2375)
                                                                      at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1526)
                                                                      at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7102)
                                                                      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:927)
                                                                      at android.view.Choreographer.doCallbacks(Choreographer.java:702)
                                                                      at android.view.Choreographer.doFrame(Choreographer.java:638)
                                                                      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:913)
                                                                      at android.os.Handler.handleCallback(Handler.java:751)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                      at android.os.Looper.loop(Looper.java:154)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:6682)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

**Comment by lipangit** [comment]
break point at MediaPlayer.release()，  The video must not played when the see the log, right? so I must run MediaPlayer.release() at a wrong time, solve it can fix the exception

**Comment by fukemy** [comment]
```
jzVideoPlayerStandard = findViewById(R.id.videoplayer);
jzVideoPlayerStandard.progressBar.setEnabled(false);
jzVideoPlayerStandard.startButton.setAlpha(0);
```
the above method worked, but when toggle fullscreen then progressbar enabled, and startButton visible. Can you help?

**Comment by fukemy** [comment]
working now. THanks u

**Comment by Kamlesh-ECInfosolutions** [comment]
JCVideoPlayerStandard minimize button not working.When we playing video in full screen in landscape mode.

**Comment by Kamlesh-ECInfosolutions** [comment]
How to hide minimize / maximize icon of jzvideoplayerstandard  when we playing video in landscape mode .
