### ISSUE TITLE
ArithmeticException: divide by zero

### ISSUE THREAD

**Issue by zboing** [lipangit/JieCaoVideoPlayer#557]
Phone: Samsung Galaxy S2, OS: Android 4.1.2, Lib version: 5.0.1_preview
Issue appears when playing a video from a recycler view and it points to the below lines from the library class JCResizeTextureView:
        Log.i(TAG, "viewWidth = " + width + ", " + "viewHeight = " + height);
        Log.i(TAG, "viewWidth / viewHeight = " + width / height);
        setMeasuredDimension(width, height);

Logcat console:
java.lang.ArithmeticException: divide by zero
	at fm.jiecao.jcvideoplayer_lib.JCResizeTextureView.onMeasure(JCResizeTextureView.java:133)
	at android.view.View.measure(View.java:15504)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5059)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
	at android.view.View.measure(View.java:15504)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:617)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:399)
	at android.view.View.measure(View.java:15504)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5059)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
	at android.view.View.measure(View.java:15504)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:617)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:399)
	at android.view.View.measure(View.java:15504)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5059)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
	at android.support.v7.widget.CardView.onMeasure(CardView.java:209)
	at android.view.View.measure(View.java:15504)
	at android.support.v7.widget.RecyclerView$LayoutManager.measureChildWithMargins(RecyclerView.java:8158)
	at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1471)
	at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1408)
	at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:580)
	at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3374)
	at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3183)
	at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3627)
	at android.view.View.layout(View.java:14072)
	at android.view.ViewGroup.layout(ViewGroup.java:4607)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:948)
	at android.view.View.layout(View.java:14072)
	at android.view.ViewGroup.layout(ViewGroup.java:4607)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1655)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1513)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1426)
	at android.view.View.layout(View.java:14072)
	at android.view.ViewGroup.layout(ViewGroup.java:4607)
	at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1193)
	at android.view.View.layout(View.java:14072)
	at android.view.ViewGroup.layout(ViewGroup.java:4607)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:948)
	at android.view.View.layout(View.java:14072)
	at android.view.ViewGroup.layout(ViewGroup.java:4607)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
	at android.view.View.layout(View.java:14072)
	at android.view.ViewGroup.layout(ViewGroup.java:4607)
	at android.support.v7.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:437)
	at android.view.View.layout(View.java:14072)
	at android.view.ViewGroup.layout(ViewGroup.java:4607)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
	at android.view.View.layout(View.java:14072)
	at android.view.ViewGroup.layout(ViewGroup.java:4607)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1655)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1513)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1426)
	at android.view.View.layout(View.java:14072)
	at android.view.ViewGroup.layout(ViewGroup.java:4607)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
	at android.view.View.layout(View.java:14072)
	at android.view.ViewGroup.layout(ViewGroup.java:4607)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:1997)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1818)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1115)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4526)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:725)
	at android.view.Choreographer.doCallbacks(Choreographer.java:555)
	at android.view.Choreographer.doFrame(Choreographer.java:525)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:711)
	at android.os.Handler.handleCallback(Handler.java:615)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:4921)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1027)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by lipangit** [comment]
Thank you, this is bug, Will fix next version.

**Comment by zboing** [comment]
issue fixed in version 5.2. thanks!
