### ISSUE TITLE
支持缓存

### ISSUE THREAD

**Issue by flztsj** [lipangit/JieCaoVideoPlayer#560]
https://github.com/danikula/AndroidVideoCache

使用这个库，直接很简单的把视频url封装一层后就可以边播边缓存了。

**Comment by lipangit** [comment]
好的，有时间我研究一下，尤其是进度不连续的时候怎么缓存

**Comment by bravekingzhang** [comment]
@flztsj @lipangit 这个有个bug，出现这个比较频繁  ：

```java
E/HttpProxyCacheServer: HttpProxyCacheServer error
                                                                             com.danikula.videocache.ProxyCacheException: Error closing socket output stream
                                                                                 at com.danikula.videocache.HttpProxyCacheServer.closeSocketOutput(HttpProxyCacheServer.java:294)
                                                                                 at com.danikula.videocache.HttpProxyCacheServer.releaseSocket(HttpProxyCacheServer.java:270)
                                                                                 at com.danikula.videocache.HttpProxyCacheServer.processSocket(HttpProxyCacheServer.java:242)
                                                                                 at com.danikula.videocache.HttpProxyCacheServer.access$200(HttpProxyCacheServer.java:52)
                                                                                 at com.danikula.videocache.HttpProxyCacheServer$SocketProcessorRunnable.run(HttpProxyCacheServer.java:337)
```

**Comment by fflin** [comment]
那么这个问题的最终解决方案呢?
