### ISSUE TITLE
Null Pointer Exception in 5.0.1_preview

### ISSUE THREAD

**Issue by bishtmayank** [lipangit/JieCaoVideoPlayer#565]
E/AndroidRuntime: FATAL EXCEPTION: main
                                                                       java.lang.NullPointerException: Attempt to invoke virtual method 'long com.google.android.exoplayer2.SimpleExoPlayer.getDuration()' on a null object reference
                                                                           at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.getDuration(JCVideoPlayer.java:732)
                                                                           at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.setTextAndProgress(JCVideoPlayer.java:743)
                                                                           at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer$ProgressTimerTask$1.run(JCVideoPlayer.java:704)
                                                                           at android.os.Handler.handleCallback(Handler.java:739)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                           at android.os.Looper.loop(Looper.java:148)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by lipangit** [comment]
mediaplayer has been release

**Comment by lipangit** [comment]
Fix this?
