### ISSUE TITLE
Can JC video player support auto pause when scroll a recyclerview out of visible scope 

### ISSUE THREAD

**Issue by jiechu** [lipangit/jiecaovideoplayer#57]
JC video player is good if we want to play a mp4 in current position. but if we pull-to-refresh or loading-more a recycler view, the application will crash due to it does not support automatically pause or destroy.
Can it support it in native so that we can avoid put more boring codes?
Also if vitamio is not free for some usage, can it integrate ffmpeg as a replacement?

Best wishes.

**Comment by lipangit** [comment]
if videoplayer out of vidible it will reset , because when reuse the item will call setUp(), this function will change the videoplayer to normal state .  

How to use ffmpeg to play video in android , we can import  vitamio or exoplayer , have other way?

**Comment by jiechu** [comment]
When loadingmore is called, then show exception:
 java.lang.IllegalStateException
                                                                   at android.media.MediaPlayer._stop(Native Method)
                                                                   at android.media.MediaPlayer.stop(MediaPlayer.java:1249)
                                                                   at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.setUp(JCVideoPlayer.java:157)
                                                                   at my.VideoListAdapter.showVideo(VideoListAdapter.java:260)
                                                                   at my.VideoListAdapter.onBindViewHolderCursor(VideoListAdapter.java:93)

Here is the method:
```
private void showVideo(ViewHolder viewHolder, final String video, final String pic) {
        if (!TextUtils.isEmpty(video)) {
            viewHolder.videoView.setVisibility(View.VISIBLE);
            if (!TextUtils.isEmpty(pic)) {
                Picasso.with(GlobalContext.getGlobalContext()).load(pic).fit().centerInside().into(viewHolder.videoView.ivThumb);
            }

            viewHolder.videoView.setUp(video, null, false);
            viewHolder.videoView.onPrepared();
        } else {
            viewHolder.videoView.onCompletion();
            viewHolder.videoView.release();
            viewHolder.videoView.setVisibility(View.GONE);
        }
    }
```

**Comment by lipangit** [comment]
if it work well use it for now , few days later will release v3.0 , code will more flexable .
