### ISSUE TITLE
播放flv文件时，出现有图像，没有声音

### ISSUE THREAD

**Issue by ndlxp2008** [lipangit/JieCaoVideoPlayer#575]
播放flv文件时，出现有图像，没有声音

**Comment by lipangit** [comment]
是5.1新版吗，log发来看看，你用exoplayer官方的demo试试

**Comment by ndlxp2008** [comment]
4.8.3版本的，官方报错：我的flv地址，http://www.sfda.gov.cn/WS01/video/example/20160727syaqscxrky.flv


/EventLogger: internalError [0.60, loadError]
                                                                                 com.google.android.exoplayer2.extractor.flv.TagPayloadReader$UnsupportedFormatException: Audio format not supported: 2
                                                                                     at com.google.android.exoplayer2.extractor.flv.AudioTagPayloadReader.parseHeader(AudioTagPayloadReader.java:68)
                                                                                     at com.google.android.exoplayer2.extractor.flv.TagPayloadReader.consume(TagPayloadReader.java:64)
                                                                                     at com.google.android.exoplayer2.extractor.flv.FlvExtractor.readTagData(FlvExtractor.java:251)
                                                                                     at com.google.android.exoplayer2.extractor.flv.FlvExtractor.read(FlvExtractor.java:158)
                                                                                     at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:630)
                                                                                     at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                                                     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                     at java.lang.Thread.run(Thread.java:818)
12-19 17:00:16.531 12260-12260/com.google.android.exoplayer2.demo E/EventLogger: internalError [0.85, loadError]
                                                                                 com.google.android.exoplayer2.extractor.flv.TagPayloadReader$UnsupportedFormatException: Audio format not supported: 0
                                                                                     at com.google.android.exoplayer2.extractor.flv.AudioTagPayloadReader.parseHeader(AudioTagPayloadReader.java:68)
                                                                                     at com.google.android.exoplayer2.extractor.flv.TagPayloadReader.consume(TagPayloadReader.java:64)
                                                                                     at com.google.android.exoplayer2.extractor.flv.FlvExtractor.readTagData(FlvExtractor.java:251)
                                                                                     at com.google.android.exoplayer2.extractor.flv.FlvExtractor.read(FlvExtractor.java:158)
                                                                                     at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:630)
                                                                                     at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                                                     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                     at java.lang.Thread.run(Thread.java:818)
12-19 17:00:17.781 12260-12260/com.google.android.exoplayer2.demo E/EventLogger: internalError [2.10, loadError]
                                                                                 com.google.android.exoplayer2.extractor.flv.TagPayloadReader$UnsupportedFormatException: Audio format not supported: 3
                                                                                     at com.google.android.exoplayer2.extractor.flv.AudioTagPayloadReader.parseHeader(AudioTagPayloadReader.java:68)
                                                                                     at com.google.android.exoplayer2.extractor.flv.TagPayloadReader.consume(TagPayloadReader.java:64)
                                                                                     at com.google.android.exoplayer2.extractor.flv.FlvExtractor.readTagData(FlvExtractor.java:251)
                                                                                     at com.google.android.exoplayer2.extractor.flv.FlvExtractor.read(FlvExtractor.java:158)
                                                                                     at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:630)
                                                                                     at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                                                     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                     at java.lang.Thread.run(Thread.java:818)
12-19 17:00:20.044 12260-12260/com.google.android.exoplayer2.demo E/EventLogger: internalError [4.36, loadError]
                                                                                 com.google.android.exoplayer2.extractor.flv.TagPayloadReader$UnsupportedFormatException: Audio format not supported: 11
                                                                                     at com.google.android.exoplayer2.extractor.flv.AudioTagPayloadReader.parseHeader(AudioTagPayloadReader.java:68)
                                                                                     at com.google.android.exoplayer2.extractor.flv.TagPayloadReader.consume(TagPayloadReader.java:64)
                                                                                     at com.google.android.exoplayer2.extractor.flv.FlvExtractor.readTagData(FlvExtractor.java:251)
                                                                                     at com.google.android.exoplayer2.extractor.flv.FlvExtractor.read(FlvExtractor.java:158)
                                                                                     at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:630)
                                                                                     at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                                                     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                     at java.lang.Thread.run(Thread.java:818)
12-19 17:00:20.053 12260-12341/com.google.android.exoplayer2.demo E/ExoPlayerImplInternal: Source error.
                                                                                           com.google.android.exoplayer2.extractor.flv.TagPayloadReader$UnsupportedFormatException: Audio format not supported: 11
                                                                                               at com.google.android.exoplayer2.extractor.flv.AudioTagPayloadReader.parseHeader(AudioTagPayloadReader.java:68)
                                                                                               at com.google.android.exoplayer2.extractor.flv.TagPayloadReader.consume(TagPayloadReader.java:64)
                                                                                               at com.google.android.exoplayer2.extractor.flv.FlvExtractor.readTagData(FlvExtractor.java:251)
                                                                                               at com.google.android.exoplayer2.extractor.flv.FlvExtractor.read(FlvExtractor.java:158)
                                                                                               at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:630)
                                                                                               at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                                                               at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                                               at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                               at java.lang.Thread.run(Thread.java:818)
12-19 17:00:20.056 12260-12260/com.google.android.exoplayer2.demo E/EventLogger: playerFailed [4.37]
                                                                                 com.google.android.exoplayer2.ExoPlaybackException
                                                                                     at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:360)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                     at android.os.Looper.loop(Looper.java:148)
                                                                                     at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                     at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                                                  Caused by: com.google.android.exoplayer2.extractor.flv.TagPayloadReader$UnsupportedFormatException: Audio format not supported: 11
                                                                                     at com.google.android.exoplayer2.extractor.flv.AudioTagPayloadReader.parseHeader(AudioTagPayloadReader.java:68)
                                                                                     at com.google.android.exoplayer2.extractor.flv.TagPayloadReader.consume(TagPayloadReader.java:64)
                                                                                     at com.google.android.exoplayer2.extractor.flv.FlvExtractor.readTagData(FlvExtractor.java:251)
                                                                                     at com.google.android.exoplayer2.extractor.flv.FlvExtractor.read(FlvExtractor.java:158)
                                                                                     at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:630)
                                                                                     at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                                                     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                     at java.lang.Thread.run(Thread.java:818)

**Comment by ndlxp2008** [comment]
说是不支持格式，但是具体不清楚怎么不支持，flv都是一样的吧，又不一样的还真不知道。

**Comment by lipangit** [comment]
flv好像是有问题
