### ISSUE TITLE
安卓5.0版本以上系统横向全屏播放崩溃

### ISSUE THREAD

**Issue by hackboy** [lipangit/JieCaoVideoPlayer#593]
全屏播放在SCREEN_ORIENTATION_PORTRAIT模式下可以播放，但是调整为SCREEN_ORIENTATION_LANDSCAPE模式时在安卓5.0版本以上直接崩溃，未能排查出问题，activity也已做对应配置
            android:configChanges="orientation|keyboardHidden|screenSize"
            android:screenOrientation="portrait"

报错信息如下
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'long com.google.android.exoplayer2.SimpleExoPlayer.getCurrentPosition()' on a null object reference
   at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.getCurrentPositionWhenPlaying(JCVideoPlayer.java:689)
   at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.onCompletion(JCVideoPlayer.java:424)
   at fm.jiecao.jcvideoplayer_lib.JCVideoPlayerManager.completeAll(JCVideoPlayerManager.java:42)
   at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.releaseAllVideos(JCVideoPlayer.java:793)
   at com.dahe.news.ui.NewsDetailCommentActivity.onPause(NewsDetailCommentActivity.java:721)
   at android.app.Activity.performPause(Activity.java:6194)
   at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1319)
   at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3346)
   at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3319) 
   at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3294) 
   at android.app.ActivityThread.access$1100(ActivityThread.java:175) 
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1377) 
   at android.os.Handler.dispatchMessage(Handler.java:102) 
   at android.os.Looper.loop(Looper.java:135) 
   at android.app.ActivityThread.main(ActivityThread.java:5400) 
   at java.lang.reflect.Method.invoke(Native Method) 
   at java.lang.reflect.Method.invoke(Method.java:372) 
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1037) 
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)

**Comment by lipangit** [comment]
SimpleExoPlayer 已经是空了，一定是因为进入releaseVideo，打断点看堆栈，是哪调用了releasevideo

**Comment by hackboy** [comment]
@lipangit 进行调试后发现在切换到竖屏全屏播放时，前面打开的activity都被destroy，包括这个播放视频的activity，然后会走这个activity的onPause方法，而我参照demo在onpause里调用了releaseallvideo方法，不知道为什么竖屏切换为什么会导致所有启动activity的销毁重建

**Comment by hackboy** [comment]
@lipangit 解决了，我刚看了下全屏逻辑，知道问题出在哪了了。。。。谢谢了

**Comment by heroleon** [comment]
@hackboy  你好，请问能描述一下是怎么解决这个问题的呢？

**Comment by hackboy** [comment]
@heroleon 不止当前activity需要进行activity的配置，其他activity也需要进行配置

**Comment by heroleon** [comment]
@hackboy 多谢了
