### ISSUE TITLE
when open the app,it has been crashed.

### ISSUE THREAD

**Issue by hschenzhimin** [lipangit/jiecaovideoplayer#60]
04-25 11:16:59.931 14817-14817/fm.jiecao.jiecaovideoplayer E/AndroidRuntime: FATAL EXCEPTION: main
                                                                             Process: fm.jiecao.jiecaovideoplayer, PID: 14817
                                                                             java.lang.RuntimeException: Unable to start activity ComponentInfo{fm.jiecao.jiecaovideoplayer/fm.jiecao.jiecaovideoplayer.MainActivity}: android.view.InflateException: Binary XML file line #48: Error inflating class fm.jiecao.jiecaovideoplayer.View.JCVideoPlayerStandardWithShareButton
                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3133)
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3243)
                                                                                 at android.app.ActivityThread.access$1000(ActivityThread.java:218)
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1718)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                 at android.os.Looper.loop(Looper.java:145)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:6917)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
                                                                              Caused by: android.view.InflateException: Binary XML file line #48: Error inflating class fm.jiecao.jiecaovideoplayer.View.JCVideoPlayerStandardWithShareButton
                                                                                 at android.view.LayoutInflater.createView(LayoutInflater.java:640)
                                                                                 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:750)
                                                                                 at android.view.LayoutInflater.rInflate(LayoutInflater.java:813)
                                                                                 at android.view.LayoutInflater.rInflate(LayoutInflater.java:821)
                                                                                 at android.view.LayoutInflater.rInflate(LayoutInflater.java:821)
                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:511)
                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:415)
                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:366)
                                                                                 at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:256)
                                                                                 at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:109)
                                                                                 at fm.jiecao.jiecaovideoplayer.MainActivity.onCreate(MainActivity.java:31)
                                                                                 at android.app.Activity.performCreate(Activity.java:6609)
                                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1134)
                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3086)
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3243) 
                                                                                 at android.app.ActivityThread.access$1000(ActivityThread.java:218) 
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1718) 
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                 at android.os.Looper.loop(Looper.java:145) 
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:6917) 
                                                                                 at java.lang.reflect.Method.invoke(Native Method) 
                                                                                 at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404) 
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199) 
                                                                              Caused by: java.lang.reflect.InvocationTargetException
                                                                                 at java.lang.reflect.Constructor.newInstance(Native Method)
                                                                                 at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
                                                                                 at android.view.LayoutInflater.createView(LayoutInflater.java:614)
                                                                                 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:750) 
                                                                                 at android.view.LayoutInflater.rInflate(LayoutInflater.java:813) 
                                                                                 at android.view.LayoutInflater.rInflate(LayoutInflater.java:821) 
                                                                                 at android.view.LayoutInflater.rInflate(LayoutInflater.java:821) 
                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:511) 
                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:415) 
                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:366) 
                                                                                 at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:256) 
                                                                                 at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:109) 
                                                                                 at fm.jiecao.jiecaovideoplayer.MainActivity.onCreate(MainActivity.java:31) 
                                                                                 at android.app.Activity.performCreate(Activity.java:6609) 
                                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1134) 
                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3086) 
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3243) 
                                                                                 at android.app.ActivityThread.access$1000(ActivityThread.java:218) 
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1718) 
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                 at android.os.Looper.loop(Looper.java:145) 
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:6917) 
                                                                                 at java.lang.reflect.Method.invoke(Native Method) 
                                                                                 at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404) 
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199) 
                                                                              Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.ViewGroup.setOnClickListener(android.view.View$OnClickListener)' on a null object reference
                                                                                 at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.init(JCVideoPlayer.java:83)
                                                                                 at fm.jiecao.jcvideoplayer_lib.JCVideoPlayerStandard.init(JCVideoPlayerStandard.java:39)
                                                                                 at fm.jiecao.jiecaovideoplayer.View.JCVideoPlayerStandardWithShareButton.init(JCVideoPlayerStandardWithShareButton.java:30)
                                                                                 at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.<init>(JCVideoPlayer.java:66)
                                                                                 at fm.jiecao.jcvideoplayer_lib.JCVideoPlayerStandard.<init>(JCVideoPlayerStandard.java:0)
                                                                                 at fm.jiecao.jiecaovideoplayer.View.JCVideoPlayerStandardWithShareButton.<init>(JCVideoPlayerStandardWithShareButton.java:0)
                                                                                 at java.lang.reflect.Constructor.newInstance(Native Method) 
                                                                                 at java.lang.reflect.Constructor.newInstance(Constructor.java:288) 
                                                                                 at android.view.LayoutInflater.createView(LayoutInflater.java:614) 
                                                                                 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:750) 
                                                                                 at android.view.LayoutInflater.rInflate(LayoutInflater.java:813) 
                                                                                 at android.view.LayoutInflater.rInflate(LayoutInflater.java:821) 
                                                                                 at android.view.LayoutInflater.rInflate(LayoutInflater.java:821) 
                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:511) 
                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:415) 
                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:366) 
                                                                                 at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:256) 
                                                                                 at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:109) 
                                                                                 at fm.jiecao.jiecaovideoplayer.MainActivity.onCreate(MainActivity.java:31) 
                                                                                 at android.app.Activity.performCreate(Activity.java:6609) 
                                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1134) 
                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3086) 
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3243) 
                                                                                 at android.app.ActivityThread.access$1000(ActivityThread.java:218) 
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1718) 
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                 at android.os.Looper.loop(Looper.java:145) 
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:6917) 
                                                                                 at java.lang.reflect.Method.invoke(Native Method) 
                                                                                 at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404) 
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)

**Comment by lipangit** [comment]
Yes id was wrong, When I write readme.md I change some id for good look, and I forget change other layout.

**Comment by lipangit** [comment]
Thank you very much
