### ISSUE TITLE
onbackpressed SimpleExoPlayer.getDuration()' on a null object reference

### ISSUE THREAD

**Issue by naguchennai** [lipangit/JieCaoVideoPlayer#607]
`java.lang.NullPointerException: Attempt to invoke virtual method 'long com.google.android.exoplayer2.SimpleExoPlayer.getDuration()' on a null object reference
                                                       at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.getDuration(JCVideoPlayer.java:705)
                                                       at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.setTextAndProgress(JCVideoPlayer.java:715)
                                                       at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer$ProgressTimerTask$1.run(JCVideoPlayer.java:680)
                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:148)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`

i added 

` @Override
    public void onBackPressed() {
        if (JCVideoPlayer.backPress()) {
            return;
        }
        super.onBackPressed();
    }
    @Override
    protected void onPause() {
        super.onPause();
        JCVideoPlayer.releaseAllVideos();
    }

Still error any idea?`

**Comment by lipangit** [comment]
mediaplayer has been released.

break point on mediaplayer.release(), find out where release mediaplayer.

**Comment by SuperBeagleDog** [comment]
on the method of onPause , I did release action .
