### ISSUE TITLE
一点击全屏播放就闪退，请问这个问题怎么解决？

### ISSUE THREAD

**Issue by 103king** [lipangit/JieCaoVideoPlayer#608]
java.lang.RuntimeException: Error during detachFromGLContext (see logcat for details)
                                                       at android.graphics.SurfaceTexture.attachToGLContext(SurfaceTexture.java:237)
                                                       at android.view.GLES20TextureLayer.setSurfaceTexture(GLES20TextureLayer.java:81)
                                                       at android.view.HardwareRenderer$Gl20Renderer.setSurfaceTexture(HardwareRenderer.java:1576)
                                                       at android.view.TextureView.getHardwareLayer(TextureView.java:393)
                                                       at android.view.View.getDisplayList(View.java:12809)
                                                       at android.view.View.getDisplayList(View.java:12890)
                                                       at android.view.View.draw(View.java:13640)
                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3050)
                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2912)
                                                       at android.view.View.getDisplayList(View.java:12841)
                                                       at android.view.View.getDisplayList(View.java:12890)
                                                       at android.view.View.draw(View.java:13640)
                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3050)
                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2912)
                                                       at android.view.View.draw(View.java:13947)
                                                       at android.view.View.getDisplayList(View.java:12846)
                                                       at android.view.View.getDisplayList(View.java:12890)
                                                       at android.view.View.draw(View.java:13640)
                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3050)
                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2912)
                                                       at android.view.View.getDisplayList(View.java:12841)
                                                       at android.view.View.getDisplayList(View.java:12890)
                                                       at android.view.View.draw(View.java:13640)
                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3050)
                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2912)
                                                       at android.view.View.draw(View.java:13947)
                                                       at android.widget.FrameLayout.draw(FrameLayout.java:467)
                                                       at android.view.View.getDisplayList(View.java:12846)
                                                       at android.view.View.getDisplayList(View.java:12890)
                                                       at android.view.View.draw(View.java:13640)
                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3050)
                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2912)
                                                       at android.view.View.draw(View.java:13947)
                                                       at android.support.v7.widget.ActionBarOverlayLayout.draw(ActionBarOverlayLayout.java:442)
                                                       at android.view.View.getDisplayList(View.java:12846)
                                                       at android.view.View.getDisplayList(View.java:12890)
                                                       at android.view.View.draw(View.java:13640)
                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3050)
                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2912)
                                                       at android.view.View.getDisplayList(View.java:12841)
                                                       at android.view.View.getDisplayList(View.java:12890)
                                                       at android.view.View.draw(View.java:13640)
                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3050)
                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2912)
                                                       at android.view.View.getDisplayList(View.java:12841)
                                                       at android.view.View.getDisplayList(View.java:12890)
                                                       at android.view.View.draw(View.java:13640)
                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3050)
                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2912)
                                                       at android.view.View.draw(View.java:13947)
                                                       at android.widget.FrameLayout.draw(FrameLayout.java:467)
                                                       at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2247)
                                                       at android.view.View.getDisplayList(View.java:12846)
                                                       at android.view.View.getDisplayList(View.java:12890)
                                                       at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1249)
                                                       at android.view.ViewRootImpl.draw(ViewRootImpl.java:2572)
                                                       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2439)
                                                       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2241)
                                                       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1216)
                                                       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5044)
                                                       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:776)
                                                       at android.view.Choreographer.doCallbacks(Choreographer.java:579)
                                                       at android.view.Choreographer.doFrame(Choreographer.java:548)
                                                       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:762)
                                                       at android.os.Handler.handleCallback(Handler.java:800)
                                                       at android.os.Handler.dispatchMessage(Handler.java:100)
                                                       at android.os.Looper.loop(Looper.java:194)
                                                   	at android.app.Acti

**Comment by lipangit** [comment]
改库了吧

断点一下SurfaceTexture的生命周期，是不是destory了

**Comment by 103king** [comment]
你说的改“库”了指的是哪个库？

**Comment by lipangit** [comment]
是不是改了JCVideoPlayer了，记得MediaPlayer release之后再切换全屏就有这个问题
