### ISSUE TITLE
播放正常的网络视频，无法播放。

### ISSUE THREAD

**Issue by wujun19941207** [lipangit/JieCaoVideoPlayer#609]
以前正常使用，但是在本次更新以后，视频无法正常播放，报错无法找到正确的资源。
一样的代码，没有任何更改，更新以后导致的。

请问是出什么问题了吗？

代码大概是这样的:
jcVideoPlayer.setUp(path, JCVideoPlayer.SCREEN_WINDOW_FULLSCREEN, "视频"); 
  jcVideoPlayer.startPlayLogic(); 
报错是这样的:
E/ExoPlayerImplInternal: Source error.
E/JieCaoVideoPlayer: onError -10000 - -10000 [782923114] 
视频地址：
http://v.jiemian.com/25/d1/25d166c99cc70bdf3da03f4866f4188b_256.mp4

Html 页面播放没有问题。

**Comment by lipangit** [comment]
log是什么，是从4.*更行到5.*吗

**Comment by wujun19941207** [comment]
E/ExoPlayerImplInternal: Source error.
E/JieCaoVideoPlayer: onError -10000 - -10000 [782923114]

**Comment by wujun19941207** [comment]
@lipangit 
代码大概是这样的:
jcVideoPlayer.setUp(path, JCVideoPlayer.SCREEN_WINDOW_FULLSCREEN, "视频");
jcVideoPlayer.startPlayLogic();
报错是这样的:
E/ExoPlayerImplInternal: Source error.
E/JieCaoVideoPlayer: onError -10000 - -10000 [782923114]
视频地址：
http://v.jiemian.com/25/d1/25d166c99cc70bdf3da03f4866f4188b_256.mp4
Html 页面播放没有问题。

**Comment by scar1et** [comment]
我也遇到了这个问题，请问一下是如何解决的呢？

**Comment by wujun19941207** [comment]
我上次发现的问题可能是播放存储的问题，我把作者的文件存储位置改了，导致的，我建议你先清空缓存，然后再尝试一下 @scar1et

**Comment by scar1et** [comment]
清除之后还是是没用。报错如下
E/ExoPlayerImplInternal: Source error.
                                                                               com.google.android.exoplayer2.source.ExtractorMediaSource$UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor) could read the stream.
                                                                                   at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractorHolder.selectExtractor(ExtractorMediaPeriod.java:678)
                                                                                   at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:602)
                                                                                   at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                                                   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                                   at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                   at java.lang.Thread.run(Thread.java:841)
E/JieCaoVideoPlayer: onError -10000 - -10000 [1119464088] 

我是没改过其他东西的。链接是m3u8的，是否exoplayer也不支持m3u8？

**Comment by wujun19941207** [comment]
你是必须播放 m3u8 的吗 
 如果不是 你可以尝试一下其他 的链接地址 比如：
 http://v.jiemian.com/25/d1/25d166c99cc70bdf3da03f4866f4188b_256.mp4
 http://v.jiemian.com/f4/69/f469ffa32dc8b55f0aa5929abeaba42a.mp4  等等，这是我的测试源 
 然后，关于exoPlayer 我没有尝试过 。
 如果是的话，建议问下其他人， 播放器就只有几种好用的，也可以尝试一下 ijkPlayer  或者 vitamio

**Comment by wujun19941207** [comment]
@scar1et

**Comment by scar1et** [comment]
需求要支持m3u8的，我再试试，实在不行我就换回4.8.3，或者看看其他的。谢谢了哦。
