### ISSUE TITLE
Can not remove surfaceview

### ISSUE THREAD

**Issue by lipangit** [lipangit/jiecaovideoplayer#62]
git checkout cannot_remove_surfaceview

In JCVideoPlayer.java  pay attention on line:206 and line 269.
Click fullscreen button then click back to quitfullscreen will crash.

E/AndroidRuntime: FATAL EXCEPTION: main
                                                                             Process: fm.jiecao.jiecaovideoplayer, PID: 26819
                                                                             java.lang.NullPointerException: Attempt to invoke interface method 'void android.view.IWindowSession.performDeferredDestroy(android.view.IWindow)' on a null object reference
                                                                                 at android.view.SurfaceView.updateWindow(SurfaceView.java:691)
                                                                                 at android.view.SurfaceView.onWindowVisibilityChanged(SurfaceView.java:287)
                                                                                 at android.view.View.dispatchWindowVisibilityChanged(View.java:8793)
                                                                                 at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1165)
                                                                                 at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1165)
                                                                                 at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1165)
                                                                                 at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1165)
                                                                                 at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1165)
                                                                                 at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1165)
                                                                                 at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1165)
                                                                                 at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1165)
                                                                                 at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1165)
                                                                                 at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1165)
                                                                                 at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1165)
                                                                                 at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1348)
                                                                                 at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1091)
                                                                                 at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5926)
                                                                                 at android.view.Choreographer$CallbackRecord.run(Choreographer.java:775)
                                                                                 at android.view.Choreographer.doCallbacks(Choreographer.java:588)
                                                                                 at android.view.Choreographer.doFrame(Choreographer.java:558)
                                                                                 at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:761)
                                                                                 at android.os.Handler.handleCallback(Handler.java:739)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                 at android.os.Looper.loop(Looper.java:135)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5273)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
05-01 22:52:36.738 26819-26819/fm.jiecao.jiecaovideoplayer I/Process: Sending signal. PID: 26819 SIG: 9

When quit fullscreen an go on play video , surface has release sometimes , then I will remove surfaceview and add a new surfaceview, but I can not remove surfacevew .
How to solve the problem.

**Comment by lipangit** [comment]
if surfaceview has been release ,then remove surfaceview ,every thing is ok.
if surfaceview is normal , then remove surfaceview , application will crash.
