### ISSUE TITLE
java.lang.ArithmeticException: divide by zero at fm.jiecao.jcvideoplayer_lib.JCResizeTextureView.onMeasure

### ISSUE THREAD

**Issue by lenmoyouziJiangjun** [lipangit/JieCaoVideoPlayer#648]
E/AndroidRuntime: FATAL EXCEPTION: main
                                                                            Process: com.mcttechnology.childfolio, PID: 4481
                                                                            java.lang.ArithmeticException: divide by zero
                                                                                at fm.jiecao.jcvideoplayer_lib.JCResizeTextureView.onMeasure(JCResizeTextureView.java:133)
                                                                                at android.view.View.measure(View.java:17547)
                                                                                at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
                                                                                at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
                                                                                at android.view.View.measure(View.java:17547)
                                                                                at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:727)
                                                                                at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:463)
                                                                                at android.view.View.measure(View.java:17547)
                                                                                at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.onMeasure(JCVideoPlayer.java:304)
                                                                                at android.view.View.measure(View.java:17547)
                                                                                at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
                                                                                at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
                                                                                at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
                                                                                at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
                                                                                at android.view.View.measure(View.java:17547)
                                                                                at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
                                                                                at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
                                                                                at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
                                                                                at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
                                                                                at android.view.View.measure(View.java:17547)
                                                                                at android.support.v7.widget.RecyclerView$LayoutManager.measureChildWithMargins(RecyclerView.java:8163)
                                                                                at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1471)
                                                                                at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1408)
                                                                                at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:580)
                                                                                at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3379)
                                                                                at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:2906)
                                                                                at android.view.View.measure(View.java:17547)
                                                                                at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:727)
                                                                                at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:463)
                                                                                at android.view.View.measure(View.java:17547)
                                                                                at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:727)
                                                                                at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:463)
                                                                                at android.view.View.measure(View.java:17547)
                                                                                at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1063)
                                                                                at android.widget.LinearLayout.onMeasure(LinearLayout.java:615)
                                                                                at android.view.View.measure(View.java:17547)
                                                                                at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
                                                                                at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
                                                                                at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
                                                                                at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
                                                                                at android.view.View.measure(View.java:17547)
                                                                                at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
                                                                                at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
                                                                                at android.view.View.measure(View.java:17547)
                                                                                at android.support.v4.widget.DrawerLayout.onMeasure(DrawerLayout.java:1081)
                                                                                at android.view.View.measure(View.java:17547)
                                                                                at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:727)
                                                                                at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:463)
                                                                                at android.view.View.measure(View.java:17547)
                                                                                at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
                                                                                at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
                                                                                at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
                                                                                at android.view.View.measure(View.java:17547)
                                                                                at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
                                                                                at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
                                                                                at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
                                                                                at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
                                                                                at android.view.View.measure(View.java:17547)
                                                                            	at

**Comment by lipangit** [comment]
哪个版本，应该判断一下的

**Comment by lipangit** [comment]
fix on 68786f3
