### ISSUE TITLE
播放结束后闪退，或者点击全屏，或者是暂停当前播放的视频，播放列表中的另一个时也闪退，帮我看看

### ISSUE THREAD

**Issue by tikeyc** [lipangit/JieCaoVideoPlayer#659]
播放完成报错：
FATAL EXCEPTION: main
                                                                         Process: com.tikeyc.mobileplayer, PID: 19571
                                                                         java.lang.NullPointerException: Attempt to invoke virtual method 'android.support.v7.app.ActionBar android.support.v7.app.AppCompatActivity.getSupportActionBar()' on a null object reference
                                                                             at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.showSupportActionBar(JCVideoPlayer.java:903)
                                                                             at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.clearFullscreenLayout(JCVideoPlayer.java:414)
                                                                             at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.onCompletion(JCVideoPlayer.java:442)
                                                                             at fm.jiecao.jcvideoplayer_lib.JCVideoPlayerStandard.onCompletion(JCVideoPlayerStandard.java:144)
                                                                             at fm.jiecao.jcvideoplayer_lib.JCVideoPlayerManager.completeAll(JCVideoPlayerManager.java:65)
                                                                             at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.onAutoCompletion(JCVideoPlayer.java:421)
                                                                             at fm.jiecao.jcvideoplayer_lib.JCMediaManager$2.run(JCMediaManager.java:168)
                                                                             at android.os.Handler.handleCallback(Handler.java:739)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                             at android.os.Looper.loop(Looper.java:145)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5942)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at java.lang.reflect.Method.invoke(Method.java:372)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
点击全屏报错：
FATAL EXCEPTION: main
                                                                         Process: com.tikeyc.mobileplayer, PID: 17163
                                                                         java.lang.NullPointerException: Attempt to invoke virtual method 'android.support.v7.app.ActionBar android.support.v7.app.AppCompatActivity.getSupportActionBar()' on a null object reference
                                                                             at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.hideSupportActionBar(JCVideoPlayer.java:889)
                                                                             at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.startWindowFullscreen(JCVideoPlayer.java:629)
                                                                             at fm.jiecao.jcvideoplayer_lib.JCVideoPlayerStandard.startWindowFullscreen(JCVideoPlayerStandard.java:326)
                                                                             at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.onClick(JCVideoPlayer.java:215)
                                                                             at fm.jiecao.jcvideoplayer_lib.JCVideoPlayerStandard.onClick(JCVideoPlayerStandard.java:186)
                                                                             at android.view.View.performClick(View.java:5184)
                                                                             at android.view.View$PerformClick.run(View.java:20893)
                                                                             at android.os.Handler.handleCallback(Handler.java:739)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                             at android.os.Looper.loop(Looper.java:145)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5942)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at java.lang.reflect.Method.invoke(Method.java:372)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)

**Comment by lipangit** [comment]
包含视频的activity都要继承appCompactActiity
