### ISSUE TITLE
V5.3 java.lang.IllegalStateException

### ISSUE THREAD

**Issue by Weststreet** [lipangit/JieCaoVideoPlayer#671]
java.lang.IllegalStateException
	at android.media.MediaPlayer.seekTo(Native Method)
	at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.onTouch(TbsSdkJava:273)
	at fm.jiecao.jcvideoplayer_lib.JCVideoPlayerStandard.onTouch(TbsSdkJava:174)
	at android.view.View.dispatchTouchEvent(View.java:8666)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2517)

**Comment by lipangit** [comment]
MediaPlayer被release了，你这里在seek进度条的时候具体情况是怎样的？

**Comment by Weststreet** [comment]
@lipangit 我也模拟不出来，友盟统计到的，也有用户反馈这个问题。
