### ISSUE TITLE
5.4不支持m3u8格式的url吗？用官方demo播放m3u8格式都无法播放。

### ISSUE THREAD

**Issue by scar1et** [lipangit/JieCaoVideoPlayer#676]

**Comment by scar1et** [comment]
02-13 10:18:40.050 23533-23533/fm.jiecao.jiecaovideoplayer I/JieCaoVideoPlayer: onSurfaceTextureAvailable [1106287480] 
02-13 10:18:40.052 23533-23533/fm.jiecao.jiecaovideoplayer D/OpenGLRenderer: prepareDirty (0.00, 0.00, 720.00, 1280.00) opaque 1 <0x6183d618>
02-13 10:18:40.055 23533-23533/fm.jiecao.jiecaovideoplayer D/OpenGLRenderer: finish <0x6183d618>
02-13 10:18:40.057 23533-23745/fm.jiecao.jiecaovideoplayer E/MediaPlayer: error (-38, 0)
02-13 10:18:40.058 23533-23745/fm.jiecao.jiecaovideoplayer W/MediaPlayer: setScreenOnWhilePlaying(true) is ineffective without a SurfaceHolder
02-13 10:18:40.058 23533-23745/fm.jiecao.jiecaovideoplayer E/MediaPlayer: prepareAsync called in state 0
02-13 10:18:40.059 23533-23745/fm.jiecao.jiecaovideoplayer W/System.err: java.lang.IllegalStateException
02-13 10:18:40.059 23533-23745/fm.jiecao.jiecaovideoplayer W/System.err:     at android.media.MediaPlayer.prepareAsync(Native Method)
02-13 10:18:40.059 23533-23745/fm.jiecao.jiecaovideoplayer W/System.err:     at fm.jiecao.jcvideoplayer_lib.JCMediaManager$MediaHandler.handleMessage(JCMediaManager.java:93)
02-13 10:18:40.060 23533-23745/fm.jiecao.jiecaovideoplayer W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:110)
02-13 10:18:40.060 23533-23745/fm.jiecao.jiecaovideoplayer W/System.err:     at android.os.Looper.loop(Looper.java:193)
02-13 10:18:40.060 23533-23745/fm.jiecao.jiecaovideoplayer W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:61)
02-13 10:18:40.061 23533-23745/fm.jiecao.jiecaovideoplayer D/MediaPlayer: handleMessage msg:(100, -38, 0)
02-13 10:18:40.061 23533-23745/fm.jiecao.jiecaovideoplayer E/MediaPlayer: Error (-38,0)
02-13 10:18:40.062 23533-23533/fm.jiecao.jiecaovideoplayer D/DisplayEventReceiver: rev(0x5bed7770) w/ vsync, t=17469913202158, id=0, c=559115
02-13 10:18:40.064 23533-23533/fm.jiecao.jiecaovideoplayer D/OpenGLRenderer: prepareDirty (0.00, 0.00, 720.00, 1280.00) opaque 1 <0x6183d618>
02-13 10:18:40.067 23533-23533/fm.jiecao.jiecaovideoplayer D/OpenGLRenderer: finish <0x6183d618>
02-13 10:18:40.069 23533-23533/fm.jiecao.jiecaovideoplayer D/DisplayEventReceiver: rev(0x5bed7770) w/ vsync, t=17469923008781, id=0, c=559116
02-13 10:18:40.069 23533-23533/fm.jiecao.jiecaovideoplayer E/JieCaoVideoPlayer: onError -38 - 0 [1106524056]

**Comment by scar1et** [comment]
如果想要支持的话，应该怎么操作，您有什么好的建议吗？

**Comment by lipangit** [comment]
![a8778d19-a5d3-4d73-be1c-2d52ec695449](https://cloud.githubusercontent.com/assets/2038071/22875784/7ebbf2f4-f208-11e6-9f78-cbabeefd5574.png)

**Comment by scar1et** [comment]
是bug？我在项目没找到截图的链接。

**Comment by lipangit** [comment]
这个链接都是exoplayer官方demo里的链接，我测试了一下，5.4版本m3u8有的能用有的不能用，我再仔细研究一下区别，我对使用系统MediaPlayer也纠结

**Comment by scar1et** [comment]
好的，大神辛苦了

**Comment by scar1et** [comment]
@lipangit 
我换成v5.2.1
使用v5.2.1播放m3u8报错：
02-14 09:32:38.876 7240-17943/fm.jiecao.jiecaovideoplayer E/ExoPlayerImplInternal: Source error.
                                                                                   com.google.android.exoplayer2.source.ExtractorMediaSource$UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor) could read the stream.
                                                                                       at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractorHolder.selectExtractor(ExtractorMediaPeriod.java:678)
                                                                                       at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:602)
                                                                                       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                                                       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                       at java.lang.Thread.run(Thread.java:841)
02-14 09:32:38.876 7240-7240/fm.jiecao.jiecaovideoplayer E/JieCaoVideoPlayer: onError -10000 - -10000 [1117767912]

**Comment by scar1et** [comment]
但是播放Demo内的m3u8也是正常的。

附上测试链接
http://www.ifishing8.com/commons/attachment/video/109968/m3u8
