### ISSUE TITLE
在RecyclerView 中使用 JCVideoPlayerStandard.startFullscreen

### ISSUE THREAD

**Issue by CodeToxicant** [lipangit/JieCaoVideoPlayer#689]
第一次点击没有问题 可以正常播放
java.lang.IllegalStateException
                                                            at android.media.MediaPlayer.isPlaying(Native Method)
                                                            at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer$1.onAudioFocusChange(JCVideoPlayer.java:740)
                                                            at android.media.AudioManager$ServiceEventHandlerDelegate$1.handleMessage(AudioManager.java:2364)
                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                            at android.os.Looper.loop(Looper.java:156)
                                                            at android.app.ActivityThread.main(ActivityThread.java:6524)
                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)

点击返回按钮以后在进行播放列表中的视频出现

**Comment by lipangit** [comment]
用新版试试，这块try catch住了。

onAudioFocusChange 是手机上有其他声音播放的消息

**Comment by tangnuo** [comment]
v5.5.4还是有这个问题：

07-07 15:14:56.128 25183-25183/com.jsfengling.qipai W/System.err: java.lang.IllegalStateException
07-07 15:14:56.128 25183-25183/com.jsfengling.qipai W/System.err:     at android.media.MediaPlayer.isPlaying(Native Method)
07-07 15:14:56.128 25183-25183/com.jsfengling.qipai W/System.err:     at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer$1.onAudioFocusChange(JCVideoPlayer.java:777)
07-07 15:14:56.128 25183-25183/com.jsfengling.qipai W/System.err:     at android.media.AudioManager$FocusEventHandlerDelegate$1.handleMessage(AudioManager.java:2018)
07-07 15:14:56.128 25183-25183/com.jsfengling.qipai W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
07-07 15:14:56.128 25183-25183/com.jsfengling.qipai W/System.err:     at android.os.Looper.loop(Looper.java:136)
07-07 15:14:56.128 25183-25183/com.jsfengling.qipai W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5052)
07-07 15:14:56.128 25183-25183/com.jsfengling.qipai W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
07-07 15:14:56.128 25183-25183/com.jsfengling.qipai W/System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
07-07 15:14:56.128 25183-25183/com.jsfengling.qipai W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796)
07-07 15:14:56.128 25183-25183/com.jsfengling.qipai W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612)
07-07 15:14:56.128 25183-25183/com.jsfengling.qipai W/System.err:     at dalvik.system.NativeStart.main(Native Method)
