### ISSUE TITLE
全屏崩溃..

### ISSUE THREAD

**Issue by yuxinLi** [lipangit/JieCaoVideoPlayer#706]
Vivo Y17W
android 4.2.2
全屏的时候 崩溃

FATAL EXCEPTION: main
                                                                          java.lang.RuntimeException: Error during detachFromGLContext (see logcat for details)
                                                                              at android.graphics.SurfaceTexture.attachToGLContext(SurfaceTexture.java:237)
                                                                              at android.view.GLES20TextureLayer.setSurfaceTexture(GLES20TextureLayer.java:81)
                                                                              at android.view.HardwareRenderer$Gl20Renderer.setSurfaceTexture(HardwareRenderer.java:1576)
                                                                              at android.view.TextureView.getHardwareLayer(TextureView.java:393)
                                                                              at android.view.View.getDisplayList(View.java:12731)
                                                                              at android.view.View.getDisplayList(View.java:12806)
                                                                              at android.view.View.draw(View.java:13540)
                                                                              at android.view.ViewGroup.drawChild(ViewGroup.java:3022)
                                                                              at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2886)
                                                                              at android.view.View.getDisplayList(View.java:12760)
                                                                              at android.view.View.getDisplayList(View.java:12806)
                                                                              at android.view.View.draw(View.java:13540)
                                                                              at android.view.ViewGroup.drawChild(ViewGroup.java:3022)
                                                                              at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2886)
                                                                              at android.view.View.draw(View.java:13835)
                                                                              at android.view.View.getDisplayList(View.java:12762)
                                                                              at android.view.View.getDisplayList(View.java:12806)
                                                                              at android.view.View.draw(View.java:13540)
                                                                              at android.view.ViewGroup.drawChild(ViewGroup.java:3022)
                                                                              at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2886)
                                                                              at android.view.View.getDisplayList(View.java:12760)
                                                                              at android.view.View.getDisplayList(View.java:12806)
                                                                              at android.view.View.draw(View.java:13540)
                                                                              at android.view.ViewGroup.drawChild(ViewGroup.java:3022)
                                                                              at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2886)
                                                                              at android.view.View.draw(View.java:13835)
                                                                              at android.widget.FrameLayout.draw(FrameLayout.java:467)
                                                                              at android.view.View.getDisplayList(View.java:12762)
                                                                              at android.view.View.getDisplayList(View.java:12806)
                                                                              at android.view.View.draw(View.java:13540)
                                                                              at android.view.ViewGroup.drawChild(ViewGroup.java:3022)
                                                                              at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2886)
                                                                              at android.view.View.getDisplayList(View.java:12760)
                                                                              at android.view.View.getDisplayList(View.java:12806)
                                                                              at android.view.View.draw(View.java:13540)
                                                                              at android.view.ViewGroup.drawChild(ViewGroup.java:3022)
                                                                              at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2886)
                                                                              at android.view.View.getDisplayList(View.java:12760)
                                                                              at android.view.View.getDisplayList(View.java:12806)
                                                                              at android.view.View.draw(View.java:13540)
                                                                              at android.view.ViewGroup.drawChild(ViewGroup.java:3022)
                                                                              at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2886)
                                                                              at android.view.View.getDisplayList(View.java:12760)
                                                                              at android.view.View.getDisplayList(View.java:12806)
                                                                              at android.view.View.draw(View.java:13540)
                                                                              at android.view.ViewGroup.drawChild(ViewGroup.java:3022)
                                                                              at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2886)
                                                                              at android.view.View.draw(View.java:13835)
                                                                              at android.widget.FrameLayout.draw(FrameLayout.java:467)
                                                                              at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2238)
                                                                              at android.view.View.getDisplayList(View.java:12762)
                                                                              at android.view.View.getDisplayList(View.java:12806)
                                                                              at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1249)
                                                                              at android.view.ViewRootImpl.draw(ViewRootImpl.java:2541)
                                                                              at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2408)
                                                                              at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2206)
                                                                              at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1194)
                                                                              at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5002)
                                                                              at android.view.Choreographer$CallbackRecord.run(Choreographer.java:776)
                                                                              at android.view.Choreographer.doCallbacks(Choreographer.java:579)
                                                                              at android.view.Choreographer.doFrame(Choreographer.java:548)
                                                                              at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:762)
                                                                              at android.os.Handler.handleCallback(Handler.java:800)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:100)
                                                                              at android.os.Looper.loop(Looper.java:194)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5407)
                                                                              at java.lang.reflect.Method.invokeNative(Native Method)
                                                                          	at java.lang.reflect.Method.invoke(

**Comment by yuxinLi** [comment]
try {
            super.startWindowFullscreen();
        }catch (Exception e){
            if (JCVideoPlayerManager.getSecondFloor() != null){
                JCVideoPlayerManager.getSecondFloor().backPress();
            }
        }

这样catch不到， 好像是绘制的时候有问题，需要在哪里catch一下？

**Comment by lipangit** [comment]
jcvd哪个版本，改库了吗，demo有这个问题吗

**Comment by yuxinLi** [comment]
jiecaovideoplayer-5.5.apk
  测了一下，只有 首页 PLAY DIRECTLY WITHOUT LAYOUT --> FULLSCREEN  这个视频不会崩溃

其他路径下的视频，如果一开始不是全屏，点击全屏的时候就挂了

**Comment by tyx627** [comment]
华为G750-T01 android4.2.2  也是点击全屏就崩溃，报错信息和上面一样
12-05 11:26:40.660 25487-25487/com.moni.perinatal E/crash_callback: exceptionMessage:java.lang.RuntimeException: Error during detachFromGLContext (see logcat for details)
                                                                        at android.graphics.SurfaceTexture.attachToGLContext(SurfaceTexture.java:237)
                                                                        at android.view.GLES20TextureLayer.setSurfaceTexture(GLES20TextureLayer.java:81)
                                                                        at android.view.HardwareRenderer$Gl20Renderer.setSurfaceTexture(HardwareRenderer.java:1583)
                                                                        at android.view.TextureView.getHardwareLayer(TextureView.java:393)
                                                                        at android.view.View.getDisplayList(View.java:12865)
                                                                        at android.view.View.getDisplayList(View.java:12951)
                                                                        at android.view.View.draw(View.java:13708)
                                                                        at android.view.ViewGroup.drawChild(ViewGroup.java:3083)
                                                                        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2931)
                                                                        at android.view.View.getDisplayList(View.java:12897)
                                                                        at android.view.View.getDisplayList(View.java:12951)
                                                                        at android.view.View.draw(View.java:13708)
                                                                        at android.view.ViewGroup.drawChild(ViewGroup.java:3083)
                                                                        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2931)
                                                                        at android.view.View.draw(View.java:14018)
                                                                        at android.view.View.getDisplayList(View.java:12902)
                                                                        at android.view.View.getDisplayList(View.java:12951)
                                                                        at android.view.View.draw(View.java:13708)
                                                                        at android.view.ViewGroup.drawChild(ViewGroup.java:3083)
                                                                        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2931)
                                                                        at android.view.View.getDisplayList(View.java:12897)
                                                                        at android.view.View.getDisplayList(View.java:12951)
                                                                        at android.view.View.draw(View.java:13708)
                                                                        at android.view.ViewGroup.drawChild(ViewGroup.java:3083)
                                                                        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2931)
                                                                        at android.view.View.draw(View.java:14018)
                                                                        at android.widget.FrameLayout.draw(FrameLayout.java:526)
                                                                        at android.view.View.getDisplayList(View.java:12902)
                                                                        at android.view.View.getDisplayList(View.java:12951)
                                                                        at android.view.View.draw(View.java:13708)
                                                                        at android.view.ViewGroup.drawChild(ViewGroup.java:3083)
                                                                        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2931)
                                                                        at android.view.View.getDisplayList(View.java:12897)
                                                                        at android.view.View.getDisplayList(View.java:12951)
                                                                        at android.view.View.draw(View.java:13708)
                                                                        at android.view.ViewGroup.drawChild(ViewGroup.java:3083)
                                                                        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2931)
                                                                        at android.view.View.getDisplayList(View.java:12897)
                                                                        at android.view.View.getDisplayList(View.java:12951)
                                                                        at android.view.View.draw(View.java:13708)
                                                                        at android.view.ViewGroup.drawChild(ViewGroup.java:3083)
                                                                        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2931)
                                                                        at android.view.View.getDisplayList(View.java:12897)
                                                                        at android.view.View.getDisplayList(View.java:12951)
                                                                        at android.view.View.draw(View.java:13708)
                                                                        at android.view.ViewGroup.drawChild(ViewGroup.java:3083)
                                                                        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2931)
                                                                        at android.view.View.draw(View.java:14018)
                                                                        at android.widget.FrameLayout.draw(FrameLayout.java:526)
                                                                        at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2268)
                                                                        at android.view.View.getDisplayList(View.java:12902)
                                                                        at android.view.View.getDisplayList(View.java:12951)
                                                                        at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1256)
                                                                        at android.view.ViewRootImpl.draw(ViewRootImpl.java:2583)
                                                                        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2448)
                                                                        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2250)
                                                                        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1223)
                                                                        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5062)
                                                                        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:776)
                                                                        at android.view.Choreographer.doCallbacks(Choreographer.java:579)
                                                                        at android.view.Choreographer.doFrame(Choreographer.java:548)
                                                                        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:762)
                                                                        at android.os.Handler.handleCallback(Handler.java:800)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:100)
                                                                        at android.os.Looper.loop(Looper.java:194)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5468)
                                                                        at java.lang.reflect.Method.invokeNative(Native Method)
                                                                    	at java.lang.reflect.Method.invoke(Metho
12-05 11:26:40.661 25487-25487/com.moni.perinatal E/crash_callback: cause:Error during detachFromGLContext (see logcat for details)
12-05 11:26:40.661 25487-25487/com.moni.perinatal E/crash_callback: exceptionClassName:java.lang.RuntimeException
12-05 11:26:40.661 25487-25487/com.moni.perinatal E/crash_callback: throwClassName:android.graphics.SurfaceTexture
12-05 11:26:40.661 25487-25487/com.moni.perinatal E/crash_callback: throwMethodName:attachToGLContext
12-05 11:26:40.661 25487-25487/com.moni.perinatal E/crash_callback: throwLineNumber:237
