### ISSUE TITLE
竖屏可以播放 但是点击全屏按钮报空指针错误

### ISSUE THREAD

**Issue by NutBear** [lipangit/JieCaoVideoPlayer#709]
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.xiaoxiakj, PID: 3346
                  java.lang.NullPointerException: Attempt to invoke virtual method 'android.support.v7.app.ActionBar android.support.v7.app.AppCompatActivity.getSupportActionBar()' on a null object reference
                      at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.hideSupportActionBar(JCVideoPlayer.java:864)
                      at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.startWindowFullscreen(JCVideoPlayer.java:638)
                      at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.onClick(JCVideoPlayer.java:190)
                      at fm.jiecao.jcvideoplayer_lib.JCVideoPlayerStandard.onClick(JCVideoPlayerStandard.java:176)
                      at android.view.View.performClick(View.java:5610)
                      at android.view.View$PerformClick.run(View.java:22265)
                      at android.os.Handler.handleCallback(Handler.java:751)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6077)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by lipangit** [comment]
包含视频的activity继承AppCompactactivity，activity总要继承一个activity，那么就继承AppCompactactivity

**Comment by NutBear** [comment]
@lipangit 好的 我试试

**Comment by bocaitang** [comment]
解决了么，亲
