### ISSUE TITLE
Fragment 使用报空指针

### ISSUE THREAD

**Issue by qqtanwei** [lipangit/JieCaoVideoPlayer#738]
java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.Window android.app.Activity.getWindow()' on a null object reference
                                                       at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.prepareVideo(JCVideoPlayer.java:255)
                                                       at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.onClick(JCVideoPlayer.java:213)
                                                       at fm.jiecao.jcvideoplayer_lib.JCVideoPlayerStandard.onClick(JCVideoPlayerStandard.java:168)
                                                       at android.view.View.performClick(View.java:5204)
                                                       at android.view.View$PerformClick.run(View.java:21153)
                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:148)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by lipangit** [comment]
我记得我遇到过这个log

应该是调试退出全屏时候出现的，断点releaseAllVideos()函数，判断什么时候release的MediaPlayer，应该有所帮助

至于这个log怎么来的，为什么releaseMediaPlayer会导致这个原因，现在还不清楚

**Comment by lichafeng** [comment]
java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.Window android.app.Activity.getWindow()' on a null object reference
                                                                     at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.prepareMediaPlayer(JCVideoPlayer.java:204)
                                                                     at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.onClick(JCVideoPlayer.java:165)
                                                                     at fm.jiecao.jcvideoplayer_lib.JCVideoPlayerStandard.onClick(JCVideoPlayerStandard.java:176)
                                                                     at android.view.View.performClick(View.java:5205)
                                                                     at android.view.View$PerformClick.run(View.java:21164)
                                                                     at android.os.Handler.handleCallback(Handler.java:743)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                     at android.os.Looper.loop(Looper.java:148)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5440)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)  我点击在Fragment点击视频就报这个错  怎么解决 谢谢!

**Comment by lipangit** [comment]
点击视频是点击全屏按钮还是点开始按钮，出现这个log断点一下releaseAllVideos，有执行这个函数吗

**Comment by lichafeng** [comment]
我点击开始就burg 断点没有执行releaseAllVideos
![z_vvt3 tz 5_yv6 g8 x5z1](https://cloud.githubusercontent.com/assets/20775420/24483950/10c66290-152e-11e7-9571-9f361e30f867.png)

**Comment by lipangit** [comment]
context.getWindow好像有问题，你试试你的代码里能不能直接调用
