### ISSUE TITLE
在demo里的recycleview里把进度条滑动到最后会报空指针

### ISSUE THREAD

**Issue by qq574259582** [lipangit/JieCaoVideoPlayer#749]
Process: fm.jiecao.jiecaovideoplayer, PID: 15232
                                                                             java.lang.NullPointerException: Attempt to invoke virtual method 'void fm.jiecao.jcvideoplayer_lib.JCResizeTextureView.setVideoSize(android.graphics.Point)' on a null object reference
                                                                                 at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.onVideoSizeChanged(JCVideoPlayer.java:578)
                                                                                 at fm.jiecao.jcvideoplayer_lib.JCMediaManager$7.run(JCMediaManager.java:228)
                                                                                 at android.os.Handler.handleCallback(Handler.java:739)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                 at android.os.Looper.loop(Looper.java:135)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5430)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:913)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:706)

**Comment by lipangit** [comment]
这没遇到过，demo里应该不好复现。
哪个是null 是textureView吗

**Comment by qq574259582** [comment]
嗯嗯 对是textureView，5.1的系统

**Comment by lipangit** [comment]
断点一下这时候是不是走onComplete了，把TextureView设成null了
