### ISSUE TITLE
小米手机4.4系统全屏就闪退（必现）

### ISSUE THREAD

**Issue by qq574259582** [lipangit/JieCaoVideoPlayer#750]
03-20 16:27:57.957 26057-26057/com.didi365.mmzt.client E/MDP: DpIonHandler: flush addr 17 ms
03-20 16:28:03.775 26057-26057/com.didi365.mmzt.client E/SurfaceTexture: [unnamed-26057-0](this:0x5eaa4208,api:3) error creating EGLImage: 0x3003
03-20 16:28:03.821 26057-26057/com.didi365.mmzt.client E/AndroidRuntime: FATAL EXCEPTION: main
                                                                         java.lang.RuntimeException: Error during detachFromGLContext (see logcat for details)
                                                                             at android.graphics.SurfaceTexture.attachToGLContext(SurfaceTexture.java:237)
                                                                             at android.view.GLES20TextureLayer.setSurfaceTexture(GLES20TextureLayer.java:81)
                                                                             at android.view.HardwareRenderer$Gl20Renderer.setSurfaceTexture(HardwareRenderer.java:1576)
                                                                             at android.view.TextureView.getHardwareLayer(TextureView.java:393)
                                                                             at android.view.View.getDisplayList(View.java:12916)
                                                                             at android.view.View.getDisplayList(View.java:12997)
                                                                             at android.view.View.draw(View.java:13742)
                                                                             at android.view.ViewGroup.drawChild(ViewGroup.java:3154)
                                                                             at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3018)
                                                                             at android.view.View.getDisplayList(View.java:12948)
                                                                             at android.view.View.getDisplayList(View.java:12997)
                                                                             at android.view.View.draw(View.java:13742)
                                                                             at android.view.ViewGroup.drawChild(ViewGroup.java:3154)
                                                                             at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3018)
                                                                             at android.view.View.draw(View.java:14049)
                                                                             at android.view.View.getDisplayList(View.java:12953)
                                                                             at android.view.View.getDisplayList(View.java:12997)
                                                                             at android.view.View.draw(View.java:13742)
                                                                             at android.view.ViewGroup.drawChild(ViewGroup.java:3154)
                                                                             at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3018)
                                                                             at android.view.View.getDisplayList(View.java:12948)
                                                                             at android.view.View.getDisplayList(View.java:12997)
                                                                             at android.view.View.draw(View.java:13742)
                                                                             at android.view.ViewGroup.drawChild(ViewGroup.java:3154)
                                                                             at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3018)
                                                                             at android.view.View.draw(View.java:14049)
                                                                             at android.widget.FrameLayout.draw(FrameLayout.java:467)
                                                                             at android.view.View.getDisplayList(View.java:12953)
                                                                             at android.view.View.getDisplayList(View.java:12997)
                                                                             at android.view.View.draw(View.java:13742)
                                                                             at android.view.ViewGroup.drawChild(ViewGroup.java:3154)
                                                                             at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3018)
                                                                             at android.view.View.getDisplayList(View.java:12948)
                                                                             at android.view.View.getDisplayList(View.java:12997)
                                                                             at android.view.View.draw(View.java:13742)
                                                                             at android.view.ViewGroup.drawChild(ViewGroup.java:3154)
                                                                             at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3018)
                                                                             at android.view.View.getDisplayList(View.java:12948)
                                                                             at android.view.View.getDisplayList(View.java:12997)
                                                                             at android.view.View.draw(View.java:13742)
                                                                             at android.view.ViewGroup.drawChild(ViewGroup.java:3154)
                                                                             at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3018)
                                                                             at android.view.View.getDisplayList(View.java:12948)
                                                                             at android.view.View.getDisplayList(View.java:12997)
                                                                             at android.view.View.draw(View.java:13742)
                                                                             at android.view.ViewGroup.drawChild(ViewGroup.java:3154)
                                                                             at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3018)
                                                                             at android.view.View.draw(View.java:14049)
                                                                             at android.widget.FrameLayout.draw(FrameLayout.java:467)
                                                                             at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2333)
                                                                             at android.view.View.getDisplayList(View.java:12953)
                                                                             at android.view.View.getDisplayList(View.java:12997)
                                                                             at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1249)
                                                                             at android.view.ViewRootImpl.draw(ViewRootImpl.java:2585)
                                                                             at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2452)
                                                                             at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2254)
                                                                             at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1246)
                                                                             at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5014)
                                                                             at android.view.Choreographer$CallbackRecord.run(Choreographer.java:776)
                                                                             at android.view.Choreographer.doCallbacks(Choreographer.java:579)
                                                                             at android.view.Choreographer.doFrame(Choreographer.java:548)
                                                                             at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:762)
                                                                             at android.os.Handler.handleCallback(Handler.java:800)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:100)
                                                                             at android.os.Looper.loop(Looper.java:194)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5433)
                                                                             at java.lang.reflect.Method.invokeNative(Native Method)
                                                                         	at java.lang.reflect.Method.invoke(

**Comment by qq574259582** [comment]
必现

**Comment by qq574259582** [comment]
是最新版本5.5.2的

**Comment by lipangit** [comment]
这应该是系统的坑，保持关注中，暂时没办法

**Comment by yingzi2011** [comment]
我是遇到这个问题，大部分在4.2 这个 手机上，不是必现，但是不知道怎么去修改
