### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by icefly118** [lipangit/JieCaoVideoPlayer#753]
at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.onVideoSizeChanged(JCVideoPlayer.java:578);
全屏模式(横屏)下视频播放完成后,返回正常模式时报以上错误;
  1. 初步分析是视频播放完成后回调了JCVideoPlayer 的onCompletion()方法将 JCMediaManager.textureView 设置为空,
 2. 而后又回调了JCVideoPlayer的onVideoSizeChanged(), 在其中调用JCMediaManager.textureView.setVideoSize(point);

通过在调用JCMediaManager.textureView.setVideoSize(point)之前,先判断textureView 是否为空可避免该问题, 但是修改后视频全屏状态下无法播放完整个视频就跳回正常播放模式了.

请问该怎么解决? 谢谢!

**Comment by lipangit** [comment]
当时是什么情况，全屏模式下已经播放完了，为什么还会调onVideoSizeChanged()这个函数呢

**Comment by icefly118** [comment]
全屏模式播放完了,会自动切回半屏模式,此时是系统自动回调了onVideoSizeChanged()这个函数(通过Log日志确认的), 而非手动回调
我也没搞清楚播放完了为什么还会回调该函数?

**Comment by lipangit** [comment]
你说的‘自动切回半屏模式’是播放结束对不对？
onVideoSizeChanged这个函数是MediaPlayer回调调用的，一般在视频准备完成开始播放的时候，能拿到视频的高宽，demo里不记得有这个问题，改库了吗，改了什么其他逻辑了吗

**Comment by icefly118** [comment]
demo中只更改了2处:
1. 依赖库
compile 'com.android.support:appcompat-v7:25.3.0' 
==>
compile 'com.android.support:appcompat-v7:25.0.0'

2. 视频源采用了本地视频
注: 刚刚Download最新的Demo测试的

**Comment by lipangit** [comment]
这个修改没问题。
你说的‘自动切回半屏模式’是播放结束对不对？

**Comment by icefly118** [comment]
是的,
过程如下:
启动Demo-->播放Demo首页视频-->手动点击全屏按钮,进入全屏播放模式-->全屏播放完视频后-->程序崩溃,异常信息如下:
fm.jiecao.jiecaovideoplayer E/AndroidRuntime: FATAL EXCEPTION: main
                                                                             Process: fm.jiecao.jiecaovideoplayer, PID: 25915
                                                                             java.lang.NullPointerException
      at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.onVideoSizeChanged(JCVideoPlayer.java:578)
      at fm.jiecao.jcvideoplayer_lib.JCMediaManager$7.run(JCMediaManager.java:228)
      at android.os.Handler.handleCallback(Handler.java:733)
      at android.os.Handler.dispatchMessage(Handler.java:95)
      at android.os.Looper.loop(Looper.java:136)
     at android.app.ActivityThread.main(ActivityThread.java:5017)
     at java.lang.reflect.Method.invokeNative(Native Method)
     at java.lang.reflect.Method.invoke(Method.java:515)
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:813)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)
      at dalvik.system.NativeStart.main(Native Method)

**Comment by icefly118** [comment]
个人分析:
全屏模式下视频播放完成==>
JCMediaManager.onCompletion()==>
JCVideoPlayer.onAutoCompletion()==>
JCVideoPlayer.backPress()==>
JCVideoPlayer.playOnThisJcvd()==>
JCVideoPlayer.addTextureView()==>
JCVideoPlayer.textureViewContainer.addView(JCMediaManager.textureView, layoutParams)==>
回到JCVideoPlayer.onAutoCompletion() 执行剩下的代码,包括**JCMediaManager.textureView = null;** ==>
当回到半屏模式且TextureView onAttach到 半屏模式下的容器中后,回调
JCMediaManager.onSurfaceTextureAvailable(SurfaceTexture  surfaceTexture, int i, int i1)方法,
并执行里面的prepare(), 发送Handler消息,重新准备MediaPlayer==>
MediaPlayer 准备OK后回调 JCMediaManager.onVideoSizeChanged()函数==>
JCVideoPlayer.onVideoSIzeChanged()函数, 并在其中执行JCMediaManager.textureView.setVideoSize(), 而此时**JCMediaManager.textureView**已被置空...

**Comment by lipangit** [comment]
这问题有点严重，我需要调试研究一下

**Comment by Noshad22** [comment]
i debug it and i fail to solve the problem but i know the reason when and how it this problem arise @lipangit  plz help me

**Comment by Noshad22** [comment]
just play one of your video from mobile phone not on live stream and seek that video to the end point when the video near to the finishing point it will crash when you are on fullscreen mode.

**Comment by Noshad22** [comment]
JCMediaManager.textureView
.setVideoSize(JCMediaManager.instance()
.getVideoSize());  <-------------------- null pointer exception
............................................................................

public Point getVideoSize() {
        if (currentVideoWidth != 0 && currentVideoHeight != 0) {
            return new Point(currentVideoWidth, currentVideoHeight);
        } else {
            return null;
        }
    }

getVideoSize returning the null point..............

**Comment by Noshad22** [comment]
here is the screen shot

![image](https://cloud.githubusercontent.com/assets/6240620/24655133/5f8c0782-1956-11e7-8fff-61765b004f3b.png)

**Comment by Noshad22** [comment]
after 3 hour of struggle finally i solved the issue 
in abstract class JCVideoPlayer i found the method onAutoCompletion where i comment these objects

 //       JCMediaManager.textureView = null;
//        JCMediaManager.savedSurfaceTexture = null;

here is the screenshot
![image](https://cloud.githubusercontent.com/assets/6240620/24659245/923f3500-1965-11e7-8dd9-e7f1ae810e17.png)

**Comment by lipangit** [comment]
@Noshad22  This bug is more than one mentioned，but did not occur on my phone, I will always focuse on it .

**Comment by kris-liutao** [comment]
@Noshad22  你好呀  我现在遇到的问题和你的差不多  先判断textureView 是否为空也解决不了呢 你是怎么解决的

**Comment by Noshad22** [comment]
@kris-liutao  kindly take a look at my last comment with concentration plz i explain the solution with screen shot.

**Comment by kris-liutao** [comment]
Thank you ever so much! @Noshad22

**Comment by daitu-liang** [comment]
在recycleview中，先点击item播放视频，播完结束后，再滑动列表，进行播放，播放结束，报下错误；
 java.lang.NullPointerException: Attempt to invoke virtual method 'void fm.jiecao.jcvideoplayer_lib.JCResizeTextureView.setVideoSize(android.graphics.Point)' on a null object reference
                                                                                  at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.onVideoSizeChanged(JCVideoPlayer.java:578)
                                                                                  at fm.jiecao.jcvideoplayer_lib.JCMediaManager$7.run(JCMediaManager.java:228)
                                                                                  at android.os.Handler.handleCallback(Handler.java:815)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                                  at android.os.Looper.loop(Looper.java:207)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5917)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)

**Comment by lipangit** [comment]
下版本修改@daitu-liang
