### ISSUE TITLE
Video not playing in older android versions

### ISSUE THREAD

**Issue by pathanjalisrinivasan** [lipangit/JieCaoVideoPlayer#754]
I could able to play perfectly from Lollipop version but in older version when i tried to play, the video keeps buffering and is throwing me the following Log: 

```
E/MediaPlayer-JNI: QCMediaPlayer mediaplayer NOT present
E/MediaPlayer: error (-38, 0)
W/MediaPlayer: setScreenOnWhilePlaying(true) is ineffective without a SurfaceHolder
E/MediaPlayer: prepareAsync called in state 0
W/System.err: java.lang.IllegalStateException
W/System.err:     at android.media.MediaPlayer.prepareAsync(Native Method)
W/System.err:     at fm.jiecao.jcvideoplayer_lib.JCMediaManager$MediaHandler.handleMessage(JCMediaManager.java:93)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err:     at android.os.Looper.loop(Looper.java:136)
W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:61)
E/MediaPlayer: Error (-38,0)
E/JieCaoVideoPlayer: onError -38 - 0 [1174932672]
```

**Comment by lipangit** [comment]
yes the minSdkVersion is 16, can not work well before SdkVersion 16.

**Comment by ijntvwh** [comment]
在api19的真机上也有这个问题...

**Comment by lipangit** [comment]
保持关注
