### ISSUE TITLE
我使用的5.5.2版本的，但是点击全屏的时候闪退了，我的activity父类没有继承AppCompatActivity这个怎么解决啊

### ISSUE THREAD

**Issue by kris-liutao** [lipangit/JieCaoVideoPlayer#773]
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.zontonec.ztgarden, PID: 27388
                  java.lang.NullPointerException: Attempt to invoke virtual method 'android.support.v7.app.ActionBar android.support.v7.app.AppCompatActivity.getSupportActionBar()' on a null object reference
                      at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.hideSupportActionBar(JCVideoPlayer.java:864)
                      at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.startWindowFullscreen(JCVideoPlayer.java:638)
                      at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.onClick(JCVideoPlayer.java:190)
                      at fm.jiecao.jcvideoplayer_lib.JCVideoPlayerStandard.onClick(JCVideoPlayerStandard.java:176)
                      at android.view.View.performClick(View.java:5210)
                      at android.view.View$PerformClick.run(View.java:20976)
                      at android.os.Handler.handleCallback(Handler.java:739)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:145)
                      at android.app.ActivityThread.main(ActivityThread.java:6145)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:372)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)

**Comment by lipangit** [comment]
如果没什么影响的话最好继承AppCompatActivity，如果不继承在全屏的时候无法隐藏toolbar。
如果实在继承不了就改源码删除hideActionBar()这行。

**Comment by kris-liutao** [comment]
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.zontonec.ztgarden, PID: 10376
                  java.lang.NullPointerException: Attempt to invoke virtual method 'void fm.jiecao.jcvideoplayer_lib.JCResizeTextureView.setVideoSize(android.graphics.Point)' on a null object reference
                      at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.onVideoSizeChanged(JCVideoPlayer.java:578)
                      at fm.jiecao.jcvideoplayer_lib.JCMediaManager$7.run(JCMediaManager.java:228)
                      at android.os.Handler.handleCallback(Handler.java:739)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:145)
                      at android.app.ActivityThread.main(ActivityThread.java:6145)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:372)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
恩恩  好的呢 太谢谢你了   那个我把源码改了 能全屏了   但是当播放手机本身录制的视频时出了个这问题   这个源码也需要改改吗？

**Comment by lipangit** [comment]
理论上setVideoSize的时候JCResizeTextureView不应该为空，如果你不想纠结他的原因，判空一下就好了

**Comment by kris-liutao** [comment]
恩恩  在哪里判为空呀！ @lipangit

**Comment by lipangit** [comment]
setVideoSize 的textureView

**Comment by kris-liutao** [comment]
恩恩 额   问题已经解决了  太感谢你了
