### ISSUE TITLE
全屏状态播放视频完毕BUG？

### ISSUE THREAD

**Issue by Destiny01** [lipangit/JieCaoVideoPlayer#798]
java.lang.NullPointerException: Attempt to invoke virtual method 'void fm.jiecao.jcvideoplayer_lib.JCResizeTextureView.setVideoSize(android.graphics.Point)' on a null object reference
                                                                                   at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.onVideoSizeChanged(JCVideoPlayer.java:578)
                                                                                   at fm.jiecao.jcvideoplayer_lib.JCMediaManager$7.run(JCMediaManager.java:228)

**Comment by lipangit** [comment]
这版本修改

**Comment by lipangit** [comment]
问题太多了改发一版本了

**Comment by Destiny01** [comment]
加油

**Comment by Destiny01** [comment]
http://www.tianshengdiyi.com/upload/APPteacher/zk1.mp4播放这个在线视频缓冲进度条有问题，一卡一卡的，是mp4所在服务器的事吗？

**Comment by lipangit** [comment]
为什么autoComplete的时候会调用videoSizeChange，很令人费解啊

**Comment by lipangit** [comment]
http://www.tianshengdiyi.com/upload/APPteacher/zk1.mp4 这个地址无法访问
