### ISSUE TITLE
华为荣耀7全屏播放闪退

### ISSUE THREAD

**Issue by keyguan** [lipangit/JieCaoVideoPlayer#808]
华为荣耀7全屏播放闪退
操作：全屏播放或转动横竖屏，100%几率闪退
报错日志：04-17 19:27:07.458 8186-8197/com.laka.taste E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
                                                          java.lang.Throwable: Explicit termination method 'release' not called
                                                              at dalvik.system.CloseGuard.open(CloseGuard.java:180)
                                                              at android.view.Surface.setNativeObjectLocked(Surface.java:509)
                                                              at android.view.Surface.<init>(Surface.java:158)
                                                              at fm.jiecao.jcvideoplayer_lib.JCMediaManager$MediaHandler.handleMessage(JCMediaManager.java:123)
                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                              at android.os.Looper.loop(Looper.java:150)
                                                              at android.os.HandlerThread.run(HandlerThread.java:61)
手机信息：
华为荣耀7
PLK-UL00
EMUI系统4.0.2
Android版本6.0
sdk版本：5.5.3/5.2.1/4.8.2

**Comment by tysheng** [comment]
mediaplayer ijk exo全挂？
