### ISSUE TITLE
关于5.2.1版本的必现bug问题

### ISSUE THREAD

**Issue by gaodengjiaoyu** [lipangit/JieCaoVideoPlayer#818]
[大神好！假如您的5.2.1不在维护了，请忽略它吧。要是还在维护，我这边有一个必现的bug，使用JCVideoPlayerStandard播放(http://devimages.apple.com/iphone/samples/bipbop/gear1/prog_index.m3u8)，点击全屏，必然奔溃，bug如下
    java.lang.RuntimeException: Error during detachFromGLContext (see logcat for details)
                                                                                 at android.graphics.SurfaceTexture.attachToGLContext(SurfaceTexture.java:237)
                                                                                 at android.view.GLES20TextureLayer.setSurfaceTexture(GLES20TextureLayer.java:81)
                                                                                 at android.view.HardwareRenderer$Gl20Renderer.setSurfaceTexture(HardwareRenderer.java:1576)
                                                                                 at android.view.TextureView.getHardwareLayer(TextureView.java:393)
                                                                                 at android.view.View.getDisplayList(View.java:12795)
                                                                                 at android.view.View.getDisplayList(View.java:12876)
                                                                                 at android.view.View.draw(View.java:13621)
                                                                                 at android.view.ViewGroup.drawChild(ViewGroup.java:3037)
                                                                                 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2901)
                                                                                 at android.view.View.getDisplayList(View.java:12827)
                                                                                 at android.view.View.getDisplayList(View.java:12876)
                                                                                 at android.view.View.draw(View.java:13621)
                                                                                 at android.view.ViewGroup.drawChild(ViewGroup.java:3037)
                                                                                 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2901)
                                                                                 at android.view.View.draw(View.java:13928)

**Comment by tysheng** [comment]
下载5.5.3源码，改成ijk，ijk的API和mediaplayer几乎一样

**Comment by lipangit** [comment]
请用5.5.2，这个版本更轻量
