### ISSUE TITLE
Bug Play Video Android

### ISSUE THREAD

**Issue by HackJoues** [lipangit/JieCaoVideoPlayer#837]
Im using the Android 4.1.1.

And cant play the video demo of JieCaoVdeoPlayer, this is the LogCat results:

```

04-27 13:28:04.376 1971-1971/fm.jiecao.jiecaovideoplayer D/OpenGLRenderer: TextureCache::callback: name, removed size, mSize = 14, 129600, 1464256
04-27 13:28:04.512 1971-1971/fm.jiecao.jiecaovideoplayer I/JieCaoVideoPlayer: backPress
04-27 13:28:05.740 1971-1971/fm.jiecao.jiecaovideoplayer I/JieCaoVideoPlayer: onClick start [1399947100] 
04-27 13:28:05.740 1971-1971/fm.jiecao.jiecaovideoplayer D/JieCaoVideoPlayer: prepareMediaPlayer [1399947100] 
04-27 13:28:05.740 1971-1971/fm.jiecao.jiecaovideoplayer D/JieCaoVideoPlayer: addTextureView [1399947100] 
04-27 13:28:05.744 1971-1971/fm.jiecao.jiecaovideoplayer I/USER_EVENT: ON_CLICK_START_ICON title is : Titulo del Video url is : http://2449.vod.myqcloud.com/2449_22ca37a6ea9011e5acaaf51d105342e3.f20.mp4 screen is : 2
04-27 13:28:05.744 1971-1971/fm.jiecao.jiecaovideoplayer I/JCResizeTextureView: onMeasure  [1399947548] 
04-27 13:28:05.744 1971-1971/fm.jiecao.jiecaovideoplayer I/JCResizeTextureView: videoWidth = 0, videoHeight = 0
04-27 13:28:05.744 1971-1971/fm.jiecao.jiecaovideoplayer I/JCResizeTextureView: viewRotation = 0
04-27 13:28:05.748 1971-1971/fm.jiecao.jiecaovideoplayer I/JCResizeTextureView: onMeasure  [1399947548] 
04-27 13:28:05.748 1971-1971/fm.jiecao.jiecaovideoplayer I/JCResizeTextureView: videoWidth = 0, videoHeight = 0
04-27 13:28:05.756 1971-1971/fm.jiecao.jiecaovideoplayer I/JCResizeTextureView: viewRotation = 0
04-27 13:28:05.760 1971-1971/fm.jiecao.jiecaovideoplayer I/JCResizeTextureView: onMeasure  [1399947548] 
04-27 13:28:05.760 1971-1971/fm.jiecao.jiecaovideoplayer I/JCResizeTextureView: videoWidth = 0, videoHeight = 0
04-27 13:28:05.760 1971-1971/fm.jiecao.jiecaovideoplayer I/JCResizeTextureView: viewRotation = 0
04-27 13:28:05.760 1971-1971/fm.jiecao.jiecaovideoplayer I/JCResizeTextureView: onMeasure  [1399947548] 
04-27 13:28:05.760 1971-1971/fm.jiecao.jiecaovideoplayer I/JCResizeTextureView: videoWidth = 0, videoHeight = 0
04-27 13:28:05.760 1971-1971/fm.jiecao.jiecaovideoplayer I/JCResizeTextureView: viewRotation = 0
04-27 13:28:05.772 1971-1971/fm.jiecao.jiecaovideoplayer I/JCResizeTextureView: onMeasure  [1399947548] 
04-27 13:28:05.772 1971-1971/fm.jiecao.jiecaovideoplayer I/JCResizeTextureView: videoWidth = 0, videoHeight = 0
04-27 13:28:05.772 1971-1971/fm.jiecao.jiecaovideoplayer I/JCResizeTextureView: viewRotation = 0
04-27 13:28:05.772 1971-1971/fm.jiecao.jiecaovideoplayer I/JCResizeTextureView: onMeasure  [1399947548] 
04-27 13:28:05.772 1971-1971/fm.jiecao.jiecaovideoplayer I/JCResizeTextureView: videoWidth = 0, videoHeight = 0
04-27 13:28:05.772 1971-1971/fm.jiecao.jiecaovideoplayer I/JCResizeTextureView: viewRotation = 0
04-27 13:28:05.780 1971-1971/fm.jiecao.jiecaovideoplayer I/JieCaoVideoPlayer: onSurfaceTextureAvailable [1400058652] 
04-27 13:28:05.780 1971-2008/fm.jiecao.jiecaovideoplayer W/MediaPlayer: setScreenOnWhilePlaying(true) is ineffective without a SurfaceHolder
04-27 13:28:05.780 1971-2008/fm.jiecao.jiecaovideoplayer W/MediaPlayer: setScreenOnWhilePlaying(true) is ineffective for Surface
04-27 13:28:06.268 1971-1971/fm.jiecao.jiecaovideoplayer I/JCResizeTextureView: onMeasure  [1399947548] 
04-27 13:28:06.268 1971-1971/fm.jiecao.jiecaovideoplayer I/JCResizeTextureView: videoWidth = 0, videoHeight = 0
04-27 13:28:06.268 1971-1971/fm.jiecao.jiecaovideoplayer I/JCResizeTextureView: viewRotation = 0
04-27 13:28:06.300 1971-1971/fm.jiecao.jiecaovideoplayer I/JCResizeTextureView: onMeasure  [1399947548] 
04-27 13:28:06.304 1971-1971/fm.jiecao.jiecaovideoplayer I/JCResizeTextureView: videoWidth = 0, videoHeight = 0
04-27 13:28:06.304 1971-1971/fm.jiecao.jiecaovideoplayer I/JCResizeTextureView: viewRotation = 0
04-27 13:28:11.400 1971-1981/fm.jiecao.jiecaovideoplayer E/MediaPlayer: error (1, -2147483648)
04-27 13:28:11.400 1971-2008/fm.jiecao.jiecaovideoplayer E/MediaPlayer: Error (1,-2147483648)
04-27 13:28:11.456 1971-1971/fm.jiecao.jiecaovideoplayer I/JieCaoVideoPlayer: onVideoSizeChanged  [1399947100] 
04-27 13:28:11.456 1971-1971/fm.jiecao.jiecaovideoplayer I/JieCaoVideoPlayer: onPrepared  [1399947100] 
04-27 13:28:11.580 1971-1971/fm.jiecao.jiecaovideoplayer I/JCResizeTextureView: onMeasure  [1399947548] 
04-27 13:28:11.580 1971-1971/fm.jiecao.jiecaovideoplayer I/JCResizeTextureView: videoWidth = 640, videoHeight = 480
04-27 13:28:11.580 1971-1971/fm.jiecao.jiecaovideoplayer I/JCResizeTextureView: viewRotation = 0
04-27 13:28:11.580 1971-1971/fm.jiecao.jiecaovideoplayer I/JCResizeTextureView: widthMeasureSpec  [MeasureSpec: EXACTLY 720]
04-27 13:28:11.580 1971-1971/fm.jiecao.jiecaovideoplayer I/JCResizeTextureView: heightMeasureSpec [MeasureSpec: EXACTLY 1184]
04-27 13:28:11.580 1971-1971/fm.jiecao.jiecaovideoplayer I/JCResizeTextureView: onMeasure  [1399947548] 
04-27 13:28:11.580 1971-1971/fm.jiecao.jiecaovideoplayer I/JCResizeTextureView: videoWidth = 640, videoHeight = 480
04-27 13:28:11.580 1971-1971/fm.jiecao.jiecaovideoplayer I/JCResizeTextureView: viewRotation = 0
04-27 13:28:11.580 1971-1971/fm.jiecao.jiecaovideoplayer I/JCResizeTextureView: widthMeasureSpec  [MeasureSpec: EXACTLY 720]
04-27 13:28:11.580 1971-1971/fm.jiecao.jiecaovideoplayer I/JCResizeTextureView: heightMeasureSpec [MeasureSpec: EXACTLY 1184]
04-27 13:28:11.580 1971-1971/fm.jiecao.jiecaovideoplayer I/JieCaoVideoPlayer: onSurfaceTextureSizeChanged [1400058652] 
04-27 13:28:11.588 1971-1971/fm.jiecao.jiecaovideoplayer E/JieCaoVideoPlayer: onError 1 - -2147483648 [1399947100] 
04-27 13:28:11.632 1971-1971/fm.jiecao.jiecaovideoplayer W/System.err: java.lang.IllegalStateException
04-27 13:28:11.632 1971-1971/fm.jiecao.jiecaovideoplayer W/System.err:     at android.media.MediaPlayer.getDuration(Native Method)
04-27 13:28:11.632 1971-1971/fm.jiecao.jiecaovideoplayer W/System.err:     at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.getDuration(JCVideoPlayer.java:737)
04-27 13:28:11.632 1971-1971/fm.jiecao.jiecaovideoplayer W/System.err:     at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.setProgressAndText(JCVideoPlayer.java:747)
04-27 13:28:11.632 1971-1971/fm.jiecao.jiecaovideoplayer W/System.err:     at fm.jiecao.jcvideoplayer_lib.JCVideoPlayerStandard.setProgressAndText(JCVideoPlayerStandard.java:321)
04-27 13:28:11.632 1971-1971/fm.jiecao.jiecaovideoplayer W/System.err:     at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer$ProgressTimerTask$1.run(JCVideoPlayer.java:709)
04-27 13:28:11.632 1971-1971/fm.jiecao.jiecaovideoplayer W/System.err:     at android.os.Handler.handleCallback(Handler.java:615)
04-27 13:28:11.632 1971-1971/fm.jiecao.jiecaovideoplayer W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:92)
04-27 13:28:11.632 1971-1971/fm.jiecao.jiecaovideoplayer W/System.err:     at android.os.Looper.loop(Looper.java:137)
04-27 13:28:11.632 1971-1971/fm.jiecao.jiecaovideoplayer W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:4745)
04-27 13:28:11.632 1971-1971/fm.jiecao.jiecaovideoplayer W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
04-27 13:28:11.632 1971-1971/fm.jiecao.jiecaovideoplayer W/System.err:     at java.lang.reflect.Method.invoke(Method.java:511)
04-27 13:28:11.632 1971-1971/fm.jiecao.jiecaovideoplayer W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
04-27 13:28:11.632 1971-1971/fm.jiecao.jiecaovideoplayer W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
04-27 13:28:11.636 1971-1971/fm.jiecao.jiecaovideoplayer W/System.err:     at dalvik.system.NativeStart.main(Native Method)
04-27 13:28:11.636 1971-1971/fm.jiecao.jiecaovideoplayer W/System.err: java.lang.IllegalStateException
04-27 13:28:11.636 1971-1971/fm.jiecao.jiecaovideoplayer W/System.err:     at android.media.MediaPlayer.getDuration(Native Method)
04-27 13:28:11.636 1971-1971/fm.jiecao.jiecaovideoplayer W/System.err:     at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.getDuration(JCVideoPlayer.java:737)
04-27 13:28:11.636 1971-1971/fm.jiecao.jiecaovideoplayer W/System.err:     at fm.jiecao.jcvideoplayer_lib.JCVideoPlayerStandard.setProgressAndText(JCVideoPlayerStandard.java:323)
04-27 13:28:11.636 1971-1971/fm.jiecao.jiecaovideoplayer W/System.err:     at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer$ProgressTimerTask$1.run(JCVideoPlayer.java:709)
04-27 13:28:11.636 1971-1971/fm.jiecao.jiecaovideoplayer W/System.err:     at android.os.Handler.handleCallback(Handler.java:615)
04-27 13:28:11.636 1971-1971/fm.jiecao.jiecaovideoplayer W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:92)
04-27 13:28:11.636 1971-1971/fm.jiecao.jiecaovideoplayer W/System.err:     at android.os.Looper.loop(Looper.java:137)
04-27 13:28:11.636 1971-1971/fm.jiecao.jiecaovideoplayer W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:4745)
04-27 13:28:11.636 1971-1971/fm.jiecao.jiecaovideoplayer W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
04-27 13:28:11.636 1971-1971/fm.jiecao.jiecaovideoplayer W/System.err:     at java.lang.reflect.Method.invoke(Method.java:511)
04-27 13:28:11.636 1971-1971/fm.jiecao.jiecaovideoplayer W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
04-27 13:28:11.636 1971-1971/fm.jiecao.jiecaovideoplayer W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
04-27 13:28:11.636 1971-1971/fm.jiecao.jiecaovideoplayer W/System.err:     at dalvik.system.NativeStart.main(Native Method)

```

**Comment by lipangit** [comment]
用新版，这个问题已经解决

**Comment by HackJoues** [comment]
I have the most recently version :(

**Comment by HackJoues** [comment]
I test the demo, in real phone, I don't have Emulator
