### ISSUE TITLE
视频还没准备好时，进行拖拽进度条，出现崩溃

### ISSUE THREAD

**Issue by MycroftWong** [lipangit/JieCaoVideoPlayer#87]
点击播放，视频还在加载，拖拽进度条，崩溃了，下面是log，版本3.0
```
TONE_RELATIVE_VOLUME=80
SUPPORTED_64_BIT_ABIS=[Ljava.lang.String;@27a9d59d
versionCode=15
BOARD=unknown
BOOTLOADER=unknown
TYPE=user
ID=LRX22G
TIME=1462282993000
BRAND=Xiaomi
TAG=Build
SERIAL=MRQWIJLN99999999
HARDWARE=mt6795
SUPPORTED_ABIS=[Ljava.lang.String;@36d3fa12
CPU_ABI=arm64-v8a
IS_DEBUGGABLE=false
RADIO=unknown
MANUFACTURER=Xiaomi
SUPPORTED_32_BIT_ABIS=[Ljava.lang.String;@eb80c47
TAGS=release-keys
CPU_ABI2=
UNKNOWN=unknown
USER=builder
FINGERPRINT=Xiaomi/hermes/hermes:5.0.2/LRX22G/V7.3.1.0.LHMCNDD:user/release-keys
HOST=zc-miui-ota-bd38.bj
PRODUCT=hermes
versionName=V2.0.0
DISPLAY=LRX22G
MODEL=Redmi Note 2
DEVICE=hermes
java.lang.IllegalStateException
	at android.media.MediaPlayer.getDuration(Native Method)
	at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.onProgressChanged(JCVideoPlayer.java:246)
	at android.widget.SeekBar.onProgressRefresh(SeekBar.java:95)
	at android.widget.ProgressBar.doRefreshProgress(ProgressBar.java:1262)
	at android.widget.ProgressBar.refreshProgress(ProgressBar.java:1309)
	at android.widget.ProgressBar.refreshProgress(ProgressBar.java:1303)
	at android.widget.ProgressBar.setProgress(ProgressBar.java:1360)
	at android.widget.AbsSeekBar.setProgress(AbsSeekBar.java:753)
	at android.widget.AbsSeekBar.trackTouchEvent(AbsSeekBar.java:683)
	at android.widget.AbsSeekBar.onTouchEvent(AbsSeekBar.java:603)
	at android.view.View.dispatchTouchEvent(View.java:8497)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2546)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2239)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2546)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2239)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2546)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2239)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2546)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2239)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2546)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2239)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2546)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2239)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2546)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2239)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2546)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2239)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2546)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2239)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2398)
	at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1739)
	at android.app.Activity.dispatchTouchEvent(Activity.java:2781)
	at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2359)
	at android.view.View.dispatchPointerEvent(View.java:8698)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4530)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4388)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3924)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3977)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3943)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4053)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3951)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4110)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3924)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3977)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3943)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3951)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3924)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6345)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6301)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6254)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6507)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:6466)
	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6538)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:802)
	at android.view.Choreographer.doCallbacks(Choreographer.java:605)
	at android.view.Choreographer.doFrame(Choreographer.java:572)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:788)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5549)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)
```

**Comment by lipangit** [comment]
我试了一下，会进入error状态，但是都不会闪退，下个版本会解决这个问题
在getDuration的时候崩溃还是很意外

多谢反馈
