### ISSUE TITLE
JieCaoVideoPlayer 横竖屏切换直接闪退

### ISSUE THREAD

**Issue by jv-lee** [lipangit/JieCaoVideoPlayer#929]
只要所在Activity 的 Theme中 带有 <item name="android:windowIsTranslucent">true</item> 属性 ， 则切换横竖屏 直接闪退。

**Comment by QinAndroid** [comment]
我也遇到了，解决没？

**Comment by qinyang1018** [comment]
你们闪退的日志是什么呢？

**Comment by BuleB** [comment]
Error during detachFromGLContext (see logcat for details)
                                                                          at android.graphics.SurfaceTexture.attachToGLContext(SurfaceTexture.java:237)
                                                                          at android.view.GLES20TextureLayer.setSurfaceTexture(GLES20TextureLayer.java:81)
                                                                          at android.view.HardwareRenderer$Gl20Renderer.setSurfaceTexture(HardwareRenderer.java:1576)
                                                                          at android.view.TextureView.getHardwareLayer(TextureView.java:393)
                                                                          at android.view.View.getDisplayList(View.java:12809)
                                                                          at android.view.View.getDisplayList(View.java:12890)
                                                                          at android.view.View.draw(View.java:13640)
                                                                          at android.view.ViewGroup.drawChild(ViewGroup.java:3050)
                                                                          at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2912)
                                                                          at android.view.View.getDisplayList(View.java:12841)
                                                                          at android.view.View.getDisplayList(View.java:12890)
                                                                          at android.view.View.draw(View.java:13640)
                                                                          at android.view.ViewGroup.drawChild(ViewGroup.java:3050)
                                                                          at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2912)
                                                                          at android.view.View.draw(View.java:13947)
                                                                          at android.view.View.getDisplayList(View.java:12846)
                                                                          at android.view.View.getDisplayList(View.java:12890)
                                                                          at android.view.View.draw(View.java:13640)
                                                                          at android.view.ViewGroup.drawChild(ViewGroup.java:3050)
                                                                          at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2912)
                                                                          at android.view.View.getDisplayList(View.java:12841)
                                                                          at android.view.View.getDisplayList(View.java:12890)
                                                                          at android.view.View.draw(View.java:13640)
                                                                          at android.view.ViewGroup.drawChild(ViewGroup.java:3050)
                                                                          at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2912)
                                                                          at android.view.View.getDisplayList(View.java:12841)
                                                                          at android.view.View.getDisplayList(View.java:12890)
                                                                          at android.view.View.draw(View.java:13640)
                                                                          at android.view.ViewGroup.drawChild(ViewGroup.java:3050)
                                                                          at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2912)
                                                                          at android.view.View.getDisplayList(View.java:12841)
                                                                          at android.view.View.getDisplayList(View.java:12890)
                                                                          at android.view.View.draw(View.java:13640)
                                                                          at android.view.ViewGroup.drawChild(ViewGroup.java:3050)
                                                                          at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2912)
                                                                          at android.view.View.draw(View.java:13947)
                                                                          at android.widget.FrameLayout.draw(FrameLayout.java:467)
                                                                          at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2247)
                                                                          at android.view.View.getDisplayList(View.java:12846)
                                                                          at android.view.View.getDisplayList(View.java:12890)
                                                                          at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1249)
                                                                          at android.view.ViewRootImpl.draw(ViewRootImpl.java:2572)
                                                                          at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2439)
                                                                          at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2241)
                                                                          at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1216)
                                                                          at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5044)
                                                                          at android.view.Choreographer$CallbackRecord.run(Choreographer.java:776)
                                                                          at android.view.Choreographer.doCallbacks(Choreographer.java:579)
                                                                          at android.view.Choreographer.doFrame(Choreographer.java:548)
                                                                          at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:762)
                                                                          at android.os.Handler.handleCallback(Handler.java:800)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:100)
                                                                          at android.os.Looper.loop(Looper.java:194)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5433)
                                                                          at java.lang.reflect.Method.invokeNative(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:525)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:922)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:689)
                                                                          at dalvik.system.NativeStart.main(Native Method)

**Comment by BuleB** [comment]
这个是在华为H30-T00 4.2.2 横竖屏切换的时候崩溃日志。 其它机型没问题
