### ISSUE TITLE
FATAL EXCEPTION | JCVideoPlayer :880

### ISSUE THREAD

**Issue by qaisershehzad** [lipangit/JieCaoVideoPlayer#969]
Hello, 
I am playing video in fragment. It plays well first time but on replay it crashes.

java.lang.NullPointerException: Attempt to invoke virtual method 'android.support.v7.app.ActionBar android.support.v7.app.AppCompatActivity.getSupportActionBar()' on a null object reference
                                                                      at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.showSupportActionBar(JCVideoPlayer.java:880)
                                                                      at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.clearFullscreenLayout(JCVideoPlayer.java:446)
                                                                      at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.onCompletion(JCVideoPlayer.java:484)
                                                                      at fm.jiecao.jcvideoplayer_lib.JCVideoPlayerStandard.onCompletion(JCVideoPlayerStandard.java:778)
                                                                      at fm.jiecao.jcvideoplayer_lib.JCVideoPlayerManager.completeAll(JCVideoPlayerManager.java:42)
                                                                      at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.prepareMediaPlayer(JCVideoPlayer.java:199)
                                                                      at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.onClick(JCVideoPlayer.java:179)
                                                                      at fm.jiecao.jcvideoplayer_lib.JCVideoPlayerStandard.onClick(JCVideoPlayerStandard.java:176)
                                                                      at android.view.View.performClick(View.java:5156)
                                                                      at android.view.View$PerformClick.run(View.java:20755)
                                                                      at android.os.Handler.handleCallback(Handler.java:739)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                      at

**Comment by lipangit** [comment]
Activity extends AppCompatActivity

**Comment by qaisershehzad** [comment]
Thanks am able to resolve.
