### ISSUE TITLE
RecylerView列表中播放，滑动后Crash

### ISSUE THREAD

**Issue by axeon** [lipangit/JieCaoVideoPlayer#98]
RecylerView列表中播放，未关闭，滑动后导致Crash。。。

java.lang.IllegalStateException
    at android.media.MediaPlayer._setVideoSurface(Native Method)
    at android.media.MediaPlayer.setDisplay(MediaPlayer.java:731)
    at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.setDisplayCaseFailed(JCVideoPlayer.java:436)
    at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.surfaceCreated(JCVideoPlayer.java:430)
    at android.view.SurfaceView.updateWindow(SurfaceView.java:597)
    at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:179)
    at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2091)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1143)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6054)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:860)
    at android.view.Choreographer.doCallbacks(Choreographer.java:672)
    at android.view.Choreographer.doFrame(Choreographer.java:608)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:846)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5456)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:735)

Attempt to invoke interface method 'void android.view.IWindowSession.finishDrawing(android.view.IWindow)' on a null object reference
                                                                java.lang.NullPointerException: Attempt to invoke interface method 'void android.view.IWindowSession.finishDrawing(android.view.IWindow)' on a null object reference
                                                                    at android.view.SurfaceView.updateWindow(SurfaceView.java:628)
                                                                    at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:179)
                                                                    at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
                                                                    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2091)
                                                                    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1143)
                                                                    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6054)
                                                                    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:860)
                                                                    at android.view.Choreographer.doCallbacks(Choreographer.java:672)
                                                                    at android.view.Choreographer.doFrame(Choreographer.java:608)
                                                                    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:846)
                                                                    at android.os.Handler.handleCallback(Handler.java:739)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                    at android.os.Looper.loop(Looper.java:148)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5456)

**Comment by lipangit** [comment]
How is it going, release()

**Comment by axeon** [comment]
依旧闪退中。。。

**Comment by lipangit** [comment]
a90f5566ecf3370c302fbe556d13c3b3ffad4b23

fix
