### ISSUE TITLE
在列表中点击全屏播放，第一条视频播放完成后继续全屏播放第二条视频的时候 抛异常

### ISSUE THREAD

**Issue by QinAndroid** [lipangit/JieCaoVideoPlayer#980]
```java
java.lang.IllegalStateException
06-20 16:17:17.457 19220-19220/com.uf.ufballtest W/System.err:     at android.media.MediaPlayer.getCurrentPosition(Native Method)
06-20 16:17:17.457 19220-19220/com.uf.ufballtest W/System.err:     at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.getCurrentPositionWhenPlaying(JCVideoPlayer.java:721)
06-20 16:17:17.457 19220-19220/com.uf.ufballtest W/System.err:     at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.onCompletion(JCVideoPlayer.java:470)
06-20 16:17:17.458 19220-19220/com.uf.ufballtest W/System.err:     at fm.jiecao.jcvideoplayer_lib.JCVideoPlayerStandard.onCompletion(JCVideoPlayerStandard.java:778)
06-20 16:17:17.458 19220-19220/com.uf.ufballtest W/System.err:     at fm.jiecao.jcvideoplayer_lib.JCVideoPlayerManager.completeAll(JCVideoPlayerManager.java:42)
06-20 16:17:17.458 19220-19220/com.uf.ufballtest W/System.err:     at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.prepareMediaPlayer(JCVideoPlayer.java:199)
06-20 16:17:17.458 19220-19220/com.uf.ufballtest W/System.err:     at fm.jiecao.jcvideoplayer_lib.JCVideoPlayerStandard.startVideo(JCVideoPlayerStandard.java:252)
06-20 16:17:17.458 19220-19220/com.uf.ufballtest W/System.err:     at fm.jiecao.jcvideoplayer_lib.JCVideoPlayerStandard.onClick(JCVideoPlayerStandard.java:189)
06-20 16:17:17.458 19220-19220/com.uf.ufballtest W/System.err:     at android.view.View.performClick(View.java:5207)
06-20 16:17:17.458 19220-19220/com.uf.ufballtest W/System.err:     at android.view.View$PerformClick.run(View.java:21177)
06-20 16:17:17.458 19220-19220/com.uf.ufballtest W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
06-20 16:17:17.458 19220-19220/com.uf.ufballtest W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
06-20 16:17:17.458 19220-19220/com.uf.ufballtest W/System.err:     at android.os.Looper.loop(Looper.java:148)
06-20 16:17:17.458 19220-19220/com.uf.ufballtest W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5458)
06-20 16:17:17.458 19220-19220/com.uf.ufballtest W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
06-20 16:17:17.458 19220-19220/com.uf.ufballtest W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
06-20 16:17:17.458 19220-19220/com.uf.ufballtest W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)
```
在列表中点击全屏播放，第一条视频播放完成后继续全屏播放第二条视频的时候 抛异常
```java 
url = data.getVideoUrl();
videoType = VIDEO_POSITIVE;
player.setUp(url, JCVideoPlayer.SCREEN_WINDOW_FULLSCREEN, "", data.getVideoId());
player.startButton.performClick();
//JCVideoPlayer.startFullscreen(getContext(), VideoPlayer.class, url, "");
```

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/27340325-cde5485e-560c-11e7-95b5-ed4acedc1777.png)
这个try catch不管用吗

**Comment by QinAndroid** [comment]
能留个QQ交流吗？我这边用到播放器遇到了点问题 继续大神帮助

**Comment by lipangit** [comment]
Q群:490442439 验证信息:jcvd

**Comment by qinyang1018** [comment]
使用
```JCVideoPlayerStandard.startFullscreen(mContext, VideoPlayer.class, proxy.getProxyUrl(url),"");
```
 全屏播放下一集前要
```JCVideoPlayerStandard.releaseAllVideos();```
释放下
